/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.resources.webhookevents;

import com.vitablehealth.connect.core.ClientOptions;
import com.vitablehealth.connect.core.RequestOptions;
import com.vitablehealth.connect.core.pagination.SyncPagingIterable;
import com.vitablehealth.connect.resources.webhookevents.requests.GetWebhookEventsRequest;
import com.vitablehealth.connect.resources.webhookevents.requests.ListDeliveriesWebhookEventsRequest;
import com.vitablehealth.connect.resources.webhookevents.requests.ListWebhookEventsRequest;
import com.vitablehealth.connect.types.ListWebhookEventDeliveriesResponse;
import com.vitablehealth.connect.types.WebhookEvent;
import com.vitablehealth.connect.types.WebhookEventResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncWebhookEventsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawWebhookEventsClient rawClient;

    public AsyncWebhookEventsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawWebhookEventsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawWebhookEventsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieves a paginated list of webhook events for the authenticated organization. Supports filtering by event name, resource type, resource ID, and date range.
     */
    public CompletableFuture<SyncPagingIterable<WebhookEvent>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieves a paginated list of webhook events for the authenticated organization. Supports filtering by event name, resource type, resource ID, and date range.
     */
    public CompletableFuture<SyncPagingIterable<WebhookEvent>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves a paginated list of webhook events for the authenticated organization. Supports filtering by event name, resource type, resource ID, and date range.
     */
    public CompletableFuture<SyncPagingIterable<WebhookEvent>> list(ListWebhookEventsRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Retrieves a paginated list of webhook events for the authenticated organization. Supports filtering by event name, resource type, resource ID, and date range.
     */
    public CompletableFuture<SyncPagingIterable<WebhookEvent>> list(
            ListWebhookEventsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves a single webhook event by its prefixed ID. Returns 404 if the event does not exist or belongs to a different organization.
     */
    public CompletableFuture<WebhookEventResponse> get(String eventId) {
        return this.rawClient.get(eventId).thenApply(response -> response.body());
    }

    /**
     * Retrieves a single webhook event by its prefixed ID. Returns 404 if the event does not exist or belongs to a different organization.
     */
    public CompletableFuture<WebhookEventResponse> get(String eventId, RequestOptions requestOptions) {
        return this.rawClient.get(eventId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves a single webhook event by its prefixed ID. Returns 404 if the event does not exist or belongs to a different organization.
     */
    public CompletableFuture<WebhookEventResponse> get(String eventId, GetWebhookEventsRequest request) {
        return this.rawClient.get(eventId, request).thenApply(response -> response.body());
    }

    /**
     * Retrieves a single webhook event by its prefixed ID. Returns 404 if the event does not exist or belongs to a different organization.
     */
    public CompletableFuture<WebhookEventResponse> get(
            String eventId, GetWebhookEventsRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(eventId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves all delivery attempts for a webhook event. Returns up to 100 deliveries. Each delivery includes a computed status field (Pending, In Progress, Delivered, or Failed).
     */
    public CompletableFuture<ListWebhookEventDeliveriesResponse> listDeliveries(String eventId) {
        return this.rawClient.listDeliveries(eventId).thenApply(response -> response.body());
    }

    /**
     * Retrieves all delivery attempts for a webhook event. Returns up to 100 deliveries. Each delivery includes a computed status field (Pending, In Progress, Delivered, or Failed).
     */
    public CompletableFuture<ListWebhookEventDeliveriesResponse> listDeliveries(
            String eventId, RequestOptions requestOptions) {
        return this.rawClient.listDeliveries(eventId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves all delivery attempts for a webhook event. Returns up to 100 deliveries. Each delivery includes a computed status field (Pending, In Progress, Delivered, or Failed).
     */
    public CompletableFuture<ListWebhookEventDeliveriesResponse> listDeliveries(
            String eventId, ListDeliveriesWebhookEventsRequest request) {
        return this.rawClient.listDeliveries(eventId, request).thenApply(response -> response.body());
    }

    /**
     * Retrieves all delivery attempts for a webhook event. Returns up to 100 deliveries. Each delivery includes a computed status field (Pending, In Progress, Delivered, or Failed).
     */
    public CompletableFuture<ListWebhookEventDeliveriesResponse> listDeliveries(
            String eventId, ListDeliveriesWebhookEventsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listDeliveries(eventId, request, requestOptions).thenApply(response -> response.body());
    }
}
