/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.resources.webhookevents;

import com.vitablehealth.connect.core.ClientOptions;
import com.vitablehealth.connect.core.RequestOptions;
import com.vitablehealth.connect.core.pagination.SyncPagingIterable;
import com.vitablehealth.connect.resources.webhookevents.requests.GetWebhookEventsRequest;
import com.vitablehealth.connect.resources.webhookevents.requests.ListDeliveriesWebhookEventsRequest;
import com.vitablehealth.connect.resources.webhookevents.requests.ListWebhookEventsRequest;
import com.vitablehealth.connect.types.ListWebhookEventDeliveriesResponse;
import com.vitablehealth.connect.types.WebhookEvent;
import com.vitablehealth.connect.types.WebhookEventResponse;

public class WebhookEventsClient {
    protected final ClientOptions clientOptions;

    private final RawWebhookEventsClient rawClient;

    public WebhookEventsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawWebhookEventsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawWebhookEventsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieves a paginated list of webhook events for the authenticated organization. Supports filtering by event name, resource type, resource ID, and date range.
     */
    public SyncPagingIterable<WebhookEvent> list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieves a paginated list of webhook events for the authenticated organization. Supports filtering by event name, resource type, resource ID, and date range.
     */
    public SyncPagingIterable<WebhookEvent> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Retrieves a paginated list of webhook events for the authenticated organization. Supports filtering by event name, resource type, resource ID, and date range.
     */
    public SyncPagingIterable<WebhookEvent> list(ListWebhookEventsRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieves a paginated list of webhook events for the authenticated organization. Supports filtering by event name, resource type, resource ID, and date range.
     */
    public SyncPagingIterable<WebhookEvent> list(ListWebhookEventsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Retrieves a single webhook event by its prefixed ID. Returns 404 if the event does not exist or belongs to a different organization.
     */
    public WebhookEventResponse get(String eventId) {
        return this.rawClient.get(eventId).body();
    }

    /**
     * Retrieves a single webhook event by its prefixed ID. Returns 404 if the event does not exist or belongs to a different organization.
     */
    public WebhookEventResponse get(String eventId, RequestOptions requestOptions) {
        return this.rawClient.get(eventId, requestOptions).body();
    }

    /**
     * Retrieves a single webhook event by its prefixed ID. Returns 404 if the event does not exist or belongs to a different organization.
     */
    public WebhookEventResponse get(String eventId, GetWebhookEventsRequest request) {
        return this.rawClient.get(eventId, request).body();
    }

    /**
     * Retrieves a single webhook event by its prefixed ID. Returns 404 if the event does not exist or belongs to a different organization.
     */
    public WebhookEventResponse get(String eventId, GetWebhookEventsRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(eventId, request, requestOptions).body();
    }

    /**
     * Retrieves all delivery attempts for a webhook event. Returns up to 100 deliveries. Each delivery includes a computed status field (Pending, In Progress, Delivered, or Failed).
     */
    public ListWebhookEventDeliveriesResponse listDeliveries(String eventId) {
        return this.rawClient.listDeliveries(eventId).body();
    }

    /**
     * Retrieves all delivery attempts for a webhook event. Returns up to 100 deliveries. Each delivery includes a computed status field (Pending, In Progress, Delivered, or Failed).
     */
    public ListWebhookEventDeliveriesResponse listDeliveries(String eventId, RequestOptions requestOptions) {
        return this.rawClient.listDeliveries(eventId, requestOptions).body();
    }

    /**
     * Retrieves all delivery attempts for a webhook event. Returns up to 100 deliveries. Each delivery includes a computed status field (Pending, In Progress, Delivered, or Failed).
     */
    public ListWebhookEventDeliveriesResponse listDeliveries(
            String eventId, ListDeliveriesWebhookEventsRequest request) {
        return this.rawClient.listDeliveries(eventId, request).body();
    }

    /**
     * Retrieves all delivery attempts for a webhook event. Returns up to 100 deliveries. Each delivery includes a computed status field (Pending, In Progress, Delivered, or Failed).
     */
    public ListWebhookEventDeliveriesResponse listDeliveries(
            String eventId, ListDeliveriesWebhookEventsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listDeliveries(eventId, request, requestOptions).body();
    }
}
