/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.resources.plans;

import com.vitablehealth.connect.core.ClientOptions;
import com.vitablehealth.connect.core.RequestOptions;
import com.vitablehealth.connect.core.pagination.SyncPagingIterable;
import com.vitablehealth.connect.resources.plans.requests.ListPlansRequest;
import com.vitablehealth.connect.types.Plan;
import java.util.concurrent.CompletableFuture;

public class AsyncPlansClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawPlansClient rawClient;

    public AsyncPlansClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawPlansClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawPlansClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a paginated list of benefit plans linked to the authenticated organization.
     */
    public CompletableFuture<SyncPagingIterable<Plan>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Returns a paginated list of benefit plans linked to the authenticated organization.
     */
    public CompletableFuture<SyncPagingIterable<Plan>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a paginated list of benefit plans linked to the authenticated organization.
     */
    public CompletableFuture<SyncPagingIterable<Plan>> list(ListPlansRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Returns a paginated list of benefit plans linked to the authenticated organization.
     */
    public CompletableFuture<SyncPagingIterable<Plan>> list(ListPlansRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }
}
