/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AccessTokenResponse.Builder.class)
public final class AccessTokenResponse {
    private final String accessToken;

    private final String tokenType;

    private final int expiresIn;

    private final Optional<BoundEntityResponse> boundEntity;

    private final Map<String, Object> additionalProperties;

    private AccessTokenResponse(
            String accessToken,
            String tokenType,
            int expiresIn,
            Optional<BoundEntityResponse> boundEntity,
            Map<String, Object> additionalProperties) {
        this.accessToken = accessToken;
        this.tokenType = tokenType;
        this.expiresIn = expiresIn;
        this.boundEntity = boundEntity;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The issued access token (vit_at_*)
     */
    @JsonProperty("access_token")
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * @return Token type, always 'Bearer'
     */
    @JsonProperty("token_type")
    public String getTokenType() {
        return tokenType;
    }

    /**
     * @return Token lifetime in seconds
     */
    @JsonProperty("expires_in")
    public int getExpiresIn() {
        return expiresIn;
    }

    /**
     * @return Entity the token is bound to, if any
     */
    @JsonIgnore
    public Optional<BoundEntityResponse> getBoundEntity() {
        if (boundEntity == null) {
            return Optional.empty();
        }
        return boundEntity;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("bound_entity")
    private Optional<BoundEntityResponse> _getBoundEntity() {
        return boundEntity;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AccessTokenResponse && equalTo((AccessTokenResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AccessTokenResponse other) {
        return accessToken.equals(other.accessToken)
                && tokenType.equals(other.tokenType)
                && expiresIn == other.expiresIn
                && boundEntity.equals(other.boundEntity);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.accessToken, this.tokenType, this.expiresIn, this.boundEntity);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AccessTokenStage builder() {
        return new Builder();
    }

    public interface AccessTokenStage {
        /**
         * <p>The issued access token (vit_at_*)</p>
         */
        TokenTypeStage accessToken(@NotNull String accessToken);

        Builder from(AccessTokenResponse other);
    }

    public interface TokenTypeStage {
        /**
         * <p>Token type, always 'Bearer'</p>
         */
        ExpiresInStage tokenType(@NotNull String tokenType);
    }

    public interface ExpiresInStage {
        /**
         * <p>Token lifetime in seconds</p>
         */
        _FinalStage expiresIn(int expiresIn);
    }

    public interface _FinalStage {
        AccessTokenResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Entity the token is bound to, if any</p>
         */
        _FinalStage boundEntity(Optional<BoundEntityResponse> boundEntity);

        _FinalStage boundEntity(BoundEntityResponse boundEntity);

        _FinalStage boundEntity(Nullable<BoundEntityResponse> boundEntity);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AccessTokenStage, TokenTypeStage, ExpiresInStage, _FinalStage {
        private String accessToken;

        private String tokenType;

        private int expiresIn;

        private Optional<BoundEntityResponse> boundEntity = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AccessTokenResponse other) {
            accessToken(other.getAccessToken());
            tokenType(other.getTokenType());
            expiresIn(other.getExpiresIn());
            boundEntity(other.getBoundEntity());
            return this;
        }

        /**
         * <p>The issued access token (vit_at_*)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("access_token")
        public TokenTypeStage accessToken(@NotNull String accessToken) {
            this.accessToken = Objects.requireNonNull(accessToken, "accessToken must not be null");
            return this;
        }

        /**
         * <p>Token type, always 'Bearer'</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("token_type")
        public ExpiresInStage tokenType(@NotNull String tokenType) {
            this.tokenType = Objects.requireNonNull(tokenType, "tokenType must not be null");
            return this;
        }

        /**
         * <p>Token lifetime in seconds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("expires_in")
        public _FinalStage expiresIn(int expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        /**
         * <p>Entity the token is bound to, if any</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage boundEntity(Nullable<BoundEntityResponse> boundEntity) {
            if (boundEntity.isNull()) {
                this.boundEntity = null;
            } else if (boundEntity.isEmpty()) {
                this.boundEntity = Optional.empty();
            } else {
                this.boundEntity = Optional.of(boundEntity.get());
            }
            return this;
        }

        /**
         * <p>Entity the token is bound to, if any</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage boundEntity(BoundEntityResponse boundEntity) {
            this.boundEntity = Optional.ofNullable(boundEntity);
            return this;
        }

        /**
         * <p>Entity the token is bound to, if any</p>
         */
        @java.lang.Override
        @JsonSetter(value = "bound_entity", nulls = Nulls.SKIP)
        public _FinalStage boundEntity(Optional<BoundEntityResponse> boundEntity) {
            this.boundEntity = boundEntity;
            return this;
        }

        @java.lang.Override
        public AccessTokenResponse build() {
            return new AccessTokenResponse(accessToken, tokenType, expiresIn, boundEntity, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
