/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AdditionalAccessMethod {
    public static final AdditionalAccessMethod SELF_SETUP = new AdditionalAccessMethod(Value.SELF_SETUP, "SELF_SETUP");

    public static final AdditionalAccessMethod NEEDS_HELP = new AdditionalAccessMethod(Value.NEEDS_HELP, "NEEDS_HELP");

    private final Value value;

    private final String string;

    AdditionalAccessMethod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AdditionalAccessMethod
                        && this.string.equals(((AdditionalAccessMethod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SELF_SETUP:
                return visitor.visitSelfSetup();
            case NEEDS_HELP:
                return visitor.visitNeedsHelp();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AdditionalAccessMethod valueOf(String value) {
        switch (value) {
            case "SELF_SETUP":
                return SELF_SETUP;
            case "NEEDS_HELP":
                return NEEDS_HELP;
            default:
                return new AdditionalAccessMethod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SELF_SETUP,

        NEEDS_HELP,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSelfSetup();

        T visitNeedsHelp();

        T visitUnknown(String unknownType);
    }
}
