/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BenefitSummary.Builder.class)
public final class BenefitSummary {
    private final String id;

    private final String name;

    private final ProductCode productCode;

    private final Category category;

    private final Map<String, Object> additionalProperties;

    private BenefitSummary(
            String id,
            String name,
            ProductCode productCode,
            Category category,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.name = name;
        this.productCode = productCode;
        this.category = category;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Benefit product ID (bprd_*)
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Display name of the benefit product
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Programmatic product identifier
     * <ul>
     * <li><code>EBA</code> - Eba Mec</li>
     * <li><code>VPC</code> - Vpc Enhanced</li>
     * <li><code>VPC_CORE</code> - Vpc Core</li>
     * <li><code>MEC</code> - Vpc Mec</li>
     * <li><code>MEC2</code> - Mec2</li>
     * <li><code>MEC_PLUS</code> - Mec Plus</li>
     * <li><code>MVP</code> - Mvp</li>
     * <li><code>MVP2</code> - Mvp2</li>
     * <li><code>MVPSL</code> - Mvpsl</li>
     * <li><code>MVPSL2</code> - Mvpsl2</li>
     * <li><code>VD</code> - Dental</li>
     * <li><code>VV</code> - Vision</li>
     * <li><code>ICHRA</code> - Ichra</li>
     * <li><code>ICHRA_PREMIUM_PLUS</code> - Ichra Premium Plus</li>
     * <li><code>ICHRA_REIMBURSEMENT_ONLY</code> - Ichra Reimbursement Only</li>
     * </ul>
     */
    @JsonProperty("product_code")
    public ProductCode getProductCode() {
        return productCode;
    }

    /**
     * @return High-level benefit grouping
     * <ul>
     * <li><code>Medical</code> - Medical</li>
     * <li><code>Dental</code> - Dental</li>
     * <li><code>Vision</code> - Vision</li>
     * <li><code>Hospital</code> - Hospital</li>
     * </ul>
     */
    @JsonProperty("category")
    public Category getCategory() {
        return category;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BenefitSummary && equalTo((BenefitSummary) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BenefitSummary other) {
        return id.equals(other.id)
                && name.equals(other.name)
                && productCode.equals(other.productCode)
                && category.equals(other.category);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.name, this.productCode, this.category);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Benefit product ID (bprd_*)</p>
         */
        NameStage id(@NotNull String id);

        Builder from(BenefitSummary other);
    }

    public interface NameStage {
        /**
         * <p>Display name of the benefit product</p>
         */
        ProductCodeStage name(@NotNull String name);
    }

    public interface ProductCodeStage {
        /**
         * <p>Programmatic product identifier</p>
         * <ul>
         * <li><code>EBA</code> - Eba Mec</li>
         * <li><code>VPC</code> - Vpc Enhanced</li>
         * <li><code>VPC_CORE</code> - Vpc Core</li>
         * <li><code>MEC</code> - Vpc Mec</li>
         * <li><code>MEC2</code> - Mec2</li>
         * <li><code>MEC_PLUS</code> - Mec Plus</li>
         * <li><code>MVP</code> - Mvp</li>
         * <li><code>MVP2</code> - Mvp2</li>
         * <li><code>MVPSL</code> - Mvpsl</li>
         * <li><code>MVPSL2</code> - Mvpsl2</li>
         * <li><code>VD</code> - Dental</li>
         * <li><code>VV</code> - Vision</li>
         * <li><code>ICHRA</code> - Ichra</li>
         * <li><code>ICHRA_PREMIUM_PLUS</code> - Ichra Premium Plus</li>
         * <li><code>ICHRA_REIMBURSEMENT_ONLY</code> - Ichra Reimbursement Only</li>
         * </ul>
         */
        CategoryStage productCode(@NotNull ProductCode productCode);
    }

    public interface CategoryStage {
        /**
         * <p>High-level benefit grouping</p>
         * <ul>
         * <li><code>Medical</code> - Medical</li>
         * <li><code>Dental</code> - Dental</li>
         * <li><code>Vision</code> - Vision</li>
         * <li><code>Hospital</code> - Hospital</li>
         * </ul>
         */
        _FinalStage category(@NotNull Category category);
    }

    public interface _FinalStage {
        BenefitSummary build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, NameStage, ProductCodeStage, CategoryStage, _FinalStage {
        private String id;

        private String name;

        private ProductCode productCode;

        private Category category;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BenefitSummary other) {
            id(other.getId());
            name(other.getName());
            productCode(other.getProductCode());
            category(other.getCategory());
            return this;
        }

        /**
         * <p>Benefit product ID (bprd_*)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Display name of the benefit product</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public ProductCodeStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Programmatic product identifier</p>
         * <ul>
         * <li><code>EBA</code> - Eba Mec</li>
         * <li><code>VPC</code> - Vpc Enhanced</li>
         * <li><code>VPC_CORE</code> - Vpc Core</li>
         * <li><code>MEC</code> - Vpc Mec</li>
         * <li><code>MEC2</code> - Mec2</li>
         * <li><code>MEC_PLUS</code> - Mec Plus</li>
         * <li><code>MVP</code> - Mvp</li>
         * <li><code>MVP2</code> - Mvp2</li>
         * <li><code>MVPSL</code> - Mvpsl</li>
         * <li><code>MVPSL2</code> - Mvpsl2</li>
         * <li><code>VD</code> - Dental</li>
         * <li><code>VV</code> - Vision</li>
         * <li><code>ICHRA</code> - Ichra</li>
         * <li><code>ICHRA_PREMIUM_PLUS</code> - Ichra Premium Plus</li>
         * <li><code>ICHRA_REIMBURSEMENT_ONLY</code> - Ichra Reimbursement Only</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("product_code")
        public CategoryStage productCode(@NotNull ProductCode productCode) {
            this.productCode = Objects.requireNonNull(productCode, "productCode must not be null");
            return this;
        }

        /**
         * <p>High-level benefit grouping</p>
         * <ul>
         * <li><code>Medical</code> - Medical</li>
         * <li><code>Dental</code> - Dental</li>
         * <li><code>Vision</code> - Vision</li>
         * <li><code>Hospital</code> - Hospital</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("category")
        public _FinalStage category(@NotNull Category category) {
            this.category = Objects.requireNonNull(category, "category must not be null");
            return this;
        }

        @java.lang.Override
        public BenefitSummary build() {
            return new BenefitSummary(id, name, productCode, category, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
