/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BenefitLifecycleStageItem {
    public static final BenefitLifecycleStageItem ONBOARDING =
            new BenefitLifecycleStageItem(Value.ONBOARDING, "onboarding");

    public static final BenefitLifecycleStageItem OPEN_ENROLLMENT =
            new BenefitLifecycleStageItem(Value.OPEN_ENROLLMENT, "open_enrollment");

    public static final BenefitLifecycleStageItem CANCELLED =
            new BenefitLifecycleStageItem(Value.CANCELLED, "cancelled");

    public static final BenefitLifecycleStageItem RENEWAL = new BenefitLifecycleStageItem(Value.RENEWAL, "renewal");

    public static final BenefitLifecycleStageItem ACTIVE = new BenefitLifecycleStageItem(Value.ACTIVE, "active");

    private final Value value;

    private final String string;

    BenefitLifecycleStageItem(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof BenefitLifecycleStageItem
                        && this.string.equals(((BenefitLifecycleStageItem) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ONBOARDING:
                return visitor.visitOnboarding();
            case OPEN_ENROLLMENT:
                return visitor.visitOpenEnrollment();
            case CANCELLED:
                return visitor.visitCancelled();
            case RENEWAL:
                return visitor.visitRenewal();
            case ACTIVE:
                return visitor.visitActive();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BenefitLifecycleStageItem valueOf(String value) {
        switch (value) {
            case "onboarding":
                return ONBOARDING;
            case "open_enrollment":
                return OPEN_ENROLLMENT;
            case "cancelled":
                return CANCELLED;
            case "renewal":
                return RENEWAL;
            case "active":
                return ACTIVE;
            default:
                return new BenefitLifecycleStageItem(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        OPEN_ENROLLMENT,

        RENEWAL,

        ACTIVE,

        ONBOARDING,

        CANCELLED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOpenEnrollment();

        T visitRenewal();

        T visitActive();

        T visitOnboarding();

        T visitCancelled();

        T visitUnknown(String unknownType);
    }
}
