/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BoundEntityType {
    public static final BoundEntityType EMPLOYEE = new BoundEntityType(Value.EMPLOYEE, "employee");

    public static final BoundEntityType EMPLOYER = new BoundEntityType(Value.EMPLOYER, "employer");

    private final Value value;

    private final String string;

    BoundEntityType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof BoundEntityType && this.string.equals(((BoundEntityType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case EMPLOYEE:
                return visitor.visitEmployee();
            case EMPLOYER:
                return visitor.visitEmployer();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BoundEntityType valueOf(String value) {
        switch (value) {
            case "employee":
                return EMPLOYEE;
            case "employer":
                return EMPLOYER;
            default:
                return new BoundEntityType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        EMPLOYER,

        EMPLOYEE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitEmployer();

        T visitEmployee();

        T visitUnknown(String unknownType);
    }
}
