/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ContributionTier.Builder.class)
public final class ContributionTier {
    private final String benefitPlanId;

    private final String benefitPlanName;

    private final String benefitPlanTierName;

    private final CoverageTier coverageTier;

    private final int cost;

    private final int costPerDependent;

    private final boolean dependentsRequiredIn;

    private final boolean spouseRequiredIn;

    private final Map<String, Object> additionalProperties;

    private ContributionTier(
            String benefitPlanId,
            String benefitPlanName,
            String benefitPlanTierName,
            CoverageTier coverageTier,
            int cost,
            int costPerDependent,
            boolean dependentsRequiredIn,
            boolean spouseRequiredIn,
            Map<String, Object> additionalProperties) {
        this.benefitPlanId = benefitPlanId;
        this.benefitPlanName = benefitPlanName;
        this.benefitPlanTierName = benefitPlanTierName;
        this.coverageTier = coverageTier;
        this.cost = cost;
        this.costPerDependent = costPerDependent;
        this.dependentsRequiredIn = dependentsRequiredIn;
        this.spouseRequiredIn = spouseRequiredIn;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Prefixed benefit-plan identifier (<code>bpln_*</code>).
     */
    @JsonProperty("benefit_plan_id")
    public String getBenefitPlanId() {
        return benefitPlanId;
    }

    /**
     * @return Benefit plan name.
     */
    @JsonProperty("benefit_plan_name")
    public String getBenefitPlanName() {
        return benefitPlanName;
    }

    /**
     * @return Coverage-tier name.
     */
    @JsonProperty("benefit_plan_tier_name")
    public String getBenefitPlanTierName() {
        return benefitPlanTierName;
    }

    /**
     * @return Coverage-tier code for this tier.
     * <ul>
     * <li><code>Unspecified</code> - Unspecified</li>
     * <li><code>EE</code> - Ee</li>
     * <li><code>ES</code> - Es</li>
     * <li><code>EC</code> - Ec</li>
     * <li><code>EF</code> - Ef</li>
     * </ul>
     */
    @JsonProperty("coverage_tier")
    public CoverageTier getCoverageTier() {
        return coverageTier;
    }

    /**
     * @return Monthly employee deduction in cents.
     */
    @JsonProperty("cost")
    public int getCost() {
        return cost;
    }

    /**
     * @return Monthly employee deduction per dependent, in cents.
     */
    @JsonProperty("cost_per_dependent")
    public int getCostPerDependent() {
        return costPerDependent;
    }

    /**
     * @return Whether dependents are required for this tier.
     */
    @JsonProperty("dependents_required_in")
    public boolean getDependentsRequiredIn() {
        return dependentsRequiredIn;
    }

    /**
     * @return Whether a spouse is required for this tier.
     */
    @JsonProperty("spouse_required_in")
    public boolean getSpouseRequiredIn() {
        return spouseRequiredIn;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ContributionTier && equalTo((ContributionTier) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ContributionTier other) {
        return benefitPlanId.equals(other.benefitPlanId)
                && benefitPlanName.equals(other.benefitPlanName)
                && benefitPlanTierName.equals(other.benefitPlanTierName)
                && coverageTier.equals(other.coverageTier)
                && cost == other.cost
                && costPerDependent == other.costPerDependent
                && dependentsRequiredIn == other.dependentsRequiredIn
                && spouseRequiredIn == other.spouseRequiredIn;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.benefitPlanId,
                this.benefitPlanName,
                this.benefitPlanTierName,
                this.coverageTier,
                this.cost,
                this.costPerDependent,
                this.dependentsRequiredIn,
                this.spouseRequiredIn);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static BenefitPlanIdStage builder() {
        return new Builder();
    }

    public interface BenefitPlanIdStage {
        /**
         * <p>Prefixed benefit-plan identifier (<code>bpln_*</code>).</p>
         */
        BenefitPlanNameStage benefitPlanId(@NotNull String benefitPlanId);

        Builder from(ContributionTier other);
    }

    public interface BenefitPlanNameStage {
        /**
         * <p>Benefit plan name.</p>
         */
        BenefitPlanTierNameStage benefitPlanName(@NotNull String benefitPlanName);
    }

    public interface BenefitPlanTierNameStage {
        /**
         * <p>Coverage-tier name.</p>
         */
        CoverageTierStage benefitPlanTierName(@NotNull String benefitPlanTierName);
    }

    public interface CoverageTierStage {
        /**
         * <p>Coverage-tier code for this tier.</p>
         * <ul>
         * <li><code>Unspecified</code> - Unspecified</li>
         * <li><code>EE</code> - Ee</li>
         * <li><code>ES</code> - Es</li>
         * <li><code>EC</code> - Ec</li>
         * <li><code>EF</code> - Ef</li>
         * </ul>
         */
        CostStage coverageTier(@NotNull CoverageTier coverageTier);
    }

    public interface CostStage {
        /**
         * <p>Monthly employee deduction in cents.</p>
         */
        CostPerDependentStage cost(int cost);
    }

    public interface CostPerDependentStage {
        /**
         * <p>Monthly employee deduction per dependent, in cents.</p>
         */
        DependentsRequiredInStage costPerDependent(int costPerDependent);
    }

    public interface DependentsRequiredInStage {
        /**
         * <p>Whether dependents are required for this tier.</p>
         */
        SpouseRequiredInStage dependentsRequiredIn(boolean dependentsRequiredIn);
    }

    public interface SpouseRequiredInStage {
        /**
         * <p>Whether a spouse is required for this tier.</p>
         */
        _FinalStage spouseRequiredIn(boolean spouseRequiredIn);
    }

    public interface _FinalStage {
        ContributionTier build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements BenefitPlanIdStage,
                    BenefitPlanNameStage,
                    BenefitPlanTierNameStage,
                    CoverageTierStage,
                    CostStage,
                    CostPerDependentStage,
                    DependentsRequiredInStage,
                    SpouseRequiredInStage,
                    _FinalStage {
        private String benefitPlanId;

        private String benefitPlanName;

        private String benefitPlanTierName;

        private CoverageTier coverageTier;

        private int cost;

        private int costPerDependent;

        private boolean dependentsRequiredIn;

        private boolean spouseRequiredIn;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ContributionTier other) {
            benefitPlanId(other.getBenefitPlanId());
            benefitPlanName(other.getBenefitPlanName());
            benefitPlanTierName(other.getBenefitPlanTierName());
            coverageTier(other.getCoverageTier());
            cost(other.getCost());
            costPerDependent(other.getCostPerDependent());
            dependentsRequiredIn(other.getDependentsRequiredIn());
            spouseRequiredIn(other.getSpouseRequiredIn());
            return this;
        }

        /**
         * <p>Prefixed benefit-plan identifier (<code>bpln_*</code>).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("benefit_plan_id")
        public BenefitPlanNameStage benefitPlanId(@NotNull String benefitPlanId) {
            this.benefitPlanId = Objects.requireNonNull(benefitPlanId, "benefitPlanId must not be null");
            return this;
        }

        /**
         * <p>Benefit plan name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("benefit_plan_name")
        public BenefitPlanTierNameStage benefitPlanName(@NotNull String benefitPlanName) {
            this.benefitPlanName = Objects.requireNonNull(benefitPlanName, "benefitPlanName must not be null");
            return this;
        }

        /**
         * <p>Coverage-tier name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("benefit_plan_tier_name")
        public CoverageTierStage benefitPlanTierName(@NotNull String benefitPlanTierName) {
            this.benefitPlanTierName =
                    Objects.requireNonNull(benefitPlanTierName, "benefitPlanTierName must not be null");
            return this;
        }

        /**
         * <p>Coverage-tier code for this tier.</p>
         * <ul>
         * <li><code>Unspecified</code> - Unspecified</li>
         * <li><code>EE</code> - Ee</li>
         * <li><code>ES</code> - Es</li>
         * <li><code>EC</code> - Ec</li>
         * <li><code>EF</code> - Ef</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("coverage_tier")
        public CostStage coverageTier(@NotNull CoverageTier coverageTier) {
            this.coverageTier = Objects.requireNonNull(coverageTier, "coverageTier must not be null");
            return this;
        }

        /**
         * <p>Monthly employee deduction in cents.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("cost")
        public CostPerDependentStage cost(int cost) {
            this.cost = cost;
            return this;
        }

        /**
         * <p>Monthly employee deduction per dependent, in cents.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("cost_per_dependent")
        public DependentsRequiredInStage costPerDependent(int costPerDependent) {
            this.costPerDependent = costPerDependent;
            return this;
        }

        /**
         * <p>Whether dependents are required for this tier.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("dependents_required_in")
        public SpouseRequiredInStage dependentsRequiredIn(boolean dependentsRequiredIn) {
            this.dependentsRequiredIn = dependentsRequiredIn;
            return this;
        }

        /**
         * <p>Whether a spouse is required for this tier.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("spouse_required_in")
        public _FinalStage spouseRequiredIn(boolean spouseRequiredIn) {
            this.spouseRequiredIn = spouseRequiredIn;
            return this;
        }

        @java.lang.Override
        public ContributionTier build() {
            return new ContributionTier(
                    benefitPlanId,
                    benefitPlanName,
                    benefitPlanTierName,
                    coverageTier,
                    cost,
                    costPerDependent,
                    dependentsRequiredIn,
                    spouseRequiredIn,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
