/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ContributionClassCompensation {
    public static final ContributionClassCompensation SALARY =
            new ContributionClassCompensation(Value.SALARY, "Salary");

    public static final ContributionClassCompensation UNSPECIFIED =
            new ContributionClassCompensation(Value.UNSPECIFIED, "Unspecified");

    public static final ContributionClassCompensation HOURLY =
            new ContributionClassCompensation(Value.HOURLY, "Hourly");

    private final Value value;

    private final String string;

    ContributionClassCompensation(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ContributionClassCompensation
                        && this.string.equals(((ContributionClassCompensation) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SALARY:
                return visitor.visitSalary();
            case UNSPECIFIED:
                return visitor.visitUnspecified();
            case HOURLY:
                return visitor.visitHourly();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ContributionClassCompensation valueOf(String value) {
        switch (value) {
            case "Salary":
                return SALARY;
            case "Unspecified":
                return UNSPECIFIED;
            case "Hourly":
                return HOURLY;
            default:
                return new ContributionClassCompensation(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        UNSPECIFIED,

        SALARY,

        HOURLY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUnspecified();

        T visitSalary();

        T visitHourly();

        T visitUnknown(String unknownType);
    }
}
