/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ContributionStrategy.Builder.class)
public final class ContributionStrategy {
    private final List<IchraContributionClass> ichraContributionClasses;

    private final List<ContributionTier> contributionTiers;

    private final Map<String, Object> additionalProperties;

    private ContributionStrategy(
            List<IchraContributionClass> ichraContributionClasses,
            List<ContributionTier> contributionTiers,
            Map<String, Object> additionalProperties) {
        this.ichraContributionClasses = ichraContributionClasses;
        this.contributionTiers = contributionTiers;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ICHRA contribution classes; empty for tier-priced benefits.
     */
    @JsonProperty("ichra_contribution_classes")
    public List<IchraContributionClass> getIchraContributionClasses() {
        return ichraContributionClasses;
    }

    /**
     * @return Coverage tiers and their costs; empty for ICHRA benefits.
     */
    @JsonProperty("contribution_tiers")
    public List<ContributionTier> getContributionTiers() {
        return contributionTiers;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ContributionStrategy && equalTo((ContributionStrategy) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ContributionStrategy other) {
        return ichraContributionClasses.equals(other.ichraContributionClasses)
                && contributionTiers.equals(other.contributionTiers);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.ichraContributionClasses, this.contributionTiers);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<IchraContributionClass> ichraContributionClasses = new ArrayList<>();

        private List<ContributionTier> contributionTiers = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ContributionStrategy other) {
            ichraContributionClasses(other.getIchraContributionClasses());
            contributionTiers(other.getContributionTiers());
            return this;
        }

        /**
         * <p>ICHRA contribution classes; empty for tier-priced benefits.</p>
         */
        @JsonSetter(value = "ichra_contribution_classes", nulls = Nulls.SKIP)
        public Builder ichraContributionClasses(List<IchraContributionClass> ichraContributionClasses) {
            this.ichraContributionClasses.clear();
            if (ichraContributionClasses != null) {
                this.ichraContributionClasses.addAll(ichraContributionClasses);
            }
            return this;
        }

        public Builder addIchraContributionClasses(IchraContributionClass ichraContributionClasses) {
            this.ichraContributionClasses.add(ichraContributionClasses);
            return this;
        }

        public Builder addAllIchraContributionClasses(List<IchraContributionClass> ichraContributionClasses) {
            if (ichraContributionClasses != null) {
                this.ichraContributionClasses.addAll(ichraContributionClasses);
            }
            return this;
        }

        /**
         * <p>Coverage tiers and their costs; empty for ICHRA benefits.</p>
         */
        @JsonSetter(value = "contribution_tiers", nulls = Nulls.SKIP)
        public Builder contributionTiers(List<ContributionTier> contributionTiers) {
            this.contributionTiers.clear();
            if (contributionTiers != null) {
                this.contributionTiers.addAll(contributionTiers);
            }
            return this;
        }

        public Builder addContributionTiers(ContributionTier contributionTiers) {
            this.contributionTiers.add(contributionTiers);
            return this;
        }

        public Builder addAllContributionTiers(List<ContributionTier> contributionTiers) {
            if (contributionTiers != null) {
                this.contributionTiers.addAll(contributionTiers);
            }
            return this;
        }

        public ContributionStrategy build() {
            return new ContributionStrategy(ichraContributionClasses, contributionTiers, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
