/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EligibleGeographicalLocation.Builder.class)
public final class EligibleGeographicalLocation {
    private final EligibleGeographicalLocationType type;

    private final List<String> stateCodes;

    private final Map<String, Object> additionalProperties;

    private EligibleGeographicalLocation(
            EligibleGeographicalLocationType type, List<String> stateCodes, Map<String, Object> additionalProperties) {
        this.type = type;
        this.stateCodes = stateCodes;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return <code>All</code> (unrestricted) or <code>StateCodes</code> (restricted to <code>state_codes</code>).
     * <ul>
     * <li><code>All</code> - All</li>
     * <li><code>StateCodes</code> - State Codes</li>
     * </ul>
     */
    @JsonProperty("type")
    public EligibleGeographicalLocationType getType() {
        return type;
    }

    /**
     * @return States the rule is restricted to; empty when <code>type</code> is <code>All</code>.
     */
    @JsonProperty("state_codes")
    public List<String> getStateCodes() {
        return stateCodes;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EligibleGeographicalLocation && equalTo((EligibleGeographicalLocation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EligibleGeographicalLocation other) {
        return type.equals(other.type) && stateCodes.equals(other.stateCodes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.stateCodes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p><code>All</code> (unrestricted) or <code>StateCodes</code> (restricted to <code>state_codes</code>).</p>
         * <ul>
         * <li><code>All</code> - All</li>
         * <li><code>StateCodes</code> - State Codes</li>
         * </ul>
         */
        _FinalStage type(@NotNull EligibleGeographicalLocationType type);

        Builder from(EligibleGeographicalLocation other);
    }

    public interface _FinalStage {
        EligibleGeographicalLocation build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>States the rule is restricted to; empty when <code>type</code> is <code>All</code>.</p>
         */
        _FinalStage stateCodes(List<String> stateCodes);

        _FinalStage addStateCodes(String stateCodes);

        _FinalStage addAllStateCodes(List<String> stateCodes);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, _FinalStage {
        private EligibleGeographicalLocationType type;

        private List<String> stateCodes = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EligibleGeographicalLocation other) {
            type(other.getType());
            stateCodes(other.getStateCodes());
            return this;
        }

        /**
         * <p><code>All</code> (unrestricted) or <code>StateCodes</code> (restricted to <code>state_codes</code>).</p>
         * <ul>
         * <li><code>All</code> - All</li>
         * <li><code>StateCodes</code> - State Codes</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull EligibleGeographicalLocationType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>States the rule is restricted to; empty when <code>type</code> is <code>All</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllStateCodes(List<String> stateCodes) {
            if (stateCodes != null) {
                this.stateCodes.addAll(stateCodes);
            }
            return this;
        }

        /**
         * <p>States the rule is restricted to; empty when <code>type</code> is <code>All</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addStateCodes(String stateCodes) {
            this.stateCodes.add(stateCodes);
            return this;
        }

        /**
         * <p>States the rule is restricted to; empty when <code>type</code> is <code>All</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "state_codes", nulls = Nulls.SKIP)
        public _FinalStage stateCodes(List<String> stateCodes) {
            this.stateCodes.clear();
            if (stateCodes != null) {
                this.stateCodes.addAll(stateCodes);
            }
            return this;
        }

        @java.lang.Override
        public EligibleGeographicalLocation build() {
            return new EligibleGeographicalLocation(type, stateCodes, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
