/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EligibilityRuleEmployeeClass {
    public static final EligibilityRuleEmployeeClass PART_TIME =
            new EligibilityRuleEmployeeClass(Value.PART_TIME, "Part Time");

    public static final EligibilityRuleEmployeeClass INDIVIDUAL_CONTRACTOR =
            new EligibilityRuleEmployeeClass(Value.INDIVIDUAL_CONTRACTOR, "Individual Contractor");

    public static final EligibilityRuleEmployeeClass TEMPORARY =
            new EligibilityRuleEmployeeClass(Value.TEMPORARY, "Temporary");

    public static final EligibilityRuleEmployeeClass ALL = new EligibilityRuleEmployeeClass(Value.ALL, "All");

    public static final EligibilityRuleEmployeeClass INTERN = new EligibilityRuleEmployeeClass(Value.INTERN, "Intern");

    public static final EligibilityRuleEmployeeClass FULL_TIME =
            new EligibilityRuleEmployeeClass(Value.FULL_TIME, "Full Time");

    public static final EligibilityRuleEmployeeClass SEASONAL =
            new EligibilityRuleEmployeeClass(Value.SEASONAL, "Seasonal");

    private final Value value;

    private final String string;

    EligibilityRuleEmployeeClass(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof EligibilityRuleEmployeeClass
                        && this.string.equals(((EligibilityRuleEmployeeClass) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PART_TIME:
                return visitor.visitPartTime();
            case INDIVIDUAL_CONTRACTOR:
                return visitor.visitIndividualContractor();
            case TEMPORARY:
                return visitor.visitTemporary();
            case ALL:
                return visitor.visitAll();
            case INTERN:
                return visitor.visitIntern();
            case FULL_TIME:
                return visitor.visitFullTime();
            case SEASONAL:
                return visitor.visitSeasonal();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EligibilityRuleEmployeeClass valueOf(String value) {
        switch (value) {
            case "Part Time":
                return PART_TIME;
            case "Individual Contractor":
                return INDIVIDUAL_CONTRACTOR;
            case "Temporary":
                return TEMPORARY;
            case "All":
                return ALL;
            case "Intern":
                return INTERN;
            case "Full Time":
                return FULL_TIME;
            case "Seasonal":
                return SEASONAL;
            default:
                return new EligibilityRuleEmployeeClass(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        FULL_TIME,

        PART_TIME,

        TEMPORARY,

        INTERN,

        SEASONAL,

        INDIVIDUAL_CONTRACTOR,

        ALL,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitFullTime();

        T visitPartTime();

        T visitTemporary();

        T visitIntern();

        T visitSeasonal();

        T visitIndividualContractor();

        T visitAll();

        T visitUnknown(String unknownType);
    }
}
