/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EligibilityPolicyRule.Builder.class)
public final class EligibilityPolicyRule {
    private final EligibilityRuleEmployeeClass employeeClass;

    private final EligibilityRuleCompensationType compensationType;

    private final EligibleGeographicalLocation eligibleGeographicalLocation;

    private final Map<String, Object> additionalProperties;

    private EligibilityPolicyRule(
            EligibilityRuleEmployeeClass employeeClass,
            EligibilityRuleCompensationType compensationType,
            EligibleGeographicalLocation eligibleGeographicalLocation,
            Map<String, Object> additionalProperties) {
        this.employeeClass = employeeClass;
        this.compensationType = compensationType;
        this.eligibleGeographicalLocation = eligibleGeographicalLocation;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Employee-class matcher (<code>All</code> for any).
     * <ul>
     * <li><code>Full Time</code> - Full Time</li>
     * <li><code>Part Time</code> - Part Time</li>
     * <li><code>Temporary</code> - Temporary</li>
     * <li><code>Intern</code> - Intern</li>
     * <li><code>Seasonal</code> - Seasonal</li>
     * <li><code>Individual Contractor</code> - Individual Contractor</li>
     * <li><code>All</code> - All</li>
     * </ul>
     */
    @JsonProperty("employee_class")
    public EligibilityRuleEmployeeClass getEmployeeClass() {
        return employeeClass;
    }

    /**
     * @return Compensation matcher (<code>All</code> for any).
     * <ul>
     * <li><code>Salary</code> - Salary</li>
     * <li><code>Hourly</code> - Hourly</li>
     * <li><code>All</code> - All</li>
     * </ul>
     */
    @JsonProperty("compensation_type")
    public EligibilityRuleCompensationType getCompensationType() {
        return compensationType;
    }

    /**
     * @return Geographic matcher.
     */
    @JsonProperty("eligible_geographical_location")
    public EligibleGeographicalLocation getEligibleGeographicalLocation() {
        return eligibleGeographicalLocation;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EligibilityPolicyRule && equalTo((EligibilityPolicyRule) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EligibilityPolicyRule other) {
        return employeeClass.equals(other.employeeClass)
                && compensationType.equals(other.compensationType)
                && eligibleGeographicalLocation.equals(other.eligibleGeographicalLocation);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.employeeClass, this.compensationType, this.eligibleGeographicalLocation);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EmployeeClassStage builder() {
        return new Builder();
    }

    public interface EmployeeClassStage {
        /**
         * <p>Employee-class matcher (<code>All</code> for any).</p>
         * <ul>
         * <li><code>Full Time</code> - Full Time</li>
         * <li><code>Part Time</code> - Part Time</li>
         * <li><code>Temporary</code> - Temporary</li>
         * <li><code>Intern</code> - Intern</li>
         * <li><code>Seasonal</code> - Seasonal</li>
         * <li><code>Individual Contractor</code> - Individual Contractor</li>
         * <li><code>All</code> - All</li>
         * </ul>
         */
        CompensationTypeStage employeeClass(@NotNull EligibilityRuleEmployeeClass employeeClass);

        Builder from(EligibilityPolicyRule other);
    }

    public interface CompensationTypeStage {
        /**
         * <p>Compensation matcher (<code>All</code> for any).</p>
         * <ul>
         * <li><code>Salary</code> - Salary</li>
         * <li><code>Hourly</code> - Hourly</li>
         * <li><code>All</code> - All</li>
         * </ul>
         */
        EligibleGeographicalLocationStage compensationType(@NotNull EligibilityRuleCompensationType compensationType);
    }

    public interface EligibleGeographicalLocationStage {
        /**
         * <p>Geographic matcher.</p>
         */
        _FinalStage eligibleGeographicalLocation(@NotNull EligibleGeographicalLocation eligibleGeographicalLocation);
    }

    public interface _FinalStage {
        EligibilityPolicyRule build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements EmployeeClassStage, CompensationTypeStage, EligibleGeographicalLocationStage, _FinalStage {
        private EligibilityRuleEmployeeClass employeeClass;

        private EligibilityRuleCompensationType compensationType;

        private EligibleGeographicalLocation eligibleGeographicalLocation;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EligibilityPolicyRule other) {
            employeeClass(other.getEmployeeClass());
            compensationType(other.getCompensationType());
            eligibleGeographicalLocation(other.getEligibleGeographicalLocation());
            return this;
        }

        /**
         * <p>Employee-class matcher (<code>All</code> for any).</p>
         * <ul>
         * <li><code>Full Time</code> - Full Time</li>
         * <li><code>Part Time</code> - Part Time</li>
         * <li><code>Temporary</code> - Temporary</li>
         * <li><code>Intern</code> - Intern</li>
         * <li><code>Seasonal</code> - Seasonal</li>
         * <li><code>Individual Contractor</code> - Individual Contractor</li>
         * <li><code>All</code> - All</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("employee_class")
        public CompensationTypeStage employeeClass(@NotNull EligibilityRuleEmployeeClass employeeClass) {
            this.employeeClass = Objects.requireNonNull(employeeClass, "employeeClass must not be null");
            return this;
        }

        /**
         * <p>Compensation matcher (<code>All</code> for any).</p>
         * <ul>
         * <li><code>Salary</code> - Salary</li>
         * <li><code>Hourly</code> - Hourly</li>
         * <li><code>All</code> - All</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("compensation_type")
        public EligibleGeographicalLocationStage compensationType(
                @NotNull EligibilityRuleCompensationType compensationType) {
            this.compensationType = Objects.requireNonNull(compensationType, "compensationType must not be null");
            return this;
        }

        /**
         * <p>Geographic matcher.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("eligible_geographical_location")
        public _FinalStage eligibleGeographicalLocation(
                @NotNull EligibleGeographicalLocation eligibleGeographicalLocation) {
            this.eligibleGeographicalLocation = Objects.requireNonNull(
                    eligibleGeographicalLocation, "eligibleGeographicalLocation must not be null");
            return this;
        }

        @java.lang.Override
        public EligibilityPolicyRule build() {
            return new EligibilityPolicyRule(
                    employeeClass, compensationType, eligibleGeographicalLocation, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
