/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Employer.Builder.class)
public final class Employer {
    private final Optional<String> id;

    private final Optional<String> organizationId;

    private final String name;

    private final String legalName;

    private final Optional<String> ein;

    private final Optional<String> referenceId;

    private final Optional<String> email;

    private final Optional<String> phoneNumber;

    private final boolean active;

    private final EmployerAddress address;

    private final Optional<EmployerContact> contact;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final Map<String, Object> additionalProperties;

    private Employer(
            Optional<String> id,
            Optional<String> organizationId,
            String name,
            String legalName,
            Optional<String> ein,
            Optional<String> referenceId,
            Optional<String> email,
            Optional<String> phoneNumber,
            boolean active,
            EmployerAddress address,
            Optional<EmployerContact> contact,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.organizationId = organizationId;
        this.name = name;
        this.legalName = legalName;
        this.ein = ein;
        this.referenceId = referenceId;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.active = active;
        this.address = address;
        this.contact = contact;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique employer identifier with 'empr_' prefix
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return ID of the parent organization (org_*)
     */
    @JsonIgnore
    public Optional<String> getOrganizationId() {
        if (organizationId == null) {
            return Optional.empty();
        }
        return organizationId;
    }

    /**
     * @return Display name of the employer
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Legal business name for compliance and tax purposes
     */
    @JsonProperty("legal_name")
    public String getLegalName() {
        return legalName;
    }

    /**
     * @return Employer Identification Number (format: XX-XXXXXXX)
     */
    @JsonIgnore
    public Optional<String> getEin() {
        if (ein == null) {
            return Optional.empty();
        }
        return ein;
    }

    /**
     * @return Partner-assigned reference ID for the employer
     */
    @JsonIgnore
    public Optional<String> getReferenceId() {
        if (referenceId == null) {
            return Optional.empty();
        }
        return referenceId;
    }

    /**
     * @return Email address for billing and communications
     */
    @JsonIgnore
    public Optional<String> getEmail() {
        if (email == null) {
            return Optional.empty();
        }
        return email;
    }

    /**
     * @return Employer phone number (E.164 format recommended)
     */
    @JsonIgnore
    public Optional<String> getPhoneNumber() {
        if (phoneNumber == null) {
            return Optional.empty();
        }
        return phoneNumber;
    }

    /**
     * @return Whether the employer is currently active in the system
     */
    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    /**
     * @return Employer's primary address
     */
    @JsonProperty("address")
    public EmployerAddress getAddress() {
        return address;
    }

    /**
     * @return Primary company-admin contact, or null
     */
    @JsonIgnore
    public Optional<EmployerContact> getContact() {
        if (contact == null) {
            return Optional.empty();
        }
        return contact;
    }

    /**
     * @return Timestamp when the employer was created
     */
    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Timestamp when the employer was last updated
     */
    @JsonProperty("updated_at")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("organization_id")
    private Optional<String> _getOrganizationId() {
        return organizationId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("ein")
    private Optional<String> _getEin() {
        return ein;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("reference_id")
    private Optional<String> _getReferenceId() {
        return referenceId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("email")
    private Optional<String> _getEmail() {
        return email;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("phone_number")
    private Optional<String> _getPhoneNumber() {
        return phoneNumber;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("contact")
    private Optional<EmployerContact> _getContact() {
        return contact;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Employer && equalTo((Employer) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Employer other) {
        return id.equals(other.id)
                && organizationId.equals(other.organizationId)
                && name.equals(other.name)
                && legalName.equals(other.legalName)
                && ein.equals(other.ein)
                && referenceId.equals(other.referenceId)
                && email.equals(other.email)
                && phoneNumber.equals(other.phoneNumber)
                && active == other.active
                && address.equals(other.address)
                && contact.equals(other.contact)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.organizationId,
                this.name,
                this.legalName,
                this.ein,
                this.referenceId,
                this.email,
                this.phoneNumber,
                this.active,
                this.address,
                this.contact,
                this.createdAt,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Display name of the employer</p>
         */
        LegalNameStage name(@NotNull String name);

        Builder from(Employer other);
    }

    public interface LegalNameStage {
        /**
         * <p>Legal business name for compliance and tax purposes</p>
         */
        ActiveStage legalName(@NotNull String legalName);
    }

    public interface ActiveStage {
        /**
         * <p>Whether the employer is currently active in the system</p>
         */
        AddressStage active(boolean active);
    }

    public interface AddressStage {
        /**
         * <p>Employer's primary address</p>
         */
        CreatedAtStage address(@NotNull EmployerAddress address);
    }

    public interface CreatedAtStage {
        /**
         * <p>Timestamp when the employer was created</p>
         */
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        /**
         * <p>Timestamp when the employer was last updated</p>
         */
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        Employer build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Unique employer identifier with 'empr_' prefix</p>
         */
        _FinalStage id(Optional<String> id);

        _FinalStage id(String id);

        /**
         * <p>ID of the parent organization (org_*)</p>
         */
        _FinalStage organizationId(Optional<String> organizationId);

        _FinalStage organizationId(String organizationId);

        _FinalStage organizationId(Nullable<String> organizationId);

        /**
         * <p>Employer Identification Number (format: XX-XXXXXXX)</p>
         */
        _FinalStage ein(Optional<String> ein);

        _FinalStage ein(String ein);

        _FinalStage ein(Nullable<String> ein);

        /**
         * <p>Partner-assigned reference ID for the employer</p>
         */
        _FinalStage referenceId(Optional<String> referenceId);

        _FinalStage referenceId(String referenceId);

        _FinalStage referenceId(Nullable<String> referenceId);

        /**
         * <p>Email address for billing and communications</p>
         */
        _FinalStage email(Optional<String> email);

        _FinalStage email(String email);

        _FinalStage email(Nullable<String> email);

        /**
         * <p>Employer phone number (E.164 format recommended)</p>
         */
        _FinalStage phoneNumber(Optional<String> phoneNumber);

        _FinalStage phoneNumber(String phoneNumber);

        _FinalStage phoneNumber(Nullable<String> phoneNumber);

        /**
         * <p>Primary company-admin contact, or null</p>
         */
        _FinalStage contact(Optional<EmployerContact> contact);

        _FinalStage contact(EmployerContact contact);

        _FinalStage contact(Nullable<EmployerContact> contact);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements NameStage,
                    LegalNameStage,
                    ActiveStage,
                    AddressStage,
                    CreatedAtStage,
                    UpdatedAtStage,
                    _FinalStage {
        private String name;

        private String legalName;

        private boolean active;

        private EmployerAddress address;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private Optional<EmployerContact> contact = Optional.empty();

        private Optional<String> phoneNumber = Optional.empty();

        private Optional<String> email = Optional.empty();

        private Optional<String> referenceId = Optional.empty();

        private Optional<String> ein = Optional.empty();

        private Optional<String> organizationId = Optional.empty();

        private Optional<String> id = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Employer other) {
            id(other.getId());
            organizationId(other.getOrganizationId());
            name(other.getName());
            legalName(other.getLegalName());
            ein(other.getEin());
            referenceId(other.getReferenceId());
            email(other.getEmail());
            phoneNumber(other.getPhoneNumber());
            active(other.getActive());
            address(other.getAddress());
            contact(other.getContact());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>Display name of the employer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public LegalNameStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Legal business name for compliance and tax purposes</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("legal_name")
        public ActiveStage legalName(@NotNull String legalName) {
            this.legalName = Objects.requireNonNull(legalName, "legalName must not be null");
            return this;
        }

        /**
         * <p>Whether the employer is currently active in the system</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("active")
        public AddressStage active(boolean active) {
            this.active = active;
            return this;
        }

        /**
         * <p>Employer's primary address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("address")
        public CreatedAtStage address(@NotNull EmployerAddress address) {
            this.address = Objects.requireNonNull(address, "address must not be null");
            return this;
        }

        /**
         * <p>Timestamp when the employer was created</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Timestamp when the employer was last updated</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>Primary company-admin contact, or null</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage contact(Nullable<EmployerContact> contact) {
            if (contact.isNull()) {
                this.contact = null;
            } else if (contact.isEmpty()) {
                this.contact = Optional.empty();
            } else {
                this.contact = Optional.of(contact.get());
            }
            return this;
        }

        /**
         * <p>Primary company-admin contact, or null</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage contact(EmployerContact contact) {
            this.contact = Optional.ofNullable(contact);
            return this;
        }

        /**
         * <p>Primary company-admin contact, or null</p>
         */
        @java.lang.Override
        @JsonSetter(value = "contact", nulls = Nulls.SKIP)
        public _FinalStage contact(Optional<EmployerContact> contact) {
            this.contact = contact;
            return this;
        }

        /**
         * <p>Employer phone number (E.164 format recommended)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phoneNumber(Nullable<String> phoneNumber) {
            if (phoneNumber.isNull()) {
                this.phoneNumber = null;
            } else if (phoneNumber.isEmpty()) {
                this.phoneNumber = Optional.empty();
            } else {
                this.phoneNumber = Optional.of(phoneNumber.get());
            }
            return this;
        }

        /**
         * <p>Employer phone number (E.164 format recommended)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phoneNumber(String phoneNumber) {
            this.phoneNumber = Optional.ofNullable(phoneNumber);
            return this;
        }

        /**
         * <p>Employer phone number (E.164 format recommended)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "phone_number", nulls = Nulls.SKIP)
        public _FinalStage phoneNumber(Optional<String> phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * <p>Email address for billing and communications</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(Nullable<String> email) {
            if (email.isNull()) {
                this.email = null;
            } else if (email.isEmpty()) {
                this.email = Optional.empty();
            } else {
                this.email = Optional.of(email.get());
            }
            return this;
        }

        /**
         * <p>Email address for billing and communications</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>Email address for billing and communications</p>
         */
        @java.lang.Override
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public _FinalStage email(Optional<String> email) {
            this.email = email;
            return this;
        }

        /**
         * <p>Partner-assigned reference ID for the employer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage referenceId(Nullable<String> referenceId) {
            if (referenceId.isNull()) {
                this.referenceId = null;
            } else if (referenceId.isEmpty()) {
                this.referenceId = Optional.empty();
            } else {
                this.referenceId = Optional.of(referenceId.get());
            }
            return this;
        }

        /**
         * <p>Partner-assigned reference ID for the employer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage referenceId(String referenceId) {
            this.referenceId = Optional.ofNullable(referenceId);
            return this;
        }

        /**
         * <p>Partner-assigned reference ID for the employer</p>
         */
        @java.lang.Override
        @JsonSetter(value = "reference_id", nulls = Nulls.SKIP)
        public _FinalStage referenceId(Optional<String> referenceId) {
            this.referenceId = referenceId;
            return this;
        }

        /**
         * <p>Employer Identification Number (format: XX-XXXXXXX)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage ein(Nullable<String> ein) {
            if (ein.isNull()) {
                this.ein = null;
            } else if (ein.isEmpty()) {
                this.ein = Optional.empty();
            } else {
                this.ein = Optional.of(ein.get());
            }
            return this;
        }

        /**
         * <p>Employer Identification Number (format: XX-XXXXXXX)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage ein(String ein) {
            this.ein = Optional.ofNullable(ein);
            return this;
        }

        /**
         * <p>Employer Identification Number (format: XX-XXXXXXX)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "ein", nulls = Nulls.SKIP)
        public _FinalStage ein(Optional<String> ein) {
            this.ein = ein;
            return this;
        }

        /**
         * <p>ID of the parent organization (org_*)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage organizationId(Nullable<String> organizationId) {
            if (organizationId.isNull()) {
                this.organizationId = null;
            } else if (organizationId.isEmpty()) {
                this.organizationId = Optional.empty();
            } else {
                this.organizationId = Optional.of(organizationId.get());
            }
            return this;
        }

        /**
         * <p>ID of the parent organization (org_*)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage organizationId(String organizationId) {
            this.organizationId = Optional.ofNullable(organizationId);
            return this;
        }

        /**
         * <p>ID of the parent organization (org_*)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "organization_id", nulls = Nulls.SKIP)
        public _FinalStage organizationId(Optional<String> organizationId) {
            this.organizationId = organizationId;
            return this;
        }

        /**
         * <p>Unique employer identifier with 'empr_' prefix</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>Unique employer identifier with 'empr_' prefix</p>
         */
        @java.lang.Override
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public _FinalStage id(Optional<String> id) {
            this.id = id;
            return this;
        }

        @java.lang.Override
        public Employer build() {
            return new Employer(
                    id,
                    organizationId,
                    name,
                    legalName,
                    ein,
                    referenceId,
                    email,
                    phoneNumber,
                    active,
                    address,
                    contact,
                    createdAt,
                    updatedAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
