/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Employee.Builder.class)
public final class Employee {
    private final Optional<String> id;

    private final Optional<String> memberId;

    private final Optional<String> employerId;

    private final Optional<String> referenceId;

    private final Optional<String> employerName;

    private final String firstName;

    private final String lastName;

    private final Optional<String> suffix;

    private final String email;

    private final String dateOfBirth;

    private final Optional<String> gender;

    private final Optional<String> phone;

    private final EmployeeClass employeeClass;

    private final Optional<EmployeeStatus> status;

    private final Optional<String> startDate;

    private final Optional<String> classificationEffectiveDate;

    private final Optional<CompensationType> compensationType;

    private final Optional<String> compensationTypeEffectiveDate;

    private final Optional<String> terminationDate;

    private final Optional<EmployeeAddress> address;

    private final List<DeductionDetail> deductions;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final Map<String, Object> additionalProperties;

    private Employee(
            Optional<String> id,
            Optional<String> memberId,
            Optional<String> employerId,
            Optional<String> referenceId,
            Optional<String> employerName,
            String firstName,
            String lastName,
            Optional<String> suffix,
            String email,
            String dateOfBirth,
            Optional<String> gender,
            Optional<String> phone,
            EmployeeClass employeeClass,
            Optional<EmployeeStatus> status,
            Optional<String> startDate,
            Optional<String> classificationEffectiveDate,
            Optional<CompensationType> compensationType,
            Optional<String> compensationTypeEffectiveDate,
            Optional<String> terminationDate,
            Optional<EmployeeAddress> address,
            List<DeductionDetail> deductions,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.memberId = memberId;
        this.employerId = employerId;
        this.referenceId = referenceId;
        this.employerName = employerName;
        this.firstName = firstName;
        this.lastName = lastName;
        this.suffix = suffix;
        this.email = email;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.phone = phone;
        this.employeeClass = employeeClass;
        this.status = status;
        this.startDate = startDate;
        this.classificationEffectiveDate = classificationEffectiveDate;
        this.compensationType = compensationType;
        this.compensationTypeEffectiveDate = compensationTypeEffectiveDate;
        this.terminationDate = terminationDate;
        this.address = address;
        this.deductions = deductions;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique employee identifier with 'empl_' prefix
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return Unique member identifier with 'mbr_' prefix
     */
    @JsonProperty("member_id")
    public Optional<String> getMemberId() {
        return memberId;
    }

    /**
     * @return Unique identifier of the employer this employment is with (empr_*)
     */
    @JsonProperty("employer_id")
    public Optional<String> getEmployerId() {
        return employerId;
    }

    /**
     * @return Partner-assigned reference ID for the employee
     */
    @JsonIgnore
    public Optional<String> getReferenceId() {
        if (referenceId == null) {
            return Optional.empty();
        }
        return referenceId;
    }

    /**
     * @return Name of the employer this employment is with
     */
    @JsonIgnore
    public Optional<String> getEmployerName() {
        if (employerName == null) {
            return Optional.empty();
        }
        return employerName;
    }

    /**
     * @return Employee's legal first name
     */
    @JsonProperty("first_name")
    public String getFirstName() {
        return firstName;
    }

    /**
     * @return Employee's legal last name
     */
    @JsonProperty("last_name")
    public String getLastName() {
        return lastName;
    }

    /**
     * @return Name suffix (e.g., Jr., Sr., III)
     */
    @JsonIgnore
    public Optional<String> getSuffix() {
        if (suffix == null) {
            return Optional.empty();
        }
        return suffix;
    }

    /**
     * @return Email address
     */
    @JsonProperty("email")
    public String getEmail() {
        return email;
    }

    /**
     * @return Date of birth (YYYY-MM-DD)
     */
    @JsonProperty("date_of_birth")
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * @return Gender identity, if provided
     */
    @JsonIgnore
    public Optional<String> getGender() {
        if (gender == null) {
            return Optional.empty();
        }
        return gender;
    }

    /**
     * @return Phone number (10-digit US domestic string)
     */
    @JsonIgnore
    public Optional<String> getPhone() {
        if (phone == null) {
            return Optional.empty();
        }
        return phone;
    }

    /**
     * @return Employment classification affecting benefit eligibility
     * <ul>
     * <li><code>Full Time</code> - Full Time</li>
     * <li><code>Part Time</code> - Part Time</li>
     * <li><code>Temporary</code> - Temporary</li>
     * <li><code>Intern</code> - Intern</li>
     * <li><code>Seasonal</code> - Seasonal</li>
     * <li><code>Individual Contractor</code> - Individual Contractor</li>
     * </ul>
     */
    @JsonProperty("employee_class")
    public EmployeeClass getEmployeeClass() {
        return employeeClass;
    }

    /**
     * @return Employee status (active or terminated)
     */
    @JsonProperty("status")
    public Optional<EmployeeStatus> getStatus() {
        return status;
    }

    /**
     * @return Employee's start date with the employer
     */
    @JsonProperty("start_date")
    public Optional<String> getStartDate() {
        return startDate;
    }

    /**
     * @return Date the employee's current classification took effect
     */
    @JsonProperty("classification_effective_date")
    public Optional<String> getClassificationEffectiveDate() {
        return classificationEffectiveDate;
    }

    /**
     * @return Employee's compensation type
     */
    @JsonIgnore
    public Optional<CompensationType> getCompensationType() {
        if (compensationType == null) {
            return Optional.empty();
        }
        return compensationType;
    }

    /**
     * @return Date the employee's current compensation type took effect
     */
    @JsonProperty("compensation_type_effective_date")
    public Optional<String> getCompensationTypeEffectiveDate() {
        return compensationTypeEffectiveDate;
    }

    /**
     * @return Employee's termination date, if terminated
     */
    @JsonIgnore
    public Optional<String> getTerminationDate() {
        if (terminationDate == null) {
            return Optional.empty();
        }
        return terminationDate;
    }

    /**
     * @return Employee's residential address
     */
    @JsonIgnore
    public Optional<EmployeeAddress> getAddress() {
        if (address == null) {
            return Optional.empty();
        }
        return address;
    }

    /**
     * @return Payroll deductions from the most recent statement period. Replaced when a new statement is generated.
     */
    @JsonProperty("deductions")
    public List<DeductionDetail> getDeductions() {
        return deductions;
    }

    /**
     * @return Timestamp when the employee was created
     */
    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Timestamp when the employee was last updated
     */
    @JsonProperty("updated_at")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("reference_id")
    private Optional<String> _getReferenceId() {
        return referenceId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("employer_name")
    private Optional<String> _getEmployerName() {
        return employerName;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("suffix")
    private Optional<String> _getSuffix() {
        return suffix;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("gender")
    private Optional<String> _getGender() {
        return gender;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("phone")
    private Optional<String> _getPhone() {
        return phone;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("compensation_type")
    private Optional<CompensationType> _getCompensationType() {
        return compensationType;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("termination_date")
    private Optional<String> _getTerminationDate() {
        return terminationDate;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("address")
    private Optional<EmployeeAddress> _getAddress() {
        return address;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Employee && equalTo((Employee) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Employee other) {
        return id.equals(other.id)
                && memberId.equals(other.memberId)
                && employerId.equals(other.employerId)
                && referenceId.equals(other.referenceId)
                && employerName.equals(other.employerName)
                && firstName.equals(other.firstName)
                && lastName.equals(other.lastName)
                && suffix.equals(other.suffix)
                && email.equals(other.email)
                && dateOfBirth.equals(other.dateOfBirth)
                && gender.equals(other.gender)
                && phone.equals(other.phone)
                && employeeClass.equals(other.employeeClass)
                && status.equals(other.status)
                && startDate.equals(other.startDate)
                && classificationEffectiveDate.equals(other.classificationEffectiveDate)
                && compensationType.equals(other.compensationType)
                && compensationTypeEffectiveDate.equals(other.compensationTypeEffectiveDate)
                && terminationDate.equals(other.terminationDate)
                && address.equals(other.address)
                && deductions.equals(other.deductions)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.memberId,
                this.employerId,
                this.referenceId,
                this.employerName,
                this.firstName,
                this.lastName,
                this.suffix,
                this.email,
                this.dateOfBirth,
                this.gender,
                this.phone,
                this.employeeClass,
                this.status,
                this.startDate,
                this.classificationEffectiveDate,
                this.compensationType,
                this.compensationTypeEffectiveDate,
                this.terminationDate,
                this.address,
                this.deductions,
                this.createdAt,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FirstNameStage builder() {
        return new Builder();
    }

    public interface FirstNameStage {
        /**
         * <p>Employee's legal first name</p>
         */
        LastNameStage firstName(@NotNull String firstName);

        Builder from(Employee other);
    }

    public interface LastNameStage {
        /**
         * <p>Employee's legal last name</p>
         */
        EmailStage lastName(@NotNull String lastName);
    }

    public interface EmailStage {
        /**
         * <p>Email address</p>
         */
        DateOfBirthStage email(@NotNull String email);
    }

    public interface DateOfBirthStage {
        /**
         * <p>Date of birth (YYYY-MM-DD)</p>
         */
        EmployeeClassStage dateOfBirth(@NotNull String dateOfBirth);
    }

    public interface EmployeeClassStage {
        /**
         * <p>Employment classification affecting benefit eligibility</p>
         * <ul>
         * <li><code>Full Time</code> - Full Time</li>
         * <li><code>Part Time</code> - Part Time</li>
         * <li><code>Temporary</code> - Temporary</li>
         * <li><code>Intern</code> - Intern</li>
         * <li><code>Seasonal</code> - Seasonal</li>
         * <li><code>Individual Contractor</code> - Individual Contractor</li>
         * </ul>
         */
        CreatedAtStage employeeClass(@NotNull EmployeeClass employeeClass);
    }

    public interface CreatedAtStage {
        /**
         * <p>Timestamp when the employee was created</p>
         */
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        /**
         * <p>Timestamp when the employee was last updated</p>
         */
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        Employee build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Unique employee identifier with 'empl_' prefix</p>
         */
        _FinalStage id(Optional<String> id);

        _FinalStage id(String id);

        /**
         * <p>Unique member identifier with 'mbr_' prefix</p>
         */
        _FinalStage memberId(Optional<String> memberId);

        _FinalStage memberId(String memberId);

        /**
         * <p>Unique identifier of the employer this employment is with (empr_*)</p>
         */
        _FinalStage employerId(Optional<String> employerId);

        _FinalStage employerId(String employerId);

        /**
         * <p>Partner-assigned reference ID for the employee</p>
         */
        _FinalStage referenceId(Optional<String> referenceId);

        _FinalStage referenceId(String referenceId);

        _FinalStage referenceId(Nullable<String> referenceId);

        /**
         * <p>Name of the employer this employment is with</p>
         */
        _FinalStage employerName(Optional<String> employerName);

        _FinalStage employerName(String employerName);

        _FinalStage employerName(Nullable<String> employerName);

        /**
         * <p>Name suffix (e.g., Jr., Sr., III)</p>
         */
        _FinalStage suffix(Optional<String> suffix);

        _FinalStage suffix(String suffix);

        _FinalStage suffix(Nullable<String> suffix);

        /**
         * <p>Gender identity, if provided</p>
         */
        _FinalStage gender(Optional<String> gender);

        _FinalStage gender(String gender);

        _FinalStage gender(Nullable<String> gender);

        /**
         * <p>Phone number (10-digit US domestic string)</p>
         */
        _FinalStage phone(Optional<String> phone);

        _FinalStage phone(String phone);

        _FinalStage phone(Nullable<String> phone);

        /**
         * <p>Employee status (active or terminated)</p>
         */
        _FinalStage status(Optional<EmployeeStatus> status);

        _FinalStage status(EmployeeStatus status);

        /**
         * <p>Employee's start date with the employer</p>
         */
        _FinalStage startDate(Optional<String> startDate);

        _FinalStage startDate(String startDate);

        /**
         * <p>Date the employee's current classification took effect</p>
         */
        _FinalStage classificationEffectiveDate(Optional<String> classificationEffectiveDate);

        _FinalStage classificationEffectiveDate(String classificationEffectiveDate);

        /**
         * <p>Employee's compensation type</p>
         */
        _FinalStage compensationType(Optional<CompensationType> compensationType);

        _FinalStage compensationType(CompensationType compensationType);

        _FinalStage compensationType(Nullable<CompensationType> compensationType);

        /**
         * <p>Date the employee's current compensation type took effect</p>
         */
        _FinalStage compensationTypeEffectiveDate(Optional<String> compensationTypeEffectiveDate);

        _FinalStage compensationTypeEffectiveDate(String compensationTypeEffectiveDate);

        /**
         * <p>Employee's termination date, if terminated</p>
         */
        _FinalStage terminationDate(Optional<String> terminationDate);

        _FinalStage terminationDate(String terminationDate);

        _FinalStage terminationDate(Nullable<String> terminationDate);

        /**
         * <p>Employee's residential address</p>
         */
        _FinalStage address(Optional<EmployeeAddress> address);

        _FinalStage address(EmployeeAddress address);

        _FinalStage address(Nullable<EmployeeAddress> address);

        /**
         * <p>Payroll deductions from the most recent statement period. Replaced when a new statement is generated.</p>
         */
        _FinalStage deductions(List<DeductionDetail> deductions);

        _FinalStage addDeductions(DeductionDetail deductions);

        _FinalStage addAllDeductions(List<DeductionDetail> deductions);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements FirstNameStage,
                    LastNameStage,
                    EmailStage,
                    DateOfBirthStage,
                    EmployeeClassStage,
                    CreatedAtStage,
                    UpdatedAtStage,
                    _FinalStage {
        private String firstName;

        private String lastName;

        private String email;

        private String dateOfBirth;

        private EmployeeClass employeeClass;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private List<DeductionDetail> deductions = new ArrayList<>();

        private Optional<EmployeeAddress> address = Optional.empty();

        private Optional<String> terminationDate = Optional.empty();

        private Optional<String> compensationTypeEffectiveDate = Optional.empty();

        private Optional<CompensationType> compensationType = Optional.empty();

        private Optional<String> classificationEffectiveDate = Optional.empty();

        private Optional<String> startDate = Optional.empty();

        private Optional<EmployeeStatus> status = Optional.empty();

        private Optional<String> phone = Optional.empty();

        private Optional<String> gender = Optional.empty();

        private Optional<String> suffix = Optional.empty();

        private Optional<String> employerName = Optional.empty();

        private Optional<String> referenceId = Optional.empty();

        private Optional<String> employerId = Optional.empty();

        private Optional<String> memberId = Optional.empty();

        private Optional<String> id = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Employee other) {
            id(other.getId());
            memberId(other.getMemberId());
            employerId(other.getEmployerId());
            referenceId(other.getReferenceId());
            employerName(other.getEmployerName());
            firstName(other.getFirstName());
            lastName(other.getLastName());
            suffix(other.getSuffix());
            email(other.getEmail());
            dateOfBirth(other.getDateOfBirth());
            gender(other.getGender());
            phone(other.getPhone());
            employeeClass(other.getEmployeeClass());
            status(other.getStatus());
            startDate(other.getStartDate());
            classificationEffectiveDate(other.getClassificationEffectiveDate());
            compensationType(other.getCompensationType());
            compensationTypeEffectiveDate(other.getCompensationTypeEffectiveDate());
            terminationDate(other.getTerminationDate());
            address(other.getAddress());
            deductions(other.getDeductions());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>Employee's legal first name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("first_name")
        public LastNameStage firstName(@NotNull String firstName) {
            this.firstName = Objects.requireNonNull(firstName, "firstName must not be null");
            return this;
        }

        /**
         * <p>Employee's legal last name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("last_name")
        public EmailStage lastName(@NotNull String lastName) {
            this.lastName = Objects.requireNonNull(lastName, "lastName must not be null");
            return this;
        }

        /**
         * <p>Email address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("email")
        public DateOfBirthStage email(@NotNull String email) {
            this.email = Objects.requireNonNull(email, "email must not be null");
            return this;
        }

        /**
         * <p>Date of birth (YYYY-MM-DD)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("date_of_birth")
        public EmployeeClassStage dateOfBirth(@NotNull String dateOfBirth) {
            this.dateOfBirth = Objects.requireNonNull(dateOfBirth, "dateOfBirth must not be null");
            return this;
        }

        /**
         * <p>Employment classification affecting benefit eligibility</p>
         * <ul>
         * <li><code>Full Time</code> - Full Time</li>
         * <li><code>Part Time</code> - Part Time</li>
         * <li><code>Temporary</code> - Temporary</li>
         * <li><code>Intern</code> - Intern</li>
         * <li><code>Seasonal</code> - Seasonal</li>
         * <li><code>Individual Contractor</code> - Individual Contractor</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("employee_class")
        public CreatedAtStage employeeClass(@NotNull EmployeeClass employeeClass) {
            this.employeeClass = Objects.requireNonNull(employeeClass, "employeeClass must not be null");
            return this;
        }

        /**
         * <p>Timestamp when the employee was created</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Timestamp when the employee was last updated</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>Payroll deductions from the most recent statement period. Replaced when a new statement is generated.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllDeductions(List<DeductionDetail> deductions) {
            if (deductions != null) {
                this.deductions.addAll(deductions);
            }
            return this;
        }

        /**
         * <p>Payroll deductions from the most recent statement period. Replaced when a new statement is generated.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addDeductions(DeductionDetail deductions) {
            this.deductions.add(deductions);
            return this;
        }

        /**
         * <p>Payroll deductions from the most recent statement period. Replaced when a new statement is generated.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "deductions", nulls = Nulls.SKIP)
        public _FinalStage deductions(List<DeductionDetail> deductions) {
            this.deductions.clear();
            if (deductions != null) {
                this.deductions.addAll(deductions);
            }
            return this;
        }

        /**
         * <p>Employee's residential address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage address(Nullable<EmployeeAddress> address) {
            if (address.isNull()) {
                this.address = null;
            } else if (address.isEmpty()) {
                this.address = Optional.empty();
            } else {
                this.address = Optional.of(address.get());
            }
            return this;
        }

        /**
         * <p>Employee's residential address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage address(EmployeeAddress address) {
            this.address = Optional.ofNullable(address);
            return this;
        }

        /**
         * <p>Employee's residential address</p>
         */
        @java.lang.Override
        @JsonSetter(value = "address", nulls = Nulls.SKIP)
        public _FinalStage address(Optional<EmployeeAddress> address) {
            this.address = address;
            return this;
        }

        /**
         * <p>Employee's termination date, if terminated</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage terminationDate(Nullable<String> terminationDate) {
            if (terminationDate.isNull()) {
                this.terminationDate = null;
            } else if (terminationDate.isEmpty()) {
                this.terminationDate = Optional.empty();
            } else {
                this.terminationDate = Optional.of(terminationDate.get());
            }
            return this;
        }

        /**
         * <p>Employee's termination date, if terminated</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage terminationDate(String terminationDate) {
            this.terminationDate = Optional.ofNullable(terminationDate);
            return this;
        }

        /**
         * <p>Employee's termination date, if terminated</p>
         */
        @java.lang.Override
        @JsonSetter(value = "termination_date", nulls = Nulls.SKIP)
        public _FinalStage terminationDate(Optional<String> terminationDate) {
            this.terminationDate = terminationDate;
            return this;
        }

        /**
         * <p>Date the employee's current compensation type took effect</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage compensationTypeEffectiveDate(String compensationTypeEffectiveDate) {
            this.compensationTypeEffectiveDate = Optional.ofNullable(compensationTypeEffectiveDate);
            return this;
        }

        /**
         * <p>Date the employee's current compensation type took effect</p>
         */
        @java.lang.Override
        @JsonSetter(value = "compensation_type_effective_date", nulls = Nulls.SKIP)
        public _FinalStage compensationTypeEffectiveDate(Optional<String> compensationTypeEffectiveDate) {
            this.compensationTypeEffectiveDate = compensationTypeEffectiveDate;
            return this;
        }

        /**
         * <p>Employee's compensation type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage compensationType(Nullable<CompensationType> compensationType) {
            if (compensationType.isNull()) {
                this.compensationType = null;
            } else if (compensationType.isEmpty()) {
                this.compensationType = Optional.empty();
            } else {
                this.compensationType = Optional.of(compensationType.get());
            }
            return this;
        }

        /**
         * <p>Employee's compensation type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage compensationType(CompensationType compensationType) {
            this.compensationType = Optional.ofNullable(compensationType);
            return this;
        }

        /**
         * <p>Employee's compensation type</p>
         */
        @java.lang.Override
        @JsonSetter(value = "compensation_type", nulls = Nulls.SKIP)
        public _FinalStage compensationType(Optional<CompensationType> compensationType) {
            this.compensationType = compensationType;
            return this;
        }

        /**
         * <p>Date the employee's current classification took effect</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage classificationEffectiveDate(String classificationEffectiveDate) {
            this.classificationEffectiveDate = Optional.ofNullable(classificationEffectiveDate);
            return this;
        }

        /**
         * <p>Date the employee's current classification took effect</p>
         */
        @java.lang.Override
        @JsonSetter(value = "classification_effective_date", nulls = Nulls.SKIP)
        public _FinalStage classificationEffectiveDate(Optional<String> classificationEffectiveDate) {
            this.classificationEffectiveDate = classificationEffectiveDate;
            return this;
        }

        /**
         * <p>Employee's start date with the employer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage startDate(String startDate) {
            this.startDate = Optional.ofNullable(startDate);
            return this;
        }

        /**
         * <p>Employee's start date with the employer</p>
         */
        @java.lang.Override
        @JsonSetter(value = "start_date", nulls = Nulls.SKIP)
        public _FinalStage startDate(Optional<String> startDate) {
            this.startDate = startDate;
            return this;
        }

        /**
         * <p>Employee status (active or terminated)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(EmployeeStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Employee status (active or terminated)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public _FinalStage status(Optional<EmployeeStatus> status) {
            this.status = status;
            return this;
        }

        /**
         * <p>Phone number (10-digit US domestic string)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phone(Nullable<String> phone) {
            if (phone.isNull()) {
                this.phone = null;
            } else if (phone.isEmpty()) {
                this.phone = Optional.empty();
            } else {
                this.phone = Optional.of(phone.get());
            }
            return this;
        }

        /**
         * <p>Phone number (10-digit US domestic string)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phone(String phone) {
            this.phone = Optional.ofNullable(phone);
            return this;
        }

        /**
         * <p>Phone number (10-digit US domestic string)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "phone", nulls = Nulls.SKIP)
        public _FinalStage phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }

        /**
         * <p>Gender identity, if provided</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage gender(Nullable<String> gender) {
            if (gender.isNull()) {
                this.gender = null;
            } else if (gender.isEmpty()) {
                this.gender = Optional.empty();
            } else {
                this.gender = Optional.of(gender.get());
            }
            return this;
        }

        /**
         * <p>Gender identity, if provided</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage gender(String gender) {
            this.gender = Optional.ofNullable(gender);
            return this;
        }

        /**
         * <p>Gender identity, if provided</p>
         */
        @java.lang.Override
        @JsonSetter(value = "gender", nulls = Nulls.SKIP)
        public _FinalStage gender(Optional<String> gender) {
            this.gender = gender;
            return this;
        }

        /**
         * <p>Name suffix (e.g., Jr., Sr., III)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage suffix(Nullable<String> suffix) {
            if (suffix.isNull()) {
                this.suffix = null;
            } else if (suffix.isEmpty()) {
                this.suffix = Optional.empty();
            } else {
                this.suffix = Optional.of(suffix.get());
            }
            return this;
        }

        /**
         * <p>Name suffix (e.g., Jr., Sr., III)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage suffix(String suffix) {
            this.suffix = Optional.ofNullable(suffix);
            return this;
        }

        /**
         * <p>Name suffix (e.g., Jr., Sr., III)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "suffix", nulls = Nulls.SKIP)
        public _FinalStage suffix(Optional<String> suffix) {
            this.suffix = suffix;
            return this;
        }

        /**
         * <p>Name of the employer this employment is with</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage employerName(Nullable<String> employerName) {
            if (employerName.isNull()) {
                this.employerName = null;
            } else if (employerName.isEmpty()) {
                this.employerName = Optional.empty();
            } else {
                this.employerName = Optional.of(employerName.get());
            }
            return this;
        }

        /**
         * <p>Name of the employer this employment is with</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage employerName(String employerName) {
            this.employerName = Optional.ofNullable(employerName);
            return this;
        }

        /**
         * <p>Name of the employer this employment is with</p>
         */
        @java.lang.Override
        @JsonSetter(value = "employer_name", nulls = Nulls.SKIP)
        public _FinalStage employerName(Optional<String> employerName) {
            this.employerName = employerName;
            return this;
        }

        /**
         * <p>Partner-assigned reference ID for the employee</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage referenceId(Nullable<String> referenceId) {
            if (referenceId.isNull()) {
                this.referenceId = null;
            } else if (referenceId.isEmpty()) {
                this.referenceId = Optional.empty();
            } else {
                this.referenceId = Optional.of(referenceId.get());
            }
            return this;
        }

        /**
         * <p>Partner-assigned reference ID for the employee</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage referenceId(String referenceId) {
            this.referenceId = Optional.ofNullable(referenceId);
            return this;
        }

        /**
         * <p>Partner-assigned reference ID for the employee</p>
         */
        @java.lang.Override
        @JsonSetter(value = "reference_id", nulls = Nulls.SKIP)
        public _FinalStage referenceId(Optional<String> referenceId) {
            this.referenceId = referenceId;
            return this;
        }

        /**
         * <p>Unique identifier of the employer this employment is with (empr_*)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage employerId(String employerId) {
            this.employerId = Optional.ofNullable(employerId);
            return this;
        }

        /**
         * <p>Unique identifier of the employer this employment is with (empr_*)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "employer_id", nulls = Nulls.SKIP)
        public _FinalStage employerId(Optional<String> employerId) {
            this.employerId = employerId;
            return this;
        }

        /**
         * <p>Unique member identifier with 'mbr_' prefix</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage memberId(String memberId) {
            this.memberId = Optional.ofNullable(memberId);
            return this;
        }

        /**
         * <p>Unique member identifier with 'mbr_' prefix</p>
         */
        @java.lang.Override
        @JsonSetter(value = "member_id", nulls = Nulls.SKIP)
        public _FinalStage memberId(Optional<String> memberId) {
            this.memberId = memberId;
            return this;
        }

        /**
         * <p>Unique employee identifier with 'empl_' prefix</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>Unique employee identifier with 'empl_' prefix</p>
         */
        @java.lang.Override
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public _FinalStage id(Optional<String> id) {
            this.id = id;
            return this;
        }

        @java.lang.Override
        public Employee build() {
            return new Employee(
                    id,
                    memberId,
                    employerId,
                    referenceId,
                    employerName,
                    firstName,
                    lastName,
                    suffix,
                    email,
                    dateOfBirth,
                    gender,
                    phone,
                    employeeClass,
                    status,
                    startDate,
                    classificationEffectiveDate,
                    compensationType,
                    compensationTypeEffectiveDate,
                    terminationDate,
                    address,
                    deductions,
                    createdAt,
                    updatedAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
