/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmployerSettings.Builder.class)
public final class EmployerSettings {
    private final Optional<DeductionFrequency> payFrequency;

    private final Map<String, Object> additionalProperties;

    private EmployerSettings(Optional<DeductionFrequency> payFrequency, Map<String, Object> additionalProperties) {
        this.payFrequency = payFrequency;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Payroll deduction frequency. One of: weekly, bi_weekly, semi_monthly, monthly
     * <ul>
     * <li><code>weekly</code> - Weekly</li>
     * <li><code>bi_weekly</code> - Bi-Weekly</li>
     * <li><code>semi_monthly</code> - Semi-Monthly</li>
     * <li><code>monthly</code> - Monthly</li>
     * </ul>
     */
    @JsonIgnore
    public Optional<DeductionFrequency> getPayFrequency() {
        if (payFrequency == null) {
            return Optional.empty();
        }
        return payFrequency;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("pay_frequency")
    private Optional<DeductionFrequency> _getPayFrequency() {
        return payFrequency;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EmployerSettings && equalTo((EmployerSettings) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EmployerSettings other) {
        return payFrequency.equals(other.payFrequency);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.payFrequency);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<DeductionFrequency> payFrequency = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(EmployerSettings other) {
            payFrequency(other.getPayFrequency());
            return this;
        }

        /**
         * <p>Payroll deduction frequency. One of: weekly, bi_weekly, semi_monthly, monthly</p>
         * <ul>
         * <li><code>weekly</code> - Weekly</li>
         * <li><code>bi_weekly</code> - Bi-Weekly</li>
         * <li><code>semi_monthly</code> - Semi-Monthly</li>
         * <li><code>monthly</code> - Monthly</li>
         * </ul>
         */
        @JsonSetter(value = "pay_frequency", nulls = Nulls.SKIP)
        public Builder payFrequency(Optional<DeductionFrequency> payFrequency) {
            this.payFrequency = payFrequency;
            return this;
        }

        public Builder payFrequency(DeductionFrequency payFrequency) {
            this.payFrequency = Optional.ofNullable(payFrequency);
            return this;
        }

        public Builder payFrequency(Nullable<DeductionFrequency> payFrequency) {
            if (payFrequency.isNull()) {
                this.payFrequency = null;
            } else if (payFrequency.isEmpty()) {
                this.payFrequency = Optional.empty();
            } else {
                this.payFrequency = Optional.of(payFrequency.get());
            }
            return this;
        }

        public EmployerSettings build() {
            return new EmployerSettings(payFrequency, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
