/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ErrorResponse.Builder.class)
public final class ErrorResponse {
    private final OffsetDateTime timestamp;

    private final String message;

    private final String error;

    private final Optional<String> appErrorCode;

    private final String traceId;

    private final Map<String, Object> additionalProperties;

    private ErrorResponse(
            OffsetDateTime timestamp,
            String message,
            String error,
            Optional<String> appErrorCode,
            String traceId,
            Map<String, Object> additionalProperties) {
        this.timestamp = timestamp;
        this.message = message;
        this.error = error;
        this.appErrorCode = appErrorCode;
        this.traceId = traceId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ISO 8601 timestamp when the error occurred
     */
    @JsonProperty("timestamp")
    public OffsetDateTime getTimestamp() {
        return timestamp;
    }

    /**
     * @return Human-readable error message
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    /**
     * @return Error message (same as message, for backwards compatibility)
     */
    @JsonProperty("error")
    public String getError() {
        return error;
    }

    /**
     * @return Application-specific error code for programmatic handling
     */
    @JsonIgnore
    public Optional<String> getAppErrorCode() {
        if (appErrorCode == null) {
            return Optional.empty();
        }
        return appErrorCode;
    }

    /**
     * @return Unique trace ID for debugging and support requests
     */
    @JsonProperty("trace_id")
    public String getTraceId() {
        return traceId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("app_error_code")
    private Optional<String> _getAppErrorCode() {
        return appErrorCode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ErrorResponse && equalTo((ErrorResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ErrorResponse other) {
        return timestamp.equals(other.timestamp)
                && message.equals(other.message)
                && error.equals(other.error)
                && appErrorCode.equals(other.appErrorCode)
                && traceId.equals(other.traceId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.timestamp, this.message, this.error, this.appErrorCode, this.traceId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TimestampStage builder() {
        return new Builder();
    }

    public interface TimestampStage {
        /**
         * <p>ISO 8601 timestamp when the error occurred</p>
         */
        MessageStage timestamp(@NotNull OffsetDateTime timestamp);

        Builder from(ErrorResponse other);
    }

    public interface MessageStage {
        /**
         * <p>Human-readable error message</p>
         */
        ErrorStage message(@NotNull String message);
    }

    public interface ErrorStage {
        /**
         * <p>Error message (same as message, for backwards compatibility)</p>
         */
        TraceIdStage error(@NotNull String error);
    }

    public interface TraceIdStage {
        /**
         * <p>Unique trace ID for debugging and support requests</p>
         */
        _FinalStage traceId(@NotNull String traceId);
    }

    public interface _FinalStage {
        ErrorResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Application-specific error code for programmatic handling</p>
         */
        _FinalStage appErrorCode(Optional<String> appErrorCode);

        _FinalStage appErrorCode(String appErrorCode);

        _FinalStage appErrorCode(Nullable<String> appErrorCode);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TimestampStage, MessageStage, ErrorStage, TraceIdStage, _FinalStage {
        private OffsetDateTime timestamp;

        private String message;

        private String error;

        private String traceId;

        private Optional<String> appErrorCode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ErrorResponse other) {
            timestamp(other.getTimestamp());
            message(other.getMessage());
            error(other.getError());
            appErrorCode(other.getAppErrorCode());
            traceId(other.getTraceId());
            return this;
        }

        /**
         * <p>ISO 8601 timestamp when the error occurred</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("timestamp")
        public MessageStage timestamp(@NotNull OffsetDateTime timestamp) {
            this.timestamp = Objects.requireNonNull(timestamp, "timestamp must not be null");
            return this;
        }

        /**
         * <p>Human-readable error message</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public ErrorStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        /**
         * <p>Error message (same as message, for backwards compatibility)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("error")
        public TraceIdStage error(@NotNull String error) {
            this.error = Objects.requireNonNull(error, "error must not be null");
            return this;
        }

        /**
         * <p>Unique trace ID for debugging and support requests</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("trace_id")
        public _FinalStage traceId(@NotNull String traceId) {
            this.traceId = Objects.requireNonNull(traceId, "traceId must not be null");
            return this;
        }

        /**
         * <p>Application-specific error code for programmatic handling</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage appErrorCode(Nullable<String> appErrorCode) {
            if (appErrorCode.isNull()) {
                this.appErrorCode = null;
            } else if (appErrorCode.isEmpty()) {
                this.appErrorCode = Optional.empty();
            } else {
                this.appErrorCode = Optional.of(appErrorCode.get());
            }
            return this;
        }

        /**
         * <p>Application-specific error code for programmatic handling</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage appErrorCode(String appErrorCode) {
            this.appErrorCode = Optional.ofNullable(appErrorCode);
            return this;
        }

        /**
         * <p>Application-specific error code for programmatic handling</p>
         */
        @java.lang.Override
        @JsonSetter(value = "app_error_code", nulls = Nulls.SKIP)
        public _FinalStage appErrorCode(Optional<String> appErrorCode) {
            this.appErrorCode = appErrorCode;
            return this;
        }

        @java.lang.Override
        public ErrorResponse build() {
            return new ErrorResponse(timestamp, message, error, appErrorCode, traceId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
