/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GroupMemberSyncFailure.Builder.class)
public final class GroupMemberSyncFailure {
    private final String referenceId;

    private final GroupMemberSyncFailureOperation operation;

    private final String reason;

    private final Map<String, Object> additionalProperties;

    private GroupMemberSyncFailure(
            String referenceId,
            GroupMemberSyncFailureOperation operation,
            String reason,
            Map<String, Object> additionalProperties) {
        this.referenceId = referenceId;
        this.operation = operation;
        this.reason = reason;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Your identifier for the member that failed to sync.
     */
    @JsonProperty("reference_id")
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * @return The sync operation that failed for this member.
     */
    @JsonProperty("operation")
    public GroupMemberSyncFailureOperation getOperation() {
        return operation;
    }

    /**
     * @return Human-readable explanation of why the operation failed.
     */
    @JsonProperty("reason")
    public String getReason() {
        return reason;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GroupMemberSyncFailure && equalTo((GroupMemberSyncFailure) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GroupMemberSyncFailure other) {
        return referenceId.equals(other.referenceId)
                && operation.equals(other.operation)
                && reason.equals(other.reason);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.referenceId, this.operation, this.reason);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ReferenceIdStage builder() {
        return new Builder();
    }

    public interface ReferenceIdStage {
        /**
         * <p>Your identifier for the member that failed to sync.</p>
         */
        OperationStage referenceId(@NotNull String referenceId);

        Builder from(GroupMemberSyncFailure other);
    }

    public interface OperationStage {
        /**
         * <p>The sync operation that failed for this member.</p>
         */
        ReasonStage operation(@NotNull GroupMemberSyncFailureOperation operation);
    }

    public interface ReasonStage {
        /**
         * <p>Human-readable explanation of why the operation failed.</p>
         */
        _FinalStage reason(@NotNull String reason);
    }

    public interface _FinalStage {
        GroupMemberSyncFailure build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ReferenceIdStage, OperationStage, ReasonStage, _FinalStage {
        private String referenceId;

        private GroupMemberSyncFailureOperation operation;

        private String reason;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GroupMemberSyncFailure other) {
            referenceId(other.getReferenceId());
            operation(other.getOperation());
            reason(other.getReason());
            return this;
        }

        /**
         * <p>Your identifier for the member that failed to sync.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("reference_id")
        public OperationStage referenceId(@NotNull String referenceId) {
            this.referenceId = Objects.requireNonNull(referenceId, "referenceId must not be null");
            return this;
        }

        /**
         * <p>The sync operation that failed for this member.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("operation")
        public ReasonStage operation(@NotNull GroupMemberSyncFailureOperation operation) {
            this.operation = Objects.requireNonNull(operation, "operation must not be null");
            return this;
        }

        /**
         * <p>Human-readable explanation of why the operation failed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("reason")
        public _FinalStage reason(@NotNull String reason) {
            this.reason = Objects.requireNonNull(reason, "reason must not be null");
            return this;
        }

        @java.lang.Override
        public GroupMemberSyncFailure build() {
            return new GroupMemberSyncFailure(referenceId, operation, reason, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
