/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GroupMemberSyncMemberRequest.Builder.class)
public final class GroupMemberSyncMemberRequest {
    private final String referenceId;

    private final String firstName;

    private final String lastName;

    private final String dateOfBirth;

    private final Optional<String> phone;

    private final String planId;

    private final AddressRequest address;

    private final Optional<String> email;

    private final Map<String, Object> additionalProperties;

    private GroupMemberSyncMemberRequest(
            String referenceId,
            String firstName,
            String lastName,
            String dateOfBirth,
            Optional<String> phone,
            String planId,
            AddressRequest address,
            Optional<String> email,
            Map<String, Object> additionalProperties) {
        this.referenceId = referenceId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.phone = phone;
        this.planId = planId;
        this.address = address;
        this.email = email;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Your own identifier for this member. Vitable echoes it back on sync failures so you can match them to your records.
     */
    @JsonProperty("reference_id")
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * @return Member's legal first name.
     */
    @JsonProperty("first_name")
    public String getFirstName() {
        return firstName;
    }

    /**
     * @return Member's legal last name.
     */
    @JsonProperty("last_name")
    public String getLastName() {
        return lastName;
    }

    /**
     * @return Member's date of birth as <code>YYYY-MM-DD</code>.
     */
    @JsonProperty("date_of_birth")
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * @return Member's contact phone number in E.164 format.
     */
    @JsonIgnore
    public Optional<String> getPhone() {
        if (phone == null) {
            return Optional.empty();
        }
        return phone;
    }

    /**
     * @return Plan the member should be subscribed to (<code>plan_*</code>).
     */
    @JsonProperty("plan_id")
    public String getPlanId() {
        return planId;
    }

    /**
     * @return The member's postal address.
     */
    @JsonProperty("address")
    public AddressRequest getAddress() {
        return address;
    }

    /**
     * @return Member's email address. Vitable sends care and coverage notices here.
     */
    @JsonIgnore
    public Optional<String> getEmail() {
        if (email == null) {
            return Optional.empty();
        }
        return email;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("phone")
    private Optional<String> _getPhone() {
        return phone;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("email")
    private Optional<String> _getEmail() {
        return email;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GroupMemberSyncMemberRequest && equalTo((GroupMemberSyncMemberRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GroupMemberSyncMemberRequest other) {
        return referenceId.equals(other.referenceId)
                && firstName.equals(other.firstName)
                && lastName.equals(other.lastName)
                && dateOfBirth.equals(other.dateOfBirth)
                && phone.equals(other.phone)
                && planId.equals(other.planId)
                && address.equals(other.address)
                && email.equals(other.email);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.referenceId,
                this.firstName,
                this.lastName,
                this.dateOfBirth,
                this.phone,
                this.planId,
                this.address,
                this.email);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ReferenceIdStage builder() {
        return new Builder();
    }

    public interface ReferenceIdStage {
        /**
         * <p>Your own identifier for this member. Vitable echoes it back on sync failures so you can match them to your records.</p>
         */
        FirstNameStage referenceId(@NotNull String referenceId);

        Builder from(GroupMemberSyncMemberRequest other);
    }

    public interface FirstNameStage {
        /**
         * <p>Member's legal first name.</p>
         */
        LastNameStage firstName(@NotNull String firstName);
    }

    public interface LastNameStage {
        /**
         * <p>Member's legal last name.</p>
         */
        DateOfBirthStage lastName(@NotNull String lastName);
    }

    public interface DateOfBirthStage {
        /**
         * <p>Member's date of birth as <code>YYYY-MM-DD</code>.</p>
         */
        PlanIdStage dateOfBirth(@NotNull String dateOfBirth);
    }

    public interface PlanIdStage {
        /**
         * <p>Plan the member should be subscribed to (<code>plan_*</code>).</p>
         */
        AddressStage planId(@NotNull String planId);
    }

    public interface AddressStage {
        /**
         * <p>The member's postal address.</p>
         */
        _FinalStage address(@NotNull AddressRequest address);
    }

    public interface _FinalStage {
        GroupMemberSyncMemberRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Member's contact phone number in E.164 format.</p>
         */
        _FinalStage phone(Optional<String> phone);

        _FinalStage phone(String phone);

        _FinalStage phone(Nullable<String> phone);

        /**
         * <p>Member's email address. Vitable sends care and coverage notices here.</p>
         */
        _FinalStage email(Optional<String> email);

        _FinalStage email(String email);

        _FinalStage email(Nullable<String> email);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ReferenceIdStage,
                    FirstNameStage,
                    LastNameStage,
                    DateOfBirthStage,
                    PlanIdStage,
                    AddressStage,
                    _FinalStage {
        private String referenceId;

        private String firstName;

        private String lastName;

        private String dateOfBirth;

        private String planId;

        private AddressRequest address;

        private Optional<String> email = Optional.empty();

        private Optional<String> phone = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GroupMemberSyncMemberRequest other) {
            referenceId(other.getReferenceId());
            firstName(other.getFirstName());
            lastName(other.getLastName());
            dateOfBirth(other.getDateOfBirth());
            phone(other.getPhone());
            planId(other.getPlanId());
            address(other.getAddress());
            email(other.getEmail());
            return this;
        }

        /**
         * <p>Your own identifier for this member. Vitable echoes it back on sync failures so you can match them to your records.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("reference_id")
        public FirstNameStage referenceId(@NotNull String referenceId) {
            this.referenceId = Objects.requireNonNull(referenceId, "referenceId must not be null");
            return this;
        }

        /**
         * <p>Member's legal first name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("first_name")
        public LastNameStage firstName(@NotNull String firstName) {
            this.firstName = Objects.requireNonNull(firstName, "firstName must not be null");
            return this;
        }

        /**
         * <p>Member's legal last name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("last_name")
        public DateOfBirthStage lastName(@NotNull String lastName) {
            this.lastName = Objects.requireNonNull(lastName, "lastName must not be null");
            return this;
        }

        /**
         * <p>Member's date of birth as <code>YYYY-MM-DD</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("date_of_birth")
        public PlanIdStage dateOfBirth(@NotNull String dateOfBirth) {
            this.dateOfBirth = Objects.requireNonNull(dateOfBirth, "dateOfBirth must not be null");
            return this;
        }

        /**
         * <p>Plan the member should be subscribed to (<code>plan_*</code>).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("plan_id")
        public AddressStage planId(@NotNull String planId) {
            this.planId = Objects.requireNonNull(planId, "planId must not be null");
            return this;
        }

        /**
         * <p>The member's postal address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("address")
        public _FinalStage address(@NotNull AddressRequest address) {
            this.address = Objects.requireNonNull(address, "address must not be null");
            return this;
        }

        /**
         * <p>Member's email address. Vitable sends care and coverage notices here.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(Nullable<String> email) {
            if (email.isNull()) {
                this.email = null;
            } else if (email.isEmpty()) {
                this.email = Optional.empty();
            } else {
                this.email = Optional.of(email.get());
            }
            return this;
        }

        /**
         * <p>Member's email address. Vitable sends care and coverage notices here.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>Member's email address. Vitable sends care and coverage notices here.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public _FinalStage email(Optional<String> email) {
            this.email = email;
            return this;
        }

        /**
         * <p>Member's contact phone number in E.164 format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phone(Nullable<String> phone) {
            if (phone.isNull()) {
                this.phone = null;
            } else if (phone.isEmpty()) {
                this.phone = Optional.empty();
            } else {
                this.phone = Optional.of(phone.get());
            }
            return this;
        }

        /**
         * <p>Member's contact phone number in E.164 format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phone(String phone) {
            this.phone = Optional.ofNullable(phone);
            return this;
        }

        /**
         * <p>Member's contact phone number in E.164 format.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "phone", nulls = Nulls.SKIP)
        public _FinalStage phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }

        @java.lang.Override
        public GroupMemberSyncMemberRequest build() {
            return new GroupMemberSyncMemberRequest(
                    referenceId, firstName, lastName, dateOfBirth, phone, planId, address, email, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
