/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class IdpProvider {
    public static final IdpProvider WORKOS = new IdpProvider(Value.WORKOS, "workos");

    public static final IdpProvider VITABLE = new IdpProvider(Value.VITABLE, "vitable");

    private final Value value;

    private final String string;

    IdpProvider(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof IdpProvider && this.string.equals(((IdpProvider) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WORKOS:
                return visitor.visitWorkos();
            case VITABLE:
                return visitor.visitVitable();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static IdpProvider valueOf(String value) {
        switch (value) {
            case "workos":
                return WORKOS;
            case "vitable":
                return VITABLE;
            default:
                return new IdpProvider(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        WORKOS,

        VITABLE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitWorkos();

        T visitVitable();

        T visitUnknown(String unknownType);
    }
}
