/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Invoice.Builder.class)
public final class Invoice {
    private final String invoiceId;

    private final Optional<String> period;

    private final Optional<Double> total;

    private final Optional<String> status;

    private final Map<String, Object> additionalProperties;

    private Invoice(
            String invoiceId,
            Optional<String> period,
            Optional<Double> total,
            Optional<String> status,
            Map<String, Object> additionalProperties) {
        this.invoiceId = invoiceId;
        this.period = period;
        this.total = total;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Chargebee invoice id (external id, not a prefixed UUID).
     */
    @JsonProperty("invoice_id")
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * @return Invoice date as an ISO string, or null.
     */
    @JsonIgnore
    public Optional<String> getPeriod() {
        if (period == null) {
            return Optional.empty();
        }
        return period;
    }

    /**
     * @return Invoice total in dollars, or null.
     */
    @JsonIgnore
    public Optional<Double> getTotal() {
        if (total == null) {
            return Optional.empty();
        }
        return total;
    }

    /**
     * @return Chargebee invoice status (e.g. <code>paid</code>), or null.
     */
    @JsonIgnore
    public Optional<String> getStatus() {
        if (status == null) {
            return Optional.empty();
        }
        return status;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("period")
    private Optional<String> _getPeriod() {
        return period;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("total")
    private Optional<Double> _getTotal() {
        return total;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("status")
    private Optional<String> _getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Invoice && equalTo((Invoice) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Invoice other) {
        return invoiceId.equals(other.invoiceId)
                && period.equals(other.period)
                && total.equals(other.total)
                && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.invoiceId, this.period, this.total, this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static InvoiceIdStage builder() {
        return new Builder();
    }

    public interface InvoiceIdStage {
        /**
         * <p>Chargebee invoice id (external id, not a prefixed UUID).</p>
         */
        _FinalStage invoiceId(@NotNull String invoiceId);

        Builder from(Invoice other);
    }

    public interface _FinalStage {
        Invoice build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Invoice date as an ISO string, or null.</p>
         */
        _FinalStage period(Optional<String> period);

        _FinalStage period(String period);

        _FinalStage period(Nullable<String> period);

        /**
         * <p>Invoice total in dollars, or null.</p>
         */
        _FinalStage total(Optional<Double> total);

        _FinalStage total(Double total);

        _FinalStage total(Nullable<Double> total);

        /**
         * <p>Chargebee invoice status (e.g. <code>paid</code>), or null.</p>
         */
        _FinalStage status(Optional<String> status);

        _FinalStage status(String status);

        _FinalStage status(Nullable<String> status);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements InvoiceIdStage, _FinalStage {
        private String invoiceId;

        private Optional<String> status = Optional.empty();

        private Optional<Double> total = Optional.empty();

        private Optional<String> period = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Invoice other) {
            invoiceId(other.getInvoiceId());
            period(other.getPeriod());
            total(other.getTotal());
            status(other.getStatus());
            return this;
        }

        /**
         * <p>Chargebee invoice id (external id, not a prefixed UUID).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("invoice_id")
        public _FinalStage invoiceId(@NotNull String invoiceId) {
            this.invoiceId = Objects.requireNonNull(invoiceId, "invoiceId must not be null");
            return this;
        }

        /**
         * <p>Chargebee invoice status (e.g. <code>paid</code>), or null.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(Nullable<String> status) {
            if (status.isNull()) {
                this.status = null;
            } else if (status.isEmpty()) {
                this.status = Optional.empty();
            } else {
                this.status = Optional.of(status.get());
            }
            return this;
        }

        /**
         * <p>Chargebee invoice status (e.g. <code>paid</code>), or null.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(String status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Chargebee invoice status (e.g. <code>paid</code>), or null.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public _FinalStage status(Optional<String> status) {
            this.status = status;
            return this;
        }

        /**
         * <p>Invoice total in dollars, or null.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage total(Nullable<Double> total) {
            if (total.isNull()) {
                this.total = null;
            } else if (total.isEmpty()) {
                this.total = Optional.empty();
            } else {
                this.total = Optional.of(total.get());
            }
            return this;
        }

        /**
         * <p>Invoice total in dollars, or null.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage total(Double total) {
            this.total = Optional.ofNullable(total);
            return this;
        }

        /**
         * <p>Invoice total in dollars, or null.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "total", nulls = Nulls.SKIP)
        public _FinalStage total(Optional<Double> total) {
            this.total = total;
            return this;
        }

        /**
         * <p>Invoice date as an ISO string, or null.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage period(Nullable<String> period) {
            if (period.isNull()) {
                this.period = null;
            } else if (period.isEmpty()) {
                this.period = Optional.empty();
            } else {
                this.period = Optional.of(period.get());
            }
            return this;
        }

        /**
         * <p>Invoice date as an ISO string, or null.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage period(String period) {
            this.period = Optional.ofNullable(period);
            return this;
        }

        /**
         * <p>Invoice date as an ISO string, or null.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "period", nulls = Nulls.SKIP)
        public _FinalStage period(Optional<String> period) {
            this.period = period;
            return this;
        }

        @java.lang.Override
        public Invoice build() {
            return new Invoice(invoiceId, period, total, status, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
