/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MemberEnrollment.Builder.class)
public final class MemberEnrollment {
    private final String id;

    private final String employerId;

    private final String benefitPlanYearId;

    private final Category benefitType;

    private final ProductCode productCode;

    private final boolean requiresQleForReissue;

    private final String productName;

    private final String employerName;

    private final Optional<String> carrierName;

    private final Optional<String> planName;

    private final Optional<String> tierName;

    private final Optional<Integer> employeeDeductionInCents;

    private final Optional<Integer> employerContributionInCents;

    private final Optional<Integer> premiumInCents;

    private final Optional<String> coverageStart;

    private final Optional<String> coverageEnd;

    private final Optional<String> cancelledDate;

    private final Optional<String> planYearCoverageEnd;

    private final String issuedDate;

    private final String enrollmentWindowStart;

    private final Optional<String> enrollmentWindowEnd;

    private final PlanYearEnrollmentElectionStatus electionStatus;

    private final Optional<PlanYearEnrollmentPolicyStatus> policyStatus;

    private final boolean inLastMonthOfCoverage;

    private final boolean isWithinEnrollmentWindow;

    private final Map<String, Object> additionalProperties;

    private MemberEnrollment(
            String id,
            String employerId,
            String benefitPlanYearId,
            Category benefitType,
            ProductCode productCode,
            boolean requiresQleForReissue,
            String productName,
            String employerName,
            Optional<String> carrierName,
            Optional<String> planName,
            Optional<String> tierName,
            Optional<Integer> employeeDeductionInCents,
            Optional<Integer> employerContributionInCents,
            Optional<Integer> premiumInCents,
            Optional<String> coverageStart,
            Optional<String> coverageEnd,
            Optional<String> cancelledDate,
            Optional<String> planYearCoverageEnd,
            String issuedDate,
            String enrollmentWindowStart,
            Optional<String> enrollmentWindowEnd,
            PlanYearEnrollmentElectionStatus electionStatus,
            Optional<PlanYearEnrollmentPolicyStatus> policyStatus,
            boolean inLastMonthOfCoverage,
            boolean isWithinEnrollmentWindow,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.employerId = employerId;
        this.benefitPlanYearId = benefitPlanYearId;
        this.benefitType = benefitType;
        this.productCode = productCode;
        this.requiresQleForReissue = requiresQleForReissue;
        this.productName = productName;
        this.employerName = employerName;
        this.carrierName = carrierName;
        this.planName = planName;
        this.tierName = tierName;
        this.employeeDeductionInCents = employeeDeductionInCents;
        this.employerContributionInCents = employerContributionInCents;
        this.premiumInCents = premiumInCents;
        this.coverageStart = coverageStart;
        this.coverageEnd = coverageEnd;
        this.cancelledDate = cancelledDate;
        this.planYearCoverageEnd = planYearCoverageEnd;
        this.issuedDate = issuedDate;
        this.enrollmentWindowStart = enrollmentWindowStart;
        this.enrollmentWindowEnd = enrollmentWindowEnd;
        this.electionStatus = electionStatus;
        this.policyStatus = policyStatus;
        this.inLastMonthOfCoverage = inLastMonthOfCoverage;
        this.isWithinEnrollmentWindow = isWithinEnrollmentWindow;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Opaque, stable enrollment identifier used to target enrollment actions
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Exact employer identifier for this enrollment
     */
    @JsonProperty("employer_id")
    public String getEmployerId() {
        return employerId;
    }

    /**
     * @return Exact benefit plan-year identifier for this enrollment
     */
    @JsonProperty("benefit_plan_year_id")
    public String getBenefitPlanYearId() {
        return benefitPlanYearId;
    }

    /**
     * @return High-level benefit grouping (e.g., Medical, Dental)
     * <ul>
     * <li><code>Medical</code> - Medical</li>
     * <li><code>Dental</code> - Dental</li>
     * <li><code>Vision</code> - Vision</li>
     * <li><code>Hospital</code> - Hospital</li>
     * </ul>
     */
    @JsonProperty("benefit_type")
    public Category getBenefitType() {
        return benefitType;
    }

    /**
     * @return The benefit product this enrollment is for
     * <ul>
     * <li><code>EBA</code> - Eba Mec</li>
     * <li><code>VPC</code> - Vpc Enhanced</li>
     * <li><code>VPC_CORE</code> - Vpc Core</li>
     * <li><code>MEC</code> - Vpc Mec</li>
     * <li><code>MEC2</code> - Mec2</li>
     * <li><code>MEC_PLUS</code> - Mec Plus</li>
     * <li><code>MVP</code> - Mvp</li>
     * <li><code>MVP2</code> - Mvp2</li>
     * <li><code>MVPSL</code> - Mvpsl</li>
     * <li><code>MVPSL2</code> - Mvpsl2</li>
     * <li><code>VD</code> - Dental</li>
     * <li><code>VV</code> - Vision</li>
     * <li><code>ICHRA</code> - Ichra</li>
     * <li><code>ICHRA_PREMIUM_PLUS</code> - Ichra Premium Plus</li>
     * <li><code>ICHRA_REIMBURSEMENT_ONLY</code> - Ichra Reimbursement Only</li>
     * </ul>
     */
    @JsonProperty("product_code")
    public ProductCode getProductCode() {
        return productCode;
    }

    /**
     * @return Whether a qualifying life event would be required to reissue this enrollment under the product and open-enrollment rule at the time this list was read
     */
    @JsonProperty("requires_qle_for_reissue")
    public boolean getRequiresQleForReissue() {
        return requiresQleForReissue;
    }

    /**
     * @return Display name of the benefit product
     */
    @JsonProperty("product_name")
    public String getProductName() {
        return productName;
    }

    /**
     * @return Name of the employer the enrollment is through
     */
    @JsonProperty("employer_name")
    public String getEmployerName() {
        return employerName;
    }

    /**
     * @return Insurance carrier name; null when no active carrier period is resolvable
     */
    @JsonIgnore
    public Optional<String> getCarrierName() {
        if (carrierName == null) {
            return Optional.empty();
        }
        return carrierName;
    }

    /**
     * @return Chosen benefit plan name; null unless the row is an election
     */
    @JsonIgnore
    public Optional<String> getPlanName() {
        if (planName == null) {
            return Optional.empty();
        }
        return planName;
    }

    /**
     * @return Chosen benefit plan tier name (e.g., Employee Only); null unless the row is an election
     */
    @JsonIgnore
    public Optional<String> getTierName() {
        if (tierName == null) {
            return Optional.empty();
        }
        return tierName;
    }

    /**
     * @return Employee monthly payroll deduction in cents; null unless the row is an election
     */
    @JsonIgnore
    public Optional<Integer> getEmployeeDeductionInCents() {
        if (employeeDeductionInCents == null) {
            return Optional.empty();
        }
        return employeeDeductionInCents;
    }

    /**
     * @return Employer monthly contribution in cents; null unless the row is an election
     */
    @JsonIgnore
    public Optional<Integer> getEmployerContributionInCents() {
        if (employerContributionInCents == null) {
            return Optional.empty();
        }
        return employerContributionInCents;
    }

    /**
     * @return Total monthly plan premium in cents; null unless the row is an election
     */
    @JsonIgnore
    public Optional<Integer> getPremiumInCents() {
        if (premiumInCents == null) {
            return Optional.empty();
        }
        return premiumInCents;
    }

    /**
     * @return Coverage window start date (YYYY-MM-DD)
     */
    @JsonIgnore
    public Optional<String> getCoverageStart() {
        if (coverageStart == null) {
            return Optional.empty();
        }
        return coverageStart;
    }

    /**
     * @return Coverage window end date (YYYY-MM-DD); null while coverage is open-ended
     */
    @JsonIgnore
    public Optional<String> getCoverageEnd() {
        if (coverageEnd == null) {
            return Optional.empty();
        }
        return coverageEnd;
    }

    /**
     * @return Earliest applicable coverage boundary (YYYY-MM-DD) when coverage was cancelled before its effective start; null unless the enrollment was cancelled
     */
    @JsonIgnore
    public Optional<String> getCancelledDate() {
        if (cancelledDate == null) {
            return Optional.empty();
        }
        return cancelledDate;
    }

    /**
     * @return Benefit plan-year coverage end date (YYYY-MM-DD), distinct from this enrollment's coverage_end; null when the plan year is open-ended
     */
    @JsonIgnore
    public Optional<String> getPlanYearCoverageEnd() {
        if (planYearCoverageEnd == null) {
            return Optional.empty();
        }
        return planYearCoverageEnd;
    }

    /**
     * @return Date the enrollment record was created (YYYY-MM-DD), the value Ops labels Issued on. Present on every row whatever the member answered, and distinct from <code>coverage_start</code>. It equals <code>enrollment_window_start</code> for a row issued once its open enrollment had already opened, and precedes it for a row issued ahead of open enrollment.
     */
    @JsonProperty("issued_date")
    public String getIssuedDate() {
        return issuedDate;
    }

    /**
     * @return First date the member could answer this enrollment (YYYY-MM-DD). Open enrollment's start date for a row issued before open enrollment opened, otherwise the date the row was issued -- an enrollment is never answerable before it exists, so this is never earlier than <code>issued_date</code>.
     */
    @JsonProperty("enrollment_window_start")
    public String getEnrollmentWindowStart() {
        return enrollmentWindowStart;
    }

    /**
     * @return Enrollment / open-enrollment window end date (YYYY-MM-DD); null when open-ended
     */
    @JsonIgnore
    public Optional<String> getEnrollmentWindowEnd() {
        if (enrollmentWindowEnd == null) {
            return Optional.empty();
        }
        return enrollmentWindowEnd;
    }

    /**
     * @return Where the member stands: <code>Enrolled</code> or <code>Waived</code> if they answered, otherwise <code>Pending</code> while their enrollment window is open and <code>Expired</code> once it has closed.
     * <ul>
     * <li><code>Enrolled</code> - Enrolled</li>
     * <li><code>Waived</code> - Waived</li>
     * <li><code>Pending</code> - Pending</li>
     * <li><code>Expired</code> - Expired</li>
     * </ul>
     */
    @JsonProperty("election_status")
    public PlanYearEnrollmentElectionStatus getElectionStatus() {
        return electionStatus;
    }

    /**
     * @return Where the member's coverage stands: <code>Coverage Upcoming</code>, <code>Coverage Effective</code>, <code>Coverage Ended</code>, or <code>Cancelled</code>. Null unless the member enrolled.
     * <ul>
     * <li><code>Coverage Upcoming</code> - Coverage Upcoming</li>
     * <li><code>Coverage Effective</code> - Coverage Effective</li>
     * <li><code>Coverage Ended</code> - Coverage Ended</li>
     * <li><code>Cancelled</code> - Cancelled</li>
     * </ul>
     */
    @JsonIgnore
    public Optional<PlanYearEnrollmentPolicyStatus> getPolicyStatus() {
        if (policyStatus == null) {
            return Optional.empty();
        }
        return policyStatus;
    }

    /**
     * @return True when today falls in the final month of the plan-year coverage window; drives end-of-coverage enrollment actions on the client.
     */
    @JsonProperty("in_last_month_of_coverage")
    public boolean getInLastMonthOfCoverage() {
        return inLastMonthOfCoverage;
    }

    /**
     * @return True when today falls inside the enrollment window this member has to answer in; drives enrollment-action availability on the client.
     */
    @JsonProperty("is_within_enrollment_window")
    public boolean getIsWithinEnrollmentWindow() {
        return isWithinEnrollmentWindow;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("carrier_name")
    private Optional<String> _getCarrierName() {
        return carrierName;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("plan_name")
    private Optional<String> _getPlanName() {
        return planName;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("tier_name")
    private Optional<String> _getTierName() {
        return tierName;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("employee_deduction_in_cents")
    private Optional<Integer> _getEmployeeDeductionInCents() {
        return employeeDeductionInCents;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("employer_contribution_in_cents")
    private Optional<Integer> _getEmployerContributionInCents() {
        return employerContributionInCents;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("premium_in_cents")
    private Optional<Integer> _getPremiumInCents() {
        return premiumInCents;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("coverage_start")
    private Optional<String> _getCoverageStart() {
        return coverageStart;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("coverage_end")
    private Optional<String> _getCoverageEnd() {
        return coverageEnd;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("cancelled_date")
    private Optional<String> _getCancelledDate() {
        return cancelledDate;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("plan_year_coverage_end")
    private Optional<String> _getPlanYearCoverageEnd() {
        return planYearCoverageEnd;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("enrollment_window_end")
    private Optional<String> _getEnrollmentWindowEnd() {
        return enrollmentWindowEnd;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("policy_status")
    private Optional<PlanYearEnrollmentPolicyStatus> _getPolicyStatus() {
        return policyStatus;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MemberEnrollment && equalTo((MemberEnrollment) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MemberEnrollment other) {
        return id.equals(other.id)
                && employerId.equals(other.employerId)
                && benefitPlanYearId.equals(other.benefitPlanYearId)
                && benefitType.equals(other.benefitType)
                && productCode.equals(other.productCode)
                && requiresQleForReissue == other.requiresQleForReissue
                && productName.equals(other.productName)
                && employerName.equals(other.employerName)
                && carrierName.equals(other.carrierName)
                && planName.equals(other.planName)
                && tierName.equals(other.tierName)
                && employeeDeductionInCents.equals(other.employeeDeductionInCents)
                && employerContributionInCents.equals(other.employerContributionInCents)
                && premiumInCents.equals(other.premiumInCents)
                && coverageStart.equals(other.coverageStart)
                && coverageEnd.equals(other.coverageEnd)
                && cancelledDate.equals(other.cancelledDate)
                && planYearCoverageEnd.equals(other.planYearCoverageEnd)
                && issuedDate.equals(other.issuedDate)
                && enrollmentWindowStart.equals(other.enrollmentWindowStart)
                && enrollmentWindowEnd.equals(other.enrollmentWindowEnd)
                && electionStatus.equals(other.electionStatus)
                && policyStatus.equals(other.policyStatus)
                && inLastMonthOfCoverage == other.inLastMonthOfCoverage
                && isWithinEnrollmentWindow == other.isWithinEnrollmentWindow;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.employerId,
                this.benefitPlanYearId,
                this.benefitType,
                this.productCode,
                this.requiresQleForReissue,
                this.productName,
                this.employerName,
                this.carrierName,
                this.planName,
                this.tierName,
                this.employeeDeductionInCents,
                this.employerContributionInCents,
                this.premiumInCents,
                this.coverageStart,
                this.coverageEnd,
                this.cancelledDate,
                this.planYearCoverageEnd,
                this.issuedDate,
                this.enrollmentWindowStart,
                this.enrollmentWindowEnd,
                this.electionStatus,
                this.policyStatus,
                this.inLastMonthOfCoverage,
                this.isWithinEnrollmentWindow);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Opaque, stable enrollment identifier used to target enrollment actions</p>
         */
        EmployerIdStage id(@NotNull String id);

        Builder from(MemberEnrollment other);
    }

    public interface EmployerIdStage {
        /**
         * <p>Exact employer identifier for this enrollment</p>
         */
        BenefitPlanYearIdStage employerId(@NotNull String employerId);
    }

    public interface BenefitPlanYearIdStage {
        /**
         * <p>Exact benefit plan-year identifier for this enrollment</p>
         */
        BenefitTypeStage benefitPlanYearId(@NotNull String benefitPlanYearId);
    }

    public interface BenefitTypeStage {
        /**
         * <p>High-level benefit grouping (e.g., Medical, Dental)</p>
         * <ul>
         * <li><code>Medical</code> - Medical</li>
         * <li><code>Dental</code> - Dental</li>
         * <li><code>Vision</code> - Vision</li>
         * <li><code>Hospital</code> - Hospital</li>
         * </ul>
         */
        ProductCodeStage benefitType(@NotNull Category benefitType);
    }

    public interface ProductCodeStage {
        /**
         * <p>The benefit product this enrollment is for</p>
         * <ul>
         * <li><code>EBA</code> - Eba Mec</li>
         * <li><code>VPC</code> - Vpc Enhanced</li>
         * <li><code>VPC_CORE</code> - Vpc Core</li>
         * <li><code>MEC</code> - Vpc Mec</li>
         * <li><code>MEC2</code> - Mec2</li>
         * <li><code>MEC_PLUS</code> - Mec Plus</li>
         * <li><code>MVP</code> - Mvp</li>
         * <li><code>MVP2</code> - Mvp2</li>
         * <li><code>MVPSL</code> - Mvpsl</li>
         * <li><code>MVPSL2</code> - Mvpsl2</li>
         * <li><code>VD</code> - Dental</li>
         * <li><code>VV</code> - Vision</li>
         * <li><code>ICHRA</code> - Ichra</li>
         * <li><code>ICHRA_PREMIUM_PLUS</code> - Ichra Premium Plus</li>
         * <li><code>ICHRA_REIMBURSEMENT_ONLY</code> - Ichra Reimbursement Only</li>
         * </ul>
         */
        RequiresQleForReissueStage productCode(@NotNull ProductCode productCode);
    }

    public interface RequiresQleForReissueStage {
        /**
         * <p>Whether a qualifying life event would be required to reissue this enrollment under the product and open-enrollment rule at the time this list was read</p>
         */
        ProductNameStage requiresQleForReissue(boolean requiresQleForReissue);
    }

    public interface ProductNameStage {
        /**
         * <p>Display name of the benefit product</p>
         */
        EmployerNameStage productName(@NotNull String productName);
    }

    public interface EmployerNameStage {
        /**
         * <p>Name of the employer the enrollment is through</p>
         */
        IssuedDateStage employerName(@NotNull String employerName);
    }

    public interface IssuedDateStage {
        /**
         * <p>Date the enrollment record was created (YYYY-MM-DD), the value Ops labels Issued on. Present on every row whatever the member answered, and distinct from <code>coverage_start</code>. It equals <code>enrollment_window_start</code> for a row issued once its open enrollment had already opened, and precedes it for a row issued ahead of open enrollment.</p>
         */
        EnrollmentWindowStartStage issuedDate(@NotNull String issuedDate);
    }

    public interface EnrollmentWindowStartStage {
        /**
         * <p>First date the member could answer this enrollment (YYYY-MM-DD). Open enrollment's start date for a row issued before open enrollment opened, otherwise the date the row was issued -- an enrollment is never answerable before it exists, so this is never earlier than <code>issued_date</code>.</p>
         */
        ElectionStatusStage enrollmentWindowStart(@NotNull String enrollmentWindowStart);
    }

    public interface ElectionStatusStage {
        /**
         * <p>Where the member stands: <code>Enrolled</code> or <code>Waived</code> if they answered, otherwise <code>Pending</code> while their enrollment window is open and <code>Expired</code> once it has closed.</p>
         * <ul>
         * <li><code>Enrolled</code> - Enrolled</li>
         * <li><code>Waived</code> - Waived</li>
         * <li><code>Pending</code> - Pending</li>
         * <li><code>Expired</code> - Expired</li>
         * </ul>
         */
        InLastMonthOfCoverageStage electionStatus(@NotNull PlanYearEnrollmentElectionStatus electionStatus);
    }

    public interface InLastMonthOfCoverageStage {
        /**
         * <p>True when today falls in the final month of the plan-year coverage window; drives end-of-coverage enrollment actions on the client.</p>
         */
        IsWithinEnrollmentWindowStage inLastMonthOfCoverage(boolean inLastMonthOfCoverage);
    }

    public interface IsWithinEnrollmentWindowStage {
        /**
         * <p>True when today falls inside the enrollment window this member has to answer in; drives enrollment-action availability on the client.</p>
         */
        _FinalStage isWithinEnrollmentWindow(boolean isWithinEnrollmentWindow);
    }

    public interface _FinalStage {
        MemberEnrollment build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Insurance carrier name; null when no active carrier period is resolvable</p>
         */
        _FinalStage carrierName(Optional<String> carrierName);

        _FinalStage carrierName(String carrierName);

        _FinalStage carrierName(Nullable<String> carrierName);

        /**
         * <p>Chosen benefit plan name; null unless the row is an election</p>
         */
        _FinalStage planName(Optional<String> planName);

        _FinalStage planName(String planName);

        _FinalStage planName(Nullable<String> planName);

        /**
         * <p>Chosen benefit plan tier name (e.g., Employee Only); null unless the row is an election</p>
         */
        _FinalStage tierName(Optional<String> tierName);

        _FinalStage tierName(String tierName);

        _FinalStage tierName(Nullable<String> tierName);

        /**
         * <p>Employee monthly payroll deduction in cents; null unless the row is an election</p>
         */
        _FinalStage employeeDeductionInCents(Optional<Integer> employeeDeductionInCents);

        _FinalStage employeeDeductionInCents(Integer employeeDeductionInCents);

        _FinalStage employeeDeductionInCents(Nullable<Integer> employeeDeductionInCents);

        /**
         * <p>Employer monthly contribution in cents; null unless the row is an election</p>
         */
        _FinalStage employerContributionInCents(Optional<Integer> employerContributionInCents);

        _FinalStage employerContributionInCents(Integer employerContributionInCents);

        _FinalStage employerContributionInCents(Nullable<Integer> employerContributionInCents);

        /**
         * <p>Total monthly plan premium in cents; null unless the row is an election</p>
         */
        _FinalStage premiumInCents(Optional<Integer> premiumInCents);

        _FinalStage premiumInCents(Integer premiumInCents);

        _FinalStage premiumInCents(Nullable<Integer> premiumInCents);

        /**
         * <p>Coverage window start date (YYYY-MM-DD)</p>
         */
        _FinalStage coverageStart(Optional<String> coverageStart);

        _FinalStage coverageStart(String coverageStart);

        _FinalStage coverageStart(Nullable<String> coverageStart);

        /**
         * <p>Coverage window end date (YYYY-MM-DD); null while coverage is open-ended</p>
         */
        _FinalStage coverageEnd(Optional<String> coverageEnd);

        _FinalStage coverageEnd(String coverageEnd);

        _FinalStage coverageEnd(Nullable<String> coverageEnd);

        /**
         * <p>Earliest applicable coverage boundary (YYYY-MM-DD) when coverage was cancelled before its effective start; null unless the enrollment was cancelled</p>
         */
        _FinalStage cancelledDate(Optional<String> cancelledDate);

        _FinalStage cancelledDate(String cancelledDate);

        _FinalStage cancelledDate(Nullable<String> cancelledDate);

        /**
         * <p>Benefit plan-year coverage end date (YYYY-MM-DD), distinct from this enrollment's coverage_end; null when the plan year is open-ended</p>
         */
        _FinalStage planYearCoverageEnd(Optional<String> planYearCoverageEnd);

        _FinalStage planYearCoverageEnd(String planYearCoverageEnd);

        _FinalStage planYearCoverageEnd(Nullable<String> planYearCoverageEnd);

        /**
         * <p>Enrollment / open-enrollment window end date (YYYY-MM-DD); null when open-ended</p>
         */
        _FinalStage enrollmentWindowEnd(Optional<String> enrollmentWindowEnd);

        _FinalStage enrollmentWindowEnd(String enrollmentWindowEnd);

        _FinalStage enrollmentWindowEnd(Nullable<String> enrollmentWindowEnd);

        /**
         * <p>Where the member's coverage stands: <code>Coverage Upcoming</code>, <code>Coverage Effective</code>, <code>Coverage Ended</code>, or <code>Cancelled</code>. Null unless the member enrolled.</p>
         * <ul>
         * <li><code>Coverage Upcoming</code> - Coverage Upcoming</li>
         * <li><code>Coverage Effective</code> - Coverage Effective</li>
         * <li><code>Coverage Ended</code> - Coverage Ended</li>
         * <li><code>Cancelled</code> - Cancelled</li>
         * </ul>
         */
        _FinalStage policyStatus(Optional<PlanYearEnrollmentPolicyStatus> policyStatus);

        _FinalStage policyStatus(PlanYearEnrollmentPolicyStatus policyStatus);

        _FinalStage policyStatus(Nullable<PlanYearEnrollmentPolicyStatus> policyStatus);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    EmployerIdStage,
                    BenefitPlanYearIdStage,
                    BenefitTypeStage,
                    ProductCodeStage,
                    RequiresQleForReissueStage,
                    ProductNameStage,
                    EmployerNameStage,
                    IssuedDateStage,
                    EnrollmentWindowStartStage,
                    ElectionStatusStage,
                    InLastMonthOfCoverageStage,
                    IsWithinEnrollmentWindowStage,
                    _FinalStage {
        private String id;

        private String employerId;

        private String benefitPlanYearId;

        private Category benefitType;

        private ProductCode productCode;

        private boolean requiresQleForReissue;

        private String productName;

        private String employerName;

        private String issuedDate;

        private String enrollmentWindowStart;

        private PlanYearEnrollmentElectionStatus electionStatus;

        private boolean inLastMonthOfCoverage;

        private boolean isWithinEnrollmentWindow;

        private Optional<PlanYearEnrollmentPolicyStatus> policyStatus = Optional.empty();

        private Optional<String> enrollmentWindowEnd = Optional.empty();

        private Optional<String> planYearCoverageEnd = Optional.empty();

        private Optional<String> cancelledDate = Optional.empty();

        private Optional<String> coverageEnd = Optional.empty();

        private Optional<String> coverageStart = Optional.empty();

        private Optional<Integer> premiumInCents = Optional.empty();

        private Optional<Integer> employerContributionInCents = Optional.empty();

        private Optional<Integer> employeeDeductionInCents = Optional.empty();

        private Optional<String> tierName = Optional.empty();

        private Optional<String> planName = Optional.empty();

        private Optional<String> carrierName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MemberEnrollment other) {
            id(other.getId());
            employerId(other.getEmployerId());
            benefitPlanYearId(other.getBenefitPlanYearId());
            benefitType(other.getBenefitType());
            productCode(other.getProductCode());
            requiresQleForReissue(other.getRequiresQleForReissue());
            productName(other.getProductName());
            employerName(other.getEmployerName());
            carrierName(other.getCarrierName());
            planName(other.getPlanName());
            tierName(other.getTierName());
            employeeDeductionInCents(other.getEmployeeDeductionInCents());
            employerContributionInCents(other.getEmployerContributionInCents());
            premiumInCents(other.getPremiumInCents());
            coverageStart(other.getCoverageStart());
            coverageEnd(other.getCoverageEnd());
            cancelledDate(other.getCancelledDate());
            planYearCoverageEnd(other.getPlanYearCoverageEnd());
            issuedDate(other.getIssuedDate());
            enrollmentWindowStart(other.getEnrollmentWindowStart());
            enrollmentWindowEnd(other.getEnrollmentWindowEnd());
            electionStatus(other.getElectionStatus());
            policyStatus(other.getPolicyStatus());
            inLastMonthOfCoverage(other.getInLastMonthOfCoverage());
            isWithinEnrollmentWindow(other.getIsWithinEnrollmentWindow());
            return this;
        }

        /**
         * <p>Opaque, stable enrollment identifier used to target enrollment actions</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public EmployerIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Exact employer identifier for this enrollment</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("employer_id")
        public BenefitPlanYearIdStage employerId(@NotNull String employerId) {
            this.employerId = Objects.requireNonNull(employerId, "employerId must not be null");
            return this;
        }

        /**
         * <p>Exact benefit plan-year identifier for this enrollment</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("benefit_plan_year_id")
        public BenefitTypeStage benefitPlanYearId(@NotNull String benefitPlanYearId) {
            this.benefitPlanYearId = Objects.requireNonNull(benefitPlanYearId, "benefitPlanYearId must not be null");
            return this;
        }

        /**
         * <p>High-level benefit grouping (e.g., Medical, Dental)</p>
         * <ul>
         * <li><code>Medical</code> - Medical</li>
         * <li><code>Dental</code> - Dental</li>
         * <li><code>Vision</code> - Vision</li>
         * <li><code>Hospital</code> - Hospital</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("benefit_type")
        public ProductCodeStage benefitType(@NotNull Category benefitType) {
            this.benefitType = Objects.requireNonNull(benefitType, "benefitType must not be null");
            return this;
        }

        /**
         * <p>The benefit product this enrollment is for</p>
         * <ul>
         * <li><code>EBA</code> - Eba Mec</li>
         * <li><code>VPC</code> - Vpc Enhanced</li>
         * <li><code>VPC_CORE</code> - Vpc Core</li>
         * <li><code>MEC</code> - Vpc Mec</li>
         * <li><code>MEC2</code> - Mec2</li>
         * <li><code>MEC_PLUS</code> - Mec Plus</li>
         * <li><code>MVP</code> - Mvp</li>
         * <li><code>MVP2</code> - Mvp2</li>
         * <li><code>MVPSL</code> - Mvpsl</li>
         * <li><code>MVPSL2</code> - Mvpsl2</li>
         * <li><code>VD</code> - Dental</li>
         * <li><code>VV</code> - Vision</li>
         * <li><code>ICHRA</code> - Ichra</li>
         * <li><code>ICHRA_PREMIUM_PLUS</code> - Ichra Premium Plus</li>
         * <li><code>ICHRA_REIMBURSEMENT_ONLY</code> - Ichra Reimbursement Only</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("product_code")
        public RequiresQleForReissueStage productCode(@NotNull ProductCode productCode) {
            this.productCode = Objects.requireNonNull(productCode, "productCode must not be null");
            return this;
        }

        /**
         * <p>Whether a qualifying life event would be required to reissue this enrollment under the product and open-enrollment rule at the time this list was read</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("requires_qle_for_reissue")
        public ProductNameStage requiresQleForReissue(boolean requiresQleForReissue) {
            this.requiresQleForReissue = requiresQleForReissue;
            return this;
        }

        /**
         * <p>Display name of the benefit product</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("product_name")
        public EmployerNameStage productName(@NotNull String productName) {
            this.productName = Objects.requireNonNull(productName, "productName must not be null");
            return this;
        }

        /**
         * <p>Name of the employer the enrollment is through</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("employer_name")
        public IssuedDateStage employerName(@NotNull String employerName) {
            this.employerName = Objects.requireNonNull(employerName, "employerName must not be null");
            return this;
        }

        /**
         * <p>Date the enrollment record was created (YYYY-MM-DD), the value Ops labels Issued on. Present on every row whatever the member answered, and distinct from <code>coverage_start</code>. It equals <code>enrollment_window_start</code> for a row issued once its open enrollment had already opened, and precedes it for a row issued ahead of open enrollment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("issued_date")
        public EnrollmentWindowStartStage issuedDate(@NotNull String issuedDate) {
            this.issuedDate = Objects.requireNonNull(issuedDate, "issuedDate must not be null");
            return this;
        }

        /**
         * <p>First date the member could answer this enrollment (YYYY-MM-DD). Open enrollment's start date for a row issued before open enrollment opened, otherwise the date the row was issued -- an enrollment is never answerable before it exists, so this is never earlier than <code>issued_date</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("enrollment_window_start")
        public ElectionStatusStage enrollmentWindowStart(@NotNull String enrollmentWindowStart) {
            this.enrollmentWindowStart =
                    Objects.requireNonNull(enrollmentWindowStart, "enrollmentWindowStart must not be null");
            return this;
        }

        /**
         * <p>Where the member stands: <code>Enrolled</code> or <code>Waived</code> if they answered, otherwise <code>Pending</code> while their enrollment window is open and <code>Expired</code> once it has closed.</p>
         * <ul>
         * <li><code>Enrolled</code> - Enrolled</li>
         * <li><code>Waived</code> - Waived</li>
         * <li><code>Pending</code> - Pending</li>
         * <li><code>Expired</code> - Expired</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("election_status")
        public InLastMonthOfCoverageStage electionStatus(@NotNull PlanYearEnrollmentElectionStatus electionStatus) {
            this.electionStatus = Objects.requireNonNull(electionStatus, "electionStatus must not be null");
            return this;
        }

        /**
         * <p>True when today falls in the final month of the plan-year coverage window; drives end-of-coverage enrollment actions on the client.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("in_last_month_of_coverage")
        public IsWithinEnrollmentWindowStage inLastMonthOfCoverage(boolean inLastMonthOfCoverage) {
            this.inLastMonthOfCoverage = inLastMonthOfCoverage;
            return this;
        }

        /**
         * <p>True when today falls inside the enrollment window this member has to answer in; drives enrollment-action availability on the client.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("is_within_enrollment_window")
        public _FinalStage isWithinEnrollmentWindow(boolean isWithinEnrollmentWindow) {
            this.isWithinEnrollmentWindow = isWithinEnrollmentWindow;
            return this;
        }

        /**
         * <p>Where the member's coverage stands: <code>Coverage Upcoming</code>, <code>Coverage Effective</code>, <code>Coverage Ended</code>, or <code>Cancelled</code>. Null unless the member enrolled.</p>
         * <ul>
         * <li><code>Coverage Upcoming</code> - Coverage Upcoming</li>
         * <li><code>Coverage Effective</code> - Coverage Effective</li>
         * <li><code>Coverage Ended</code> - Coverage Ended</li>
         * <li><code>Cancelled</code> - Cancelled</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage policyStatus(Nullable<PlanYearEnrollmentPolicyStatus> policyStatus) {
            if (policyStatus.isNull()) {
                this.policyStatus = null;
            } else if (policyStatus.isEmpty()) {
                this.policyStatus = Optional.empty();
            } else {
                this.policyStatus = Optional.of(policyStatus.get());
            }
            return this;
        }

        /**
         * <p>Where the member's coverage stands: <code>Coverage Upcoming</code>, <code>Coverage Effective</code>, <code>Coverage Ended</code>, or <code>Cancelled</code>. Null unless the member enrolled.</p>
         * <ul>
         * <li><code>Coverage Upcoming</code> - Coverage Upcoming</li>
         * <li><code>Coverage Effective</code> - Coverage Effective</li>
         * <li><code>Coverage Ended</code> - Coverage Ended</li>
         * <li><code>Cancelled</code> - Cancelled</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage policyStatus(PlanYearEnrollmentPolicyStatus policyStatus) {
            this.policyStatus = Optional.ofNullable(policyStatus);
            return this;
        }

        /**
         * <p>Where the member's coverage stands: <code>Coverage Upcoming</code>, <code>Coverage Effective</code>, <code>Coverage Ended</code>, or <code>Cancelled</code>. Null unless the member enrolled.</p>
         * <ul>
         * <li><code>Coverage Upcoming</code> - Coverage Upcoming</li>
         * <li><code>Coverage Effective</code> - Coverage Effective</li>
         * <li><code>Coverage Ended</code> - Coverage Ended</li>
         * <li><code>Cancelled</code> - Cancelled</li>
         * </ul>
         */
        @java.lang.Override
        @JsonSetter(value = "policy_status", nulls = Nulls.SKIP)
        public _FinalStage policyStatus(Optional<PlanYearEnrollmentPolicyStatus> policyStatus) {
            this.policyStatus = policyStatus;
            return this;
        }

        /**
         * <p>Enrollment / open-enrollment window end date (YYYY-MM-DD); null when open-ended</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage enrollmentWindowEnd(Nullable<String> enrollmentWindowEnd) {
            if (enrollmentWindowEnd.isNull()) {
                this.enrollmentWindowEnd = null;
            } else if (enrollmentWindowEnd.isEmpty()) {
                this.enrollmentWindowEnd = Optional.empty();
            } else {
                this.enrollmentWindowEnd = Optional.of(enrollmentWindowEnd.get());
            }
            return this;
        }

        /**
         * <p>Enrollment / open-enrollment window end date (YYYY-MM-DD); null when open-ended</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage enrollmentWindowEnd(String enrollmentWindowEnd) {
            this.enrollmentWindowEnd = Optional.ofNullable(enrollmentWindowEnd);
            return this;
        }

        /**
         * <p>Enrollment / open-enrollment window end date (YYYY-MM-DD); null when open-ended</p>
         */
        @java.lang.Override
        @JsonSetter(value = "enrollment_window_end", nulls = Nulls.SKIP)
        public _FinalStage enrollmentWindowEnd(Optional<String> enrollmentWindowEnd) {
            this.enrollmentWindowEnd = enrollmentWindowEnd;
            return this;
        }

        /**
         * <p>Benefit plan-year coverage end date (YYYY-MM-DD), distinct from this enrollment's coverage_end; null when the plan year is open-ended</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage planYearCoverageEnd(Nullable<String> planYearCoverageEnd) {
            if (planYearCoverageEnd.isNull()) {
                this.planYearCoverageEnd = null;
            } else if (planYearCoverageEnd.isEmpty()) {
                this.planYearCoverageEnd = Optional.empty();
            } else {
                this.planYearCoverageEnd = Optional.of(planYearCoverageEnd.get());
            }
            return this;
        }

        /**
         * <p>Benefit plan-year coverage end date (YYYY-MM-DD), distinct from this enrollment's coverage_end; null when the plan year is open-ended</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage planYearCoverageEnd(String planYearCoverageEnd) {
            this.planYearCoverageEnd = Optional.ofNullable(planYearCoverageEnd);
            return this;
        }

        /**
         * <p>Benefit plan-year coverage end date (YYYY-MM-DD), distinct from this enrollment's coverage_end; null when the plan year is open-ended</p>
         */
        @java.lang.Override
        @JsonSetter(value = "plan_year_coverage_end", nulls = Nulls.SKIP)
        public _FinalStage planYearCoverageEnd(Optional<String> planYearCoverageEnd) {
            this.planYearCoverageEnd = planYearCoverageEnd;
            return this;
        }

        /**
         * <p>Earliest applicable coverage boundary (YYYY-MM-DD) when coverage was cancelled before its effective start; null unless the enrollment was cancelled</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage cancelledDate(Nullable<String> cancelledDate) {
            if (cancelledDate.isNull()) {
                this.cancelledDate = null;
            } else if (cancelledDate.isEmpty()) {
                this.cancelledDate = Optional.empty();
            } else {
                this.cancelledDate = Optional.of(cancelledDate.get());
            }
            return this;
        }

        /**
         * <p>Earliest applicable coverage boundary (YYYY-MM-DD) when coverage was cancelled before its effective start; null unless the enrollment was cancelled</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage cancelledDate(String cancelledDate) {
            this.cancelledDate = Optional.ofNullable(cancelledDate);
            return this;
        }

        /**
         * <p>Earliest applicable coverage boundary (YYYY-MM-DD) when coverage was cancelled before its effective start; null unless the enrollment was cancelled</p>
         */
        @java.lang.Override
        @JsonSetter(value = "cancelled_date", nulls = Nulls.SKIP)
        public _FinalStage cancelledDate(Optional<String> cancelledDate) {
            this.cancelledDate = cancelledDate;
            return this;
        }

        /**
         * <p>Coverage window end date (YYYY-MM-DD); null while coverage is open-ended</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage coverageEnd(Nullable<String> coverageEnd) {
            if (coverageEnd.isNull()) {
                this.coverageEnd = null;
            } else if (coverageEnd.isEmpty()) {
                this.coverageEnd = Optional.empty();
            } else {
                this.coverageEnd = Optional.of(coverageEnd.get());
            }
            return this;
        }

        /**
         * <p>Coverage window end date (YYYY-MM-DD); null while coverage is open-ended</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage coverageEnd(String coverageEnd) {
            this.coverageEnd = Optional.ofNullable(coverageEnd);
            return this;
        }

        /**
         * <p>Coverage window end date (YYYY-MM-DD); null while coverage is open-ended</p>
         */
        @java.lang.Override
        @JsonSetter(value = "coverage_end", nulls = Nulls.SKIP)
        public _FinalStage coverageEnd(Optional<String> coverageEnd) {
            this.coverageEnd = coverageEnd;
            return this;
        }

        /**
         * <p>Coverage window start date (YYYY-MM-DD)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage coverageStart(Nullable<String> coverageStart) {
            if (coverageStart.isNull()) {
                this.coverageStart = null;
            } else if (coverageStart.isEmpty()) {
                this.coverageStart = Optional.empty();
            } else {
                this.coverageStart = Optional.of(coverageStart.get());
            }
            return this;
        }

        /**
         * <p>Coverage window start date (YYYY-MM-DD)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage coverageStart(String coverageStart) {
            this.coverageStart = Optional.ofNullable(coverageStart);
            return this;
        }

        /**
         * <p>Coverage window start date (YYYY-MM-DD)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "coverage_start", nulls = Nulls.SKIP)
        public _FinalStage coverageStart(Optional<String> coverageStart) {
            this.coverageStart = coverageStart;
            return this;
        }

        /**
         * <p>Total monthly plan premium in cents; null unless the row is an election</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage premiumInCents(Nullable<Integer> premiumInCents) {
            if (premiumInCents.isNull()) {
                this.premiumInCents = null;
            } else if (premiumInCents.isEmpty()) {
                this.premiumInCents = Optional.empty();
            } else {
                this.premiumInCents = Optional.of(premiumInCents.get());
            }
            return this;
        }

        /**
         * <p>Total monthly plan premium in cents; null unless the row is an election</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage premiumInCents(Integer premiumInCents) {
            this.premiumInCents = Optional.ofNullable(premiumInCents);
            return this;
        }

        /**
         * <p>Total monthly plan premium in cents; null unless the row is an election</p>
         */
        @java.lang.Override
        @JsonSetter(value = "premium_in_cents", nulls = Nulls.SKIP)
        public _FinalStage premiumInCents(Optional<Integer> premiumInCents) {
            this.premiumInCents = premiumInCents;
            return this;
        }

        /**
         * <p>Employer monthly contribution in cents; null unless the row is an election</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage employerContributionInCents(Nullable<Integer> employerContributionInCents) {
            if (employerContributionInCents.isNull()) {
                this.employerContributionInCents = null;
            } else if (employerContributionInCents.isEmpty()) {
                this.employerContributionInCents = Optional.empty();
            } else {
                this.employerContributionInCents = Optional.of(employerContributionInCents.get());
            }
            return this;
        }

        /**
         * <p>Employer monthly contribution in cents; null unless the row is an election</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage employerContributionInCents(Integer employerContributionInCents) {
            this.employerContributionInCents = Optional.ofNullable(employerContributionInCents);
            return this;
        }

        /**
         * <p>Employer monthly contribution in cents; null unless the row is an election</p>
         */
        @java.lang.Override
        @JsonSetter(value = "employer_contribution_in_cents", nulls = Nulls.SKIP)
        public _FinalStage employerContributionInCents(Optional<Integer> employerContributionInCents) {
            this.employerContributionInCents = employerContributionInCents;
            return this;
        }

        /**
         * <p>Employee monthly payroll deduction in cents; null unless the row is an election</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage employeeDeductionInCents(Nullable<Integer> employeeDeductionInCents) {
            if (employeeDeductionInCents.isNull()) {
                this.employeeDeductionInCents = null;
            } else if (employeeDeductionInCents.isEmpty()) {
                this.employeeDeductionInCents = Optional.empty();
            } else {
                this.employeeDeductionInCents = Optional.of(employeeDeductionInCents.get());
            }
            return this;
        }

        /**
         * <p>Employee monthly payroll deduction in cents; null unless the row is an election</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage employeeDeductionInCents(Integer employeeDeductionInCents) {
            this.employeeDeductionInCents = Optional.ofNullable(employeeDeductionInCents);
            return this;
        }

        /**
         * <p>Employee monthly payroll deduction in cents; null unless the row is an election</p>
         */
        @java.lang.Override
        @JsonSetter(value = "employee_deduction_in_cents", nulls = Nulls.SKIP)
        public _FinalStage employeeDeductionInCents(Optional<Integer> employeeDeductionInCents) {
            this.employeeDeductionInCents = employeeDeductionInCents;
            return this;
        }

        /**
         * <p>Chosen benefit plan tier name (e.g., Employee Only); null unless the row is an election</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage tierName(Nullable<String> tierName) {
            if (tierName.isNull()) {
                this.tierName = null;
            } else if (tierName.isEmpty()) {
                this.tierName = Optional.empty();
            } else {
                this.tierName = Optional.of(tierName.get());
            }
            return this;
        }

        /**
         * <p>Chosen benefit plan tier name (e.g., Employee Only); null unless the row is an election</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage tierName(String tierName) {
            this.tierName = Optional.ofNullable(tierName);
            return this;
        }

        /**
         * <p>Chosen benefit plan tier name (e.g., Employee Only); null unless the row is an election</p>
         */
        @java.lang.Override
        @JsonSetter(value = "tier_name", nulls = Nulls.SKIP)
        public _FinalStage tierName(Optional<String> tierName) {
            this.tierName = tierName;
            return this;
        }

        /**
         * <p>Chosen benefit plan name; null unless the row is an election</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage planName(Nullable<String> planName) {
            if (planName.isNull()) {
                this.planName = null;
            } else if (planName.isEmpty()) {
                this.planName = Optional.empty();
            } else {
                this.planName = Optional.of(planName.get());
            }
            return this;
        }

        /**
         * <p>Chosen benefit plan name; null unless the row is an election</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage planName(String planName) {
            this.planName = Optional.ofNullable(planName);
            return this;
        }

        /**
         * <p>Chosen benefit plan name; null unless the row is an election</p>
         */
        @java.lang.Override
        @JsonSetter(value = "plan_name", nulls = Nulls.SKIP)
        public _FinalStage planName(Optional<String> planName) {
            this.planName = planName;
            return this;
        }

        /**
         * <p>Insurance carrier name; null when no active carrier period is resolvable</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage carrierName(Nullable<String> carrierName) {
            if (carrierName.isNull()) {
                this.carrierName = null;
            } else if (carrierName.isEmpty()) {
                this.carrierName = Optional.empty();
            } else {
                this.carrierName = Optional.of(carrierName.get());
            }
            return this;
        }

        /**
         * <p>Insurance carrier name; null when no active carrier period is resolvable</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage carrierName(String carrierName) {
            this.carrierName = Optional.ofNullable(carrierName);
            return this;
        }

        /**
         * <p>Insurance carrier name; null when no active carrier period is resolvable</p>
         */
        @java.lang.Override
        @JsonSetter(value = "carrier_name", nulls = Nulls.SKIP)
        public _FinalStage carrierName(Optional<String> carrierName) {
            this.carrierName = carrierName;
            return this;
        }

        @java.lang.Override
        public MemberEnrollment build() {
            return new MemberEnrollment(
                    id,
                    employerId,
                    benefitPlanYearId,
                    benefitType,
                    productCode,
                    requiresQleForReissue,
                    productName,
                    employerName,
                    carrierName,
                    planName,
                    tierName,
                    employeeDeductionInCents,
                    employerContributionInCents,
                    premiumInCents,
                    coverageStart,
                    coverageEnd,
                    cancelledDate,
                    planYearCoverageEnd,
                    issuedDate,
                    enrollmentWindowStart,
                    enrollmentWindowEnd,
                    electionStatus,
                    policyStatus,
                    inLastMonthOfCoverage,
                    isWithinEnrollmentWindow,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
