/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MemberQualifyingLifeEvent.Builder.class)
public final class MemberQualifyingLifeEvent {
    private final String id;

    private final QualifyingLifeEventType eventType;

    private final String eventTypeLabel;

    private final Optional<String> otherEvent;

    private final QualifyingLifeEventStatus status;

    private final OffsetDateTime submittedAt;

    private final Map<String, Object> additionalProperties;

    private MemberQualifyingLifeEvent(
            String id,
            QualifyingLifeEventType eventType,
            String eventTypeLabel,
            Optional<String> otherEvent,
            QualifyingLifeEventStatus status,
            OffsetDateTime submittedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.eventType = eventType;
        this.eventTypeLabel = eventTypeLabel;
        this.otherEvent = otherEvent;
        this.status = status;
        this.submittedAt = submittedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Opaque qualifying life event identifier
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The member-submitted qualifying life event type
     * <ul>
     * <li><code>lost_job_based_coverage</code> - Losing job-based health insurance</li>
     * <li><code>aged_off_parent_plan</code> - Aging off a parent's plan at age 26</li>
     * <li><code>lost_medicaid_chip_medicare</code> - Losing Medicaid, CHIP, or Medicare eligibility</li>
     * <li><code>lost_decertified_individual_plan</code> - Losing individual coverage because a plan was decertified</li>
     * <li><code>married</code> - Getting married</li>
     * <li><code>divorced</code> - Getting divorced or legally separated</li>
     * <li><code>had_baby</code> - Having a baby</li>
     * <li><code>adopted_child</code> - Adopting a child</li>
     * <li><code>foster_care_placement</code> - Foster-care placement</li>
     * <li><code>death_of_spouse_or_dependent</code> - Death of a covered spouse or dependent</li>
     * <li><code>court_ordered</code> - Court order to add a dependent</li>
     * <li><code>moved_to_new_coverage_area</code> - Moving to a new ZIP code, county, or state where different plans are available</li>
     * <li><code>moved_to_us</code> - Moving to the U.S. from another country</li>
     * <li><code>moved_to_or_from_school_housing</code> - Moving to or from school housing</li>
     * <li><code>moved_to_or_from_seasonal_work_housing</code> - Moving to or from housing for seasonal work</li>
     * <li><code>became_us_citizen</code> - Becoming a U.S. citizen</li>
     * <li><code>left_incarceration</code> - Leaving incarceration</li>
     * <li><code>gained_tribal_status</code> - Gaining status as a member of a federally recognized tribe or Alaska Native corporation</li>
     * <li><code>started_or_ended_americorps_service</code> - Starting or ending AmeriCorps service</li>
     * <li><code>new_child</code> - New child</li>
     * <li><code>other</code> - Other</li>
     * </ul>
     */
    @JsonProperty("event_type")
    public QualifyingLifeEventType getEventType() {
        return eventType;
    }

    /**
     * @return Human-readable label for event_type
     */
    @JsonProperty("event_type_label")
    public String getEventTypeLabel() {
        return eventTypeLabel;
    }

    /**
     * @return Custom event description when event_type is Other; otherwise normally null
     */
    @JsonIgnore
    public Optional<String> getOtherEvent() {
        if (otherEvent == null) {
            return Optional.empty();
        }
        return otherEvent;
    }

    /**
     * @return Review status of the qualifying life event
     * <ul>
     * <li><code>pending</code> - Pending</li>
     * <li><code>approved</code> - Approved</li>
     * <li><code>denied</code> - Denied</li>
     * </ul>
     */
    @JsonProperty("status")
    public QualifyingLifeEventStatus getStatus() {
        return status;
    }

    /**
     * @return When the member submitted the event
     */
    @JsonProperty("submitted_at")
    public OffsetDateTime getSubmittedAt() {
        return submittedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("other_event")
    private Optional<String> _getOtherEvent() {
        return otherEvent;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MemberQualifyingLifeEvent && equalTo((MemberQualifyingLifeEvent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MemberQualifyingLifeEvent other) {
        return id.equals(other.id)
                && eventType.equals(other.eventType)
                && eventTypeLabel.equals(other.eventTypeLabel)
                && otherEvent.equals(other.otherEvent)
                && status.equals(other.status)
                && submittedAt.equals(other.submittedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id, this.eventType, this.eventTypeLabel, this.otherEvent, this.status, this.submittedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Opaque qualifying life event identifier</p>
         */
        EventTypeStage id(@NotNull String id);

        Builder from(MemberQualifyingLifeEvent other);
    }

    public interface EventTypeStage {
        /**
         * <p>The member-submitted qualifying life event type</p>
         * <ul>
         * <li><code>lost_job_based_coverage</code> - Losing job-based health insurance</li>
         * <li><code>aged_off_parent_plan</code> - Aging off a parent's plan at age 26</li>
         * <li><code>lost_medicaid_chip_medicare</code> - Losing Medicaid, CHIP, or Medicare eligibility</li>
         * <li><code>lost_decertified_individual_plan</code> - Losing individual coverage because a plan was decertified</li>
         * <li><code>married</code> - Getting married</li>
         * <li><code>divorced</code> - Getting divorced or legally separated</li>
         * <li><code>had_baby</code> - Having a baby</li>
         * <li><code>adopted_child</code> - Adopting a child</li>
         * <li><code>foster_care_placement</code> - Foster-care placement</li>
         * <li><code>death_of_spouse_or_dependent</code> - Death of a covered spouse or dependent</li>
         * <li><code>court_ordered</code> - Court order to add a dependent</li>
         * <li><code>moved_to_new_coverage_area</code> - Moving to a new ZIP code, county, or state where different plans are available</li>
         * <li><code>moved_to_us</code> - Moving to the U.S. from another country</li>
         * <li><code>moved_to_or_from_school_housing</code> - Moving to or from school housing</li>
         * <li><code>moved_to_or_from_seasonal_work_housing</code> - Moving to or from housing for seasonal work</li>
         * <li><code>became_us_citizen</code> - Becoming a U.S. citizen</li>
         * <li><code>left_incarceration</code> - Leaving incarceration</li>
         * <li><code>gained_tribal_status</code> - Gaining status as a member of a federally recognized tribe or Alaska Native corporation</li>
         * <li><code>started_or_ended_americorps_service</code> - Starting or ending AmeriCorps service</li>
         * <li><code>new_child</code> - New child</li>
         * <li><code>other</code> - Other</li>
         * </ul>
         */
        EventTypeLabelStage eventType(@NotNull QualifyingLifeEventType eventType);
    }

    public interface EventTypeLabelStage {
        /**
         * <p>Human-readable label for event_type</p>
         */
        StatusStage eventTypeLabel(@NotNull String eventTypeLabel);
    }

    public interface StatusStage {
        /**
         * <p>Review status of the qualifying life event</p>
         * <ul>
         * <li><code>pending</code> - Pending</li>
         * <li><code>approved</code> - Approved</li>
         * <li><code>denied</code> - Denied</li>
         * </ul>
         */
        SubmittedAtStage status(@NotNull QualifyingLifeEventStatus status);
    }

    public interface SubmittedAtStage {
        /**
         * <p>When the member submitted the event</p>
         */
        _FinalStage submittedAt(@NotNull OffsetDateTime submittedAt);
    }

    public interface _FinalStage {
        MemberQualifyingLifeEvent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Custom event description when event_type is Other; otherwise normally null</p>
         */
        _FinalStage otherEvent(Optional<String> otherEvent);

        _FinalStage otherEvent(String otherEvent);

        _FinalStage otherEvent(Nullable<String> otherEvent);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, EventTypeStage, EventTypeLabelStage, StatusStage, SubmittedAtStage, _FinalStage {
        private String id;

        private QualifyingLifeEventType eventType;

        private String eventTypeLabel;

        private QualifyingLifeEventStatus status;

        private OffsetDateTime submittedAt;

        private Optional<String> otherEvent = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MemberQualifyingLifeEvent other) {
            id(other.getId());
            eventType(other.getEventType());
            eventTypeLabel(other.getEventTypeLabel());
            otherEvent(other.getOtherEvent());
            status(other.getStatus());
            submittedAt(other.getSubmittedAt());
            return this;
        }

        /**
         * <p>Opaque qualifying life event identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public EventTypeStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The member-submitted qualifying life event type</p>
         * <ul>
         * <li><code>lost_job_based_coverage</code> - Losing job-based health insurance</li>
         * <li><code>aged_off_parent_plan</code> - Aging off a parent's plan at age 26</li>
         * <li><code>lost_medicaid_chip_medicare</code> - Losing Medicaid, CHIP, or Medicare eligibility</li>
         * <li><code>lost_decertified_individual_plan</code> - Losing individual coverage because a plan was decertified</li>
         * <li><code>married</code> - Getting married</li>
         * <li><code>divorced</code> - Getting divorced or legally separated</li>
         * <li><code>had_baby</code> - Having a baby</li>
         * <li><code>adopted_child</code> - Adopting a child</li>
         * <li><code>foster_care_placement</code> - Foster-care placement</li>
         * <li><code>death_of_spouse_or_dependent</code> - Death of a covered spouse or dependent</li>
         * <li><code>court_ordered</code> - Court order to add a dependent</li>
         * <li><code>moved_to_new_coverage_area</code> - Moving to a new ZIP code, county, or state where different plans are available</li>
         * <li><code>moved_to_us</code> - Moving to the U.S. from another country</li>
         * <li><code>moved_to_or_from_school_housing</code> - Moving to or from school housing</li>
         * <li><code>moved_to_or_from_seasonal_work_housing</code> - Moving to or from housing for seasonal work</li>
         * <li><code>became_us_citizen</code> - Becoming a U.S. citizen</li>
         * <li><code>left_incarceration</code> - Leaving incarceration</li>
         * <li><code>gained_tribal_status</code> - Gaining status as a member of a federally recognized tribe or Alaska Native corporation</li>
         * <li><code>started_or_ended_americorps_service</code> - Starting or ending AmeriCorps service</li>
         * <li><code>new_child</code> - New child</li>
         * <li><code>other</code> - Other</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("event_type")
        public EventTypeLabelStage eventType(@NotNull QualifyingLifeEventType eventType) {
            this.eventType = Objects.requireNonNull(eventType, "eventType must not be null");
            return this;
        }

        /**
         * <p>Human-readable label for event_type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("event_type_label")
        public StatusStage eventTypeLabel(@NotNull String eventTypeLabel) {
            this.eventTypeLabel = Objects.requireNonNull(eventTypeLabel, "eventTypeLabel must not be null");
            return this;
        }

        /**
         * <p>Review status of the qualifying life event</p>
         * <ul>
         * <li><code>pending</code> - Pending</li>
         * <li><code>approved</code> - Approved</li>
         * <li><code>denied</code> - Denied</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public SubmittedAtStage status(@NotNull QualifyingLifeEventStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>When the member submitted the event</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("submitted_at")
        public _FinalStage submittedAt(@NotNull OffsetDateTime submittedAt) {
            this.submittedAt = Objects.requireNonNull(submittedAt, "submittedAt must not be null");
            return this;
        }

        /**
         * <p>Custom event description when event_type is Other; otherwise normally null</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage otherEvent(Nullable<String> otherEvent) {
            if (otherEvent.isNull()) {
                this.otherEvent = null;
            } else if (otherEvent.isEmpty()) {
                this.otherEvent = Optional.empty();
            } else {
                this.otherEvent = Optional.of(otherEvent.get());
            }
            return this;
        }

        /**
         * <p>Custom event description when event_type is Other; otherwise normally null</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage otherEvent(String otherEvent) {
            this.otherEvent = Optional.ofNullable(otherEvent);
            return this;
        }

        /**
         * <p>Custom event description when event_type is Other; otherwise normally null</p>
         */
        @java.lang.Override
        @JsonSetter(value = "other_event", nulls = Nulls.SKIP)
        public _FinalStage otherEvent(Optional<String> otherEvent) {
            this.otherEvent = otherEvent;
            return this;
        }

        @java.lang.Override
        public MemberQualifyingLifeEvent build() {
            return new MemberQualifyingLifeEvent(
                    id, eventType, eventTypeLabel, otherEvent, status, submittedAt, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
