/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MemberListItem.Builder.class)
public final class MemberListItem {
    private final Optional<String> id;

    private final String firstName;

    private final String lastName;

    private final Optional<String> email;

    private final Optional<String> phone;

    private final Optional<MemberAddress> address;

    private final Map<String, Object> additionalProperties;

    private MemberListItem(
            Optional<String> id,
            String firstName,
            String lastName,
            Optional<String> email,
            Optional<String> phone,
            Optional<MemberAddress> address,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.address = address;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique member identifier with 'mbr_' prefix
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return Member's legal first name
     */
    @JsonProperty("first_name")
    public String getFirstName() {
        return firstName;
    }

    /**
     * @return Member's legal last name
     */
    @JsonProperty("last_name")
    public String getLastName() {
        return lastName;
    }

    /**
     * @return Email address
     */
    @JsonIgnore
    public Optional<String> getEmail() {
        if (email == null) {
            return Optional.empty();
        }
        return email;
    }

    /**
     * @return Phone number (10-digit US domestic string)
     */
    @JsonIgnore
    public Optional<String> getPhone() {
        if (phone == null) {
            return Optional.empty();
        }
        return phone;
    }

    /**
     * @return Member's residential address
     */
    @JsonIgnore
    public Optional<MemberAddress> getAddress() {
        if (address == null) {
            return Optional.empty();
        }
        return address;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("email")
    private Optional<String> _getEmail() {
        return email;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("phone")
    private Optional<String> _getPhone() {
        return phone;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("address")
    private Optional<MemberAddress> _getAddress() {
        return address;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MemberListItem && equalTo((MemberListItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MemberListItem other) {
        return id.equals(other.id)
                && firstName.equals(other.firstName)
                && lastName.equals(other.lastName)
                && email.equals(other.email)
                && phone.equals(other.phone)
                && address.equals(other.address);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.firstName, this.lastName, this.email, this.phone, this.address);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FirstNameStage builder() {
        return new Builder();
    }

    public interface FirstNameStage {
        /**
         * <p>Member's legal first name</p>
         */
        LastNameStage firstName(@NotNull String firstName);

        Builder from(MemberListItem other);
    }

    public interface LastNameStage {
        /**
         * <p>Member's legal last name</p>
         */
        _FinalStage lastName(@NotNull String lastName);
    }

    public interface _FinalStage {
        MemberListItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Unique member identifier with 'mbr_' prefix</p>
         */
        _FinalStage id(Optional<String> id);

        _FinalStage id(String id);

        /**
         * <p>Email address</p>
         */
        _FinalStage email(Optional<String> email);

        _FinalStage email(String email);

        _FinalStage email(Nullable<String> email);

        /**
         * <p>Phone number (10-digit US domestic string)</p>
         */
        _FinalStage phone(Optional<String> phone);

        _FinalStage phone(String phone);

        _FinalStage phone(Nullable<String> phone);

        /**
         * <p>Member's residential address</p>
         */
        _FinalStage address(Optional<MemberAddress> address);

        _FinalStage address(MemberAddress address);

        _FinalStage address(Nullable<MemberAddress> address);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FirstNameStage, LastNameStage, _FinalStage {
        private String firstName;

        private String lastName;

        private Optional<MemberAddress> address = Optional.empty();

        private Optional<String> phone = Optional.empty();

        private Optional<String> email = Optional.empty();

        private Optional<String> id = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MemberListItem other) {
            id(other.getId());
            firstName(other.getFirstName());
            lastName(other.getLastName());
            email(other.getEmail());
            phone(other.getPhone());
            address(other.getAddress());
            return this;
        }

        /**
         * <p>Member's legal first name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("first_name")
        public LastNameStage firstName(@NotNull String firstName) {
            this.firstName = Objects.requireNonNull(firstName, "firstName must not be null");
            return this;
        }

        /**
         * <p>Member's legal last name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("last_name")
        public _FinalStage lastName(@NotNull String lastName) {
            this.lastName = Objects.requireNonNull(lastName, "lastName must not be null");
            return this;
        }

        /**
         * <p>Member's residential address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage address(Nullable<MemberAddress> address) {
            if (address.isNull()) {
                this.address = null;
            } else if (address.isEmpty()) {
                this.address = Optional.empty();
            } else {
                this.address = Optional.of(address.get());
            }
            return this;
        }

        /**
         * <p>Member's residential address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage address(MemberAddress address) {
            this.address = Optional.ofNullable(address);
            return this;
        }

        /**
         * <p>Member's residential address</p>
         */
        @java.lang.Override
        @JsonSetter(value = "address", nulls = Nulls.SKIP)
        public _FinalStage address(Optional<MemberAddress> address) {
            this.address = address;
            return this;
        }

        /**
         * <p>Phone number (10-digit US domestic string)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phone(Nullable<String> phone) {
            if (phone.isNull()) {
                this.phone = null;
            } else if (phone.isEmpty()) {
                this.phone = Optional.empty();
            } else {
                this.phone = Optional.of(phone.get());
            }
            return this;
        }

        /**
         * <p>Phone number (10-digit US domestic string)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phone(String phone) {
            this.phone = Optional.ofNullable(phone);
            return this;
        }

        /**
         * <p>Phone number (10-digit US domestic string)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "phone", nulls = Nulls.SKIP)
        public _FinalStage phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }

        /**
         * <p>Email address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(Nullable<String> email) {
            if (email.isNull()) {
                this.email = null;
            } else if (email.isEmpty()) {
                this.email = Optional.empty();
            } else {
                this.email = Optional.of(email.get());
            }
            return this;
        }

        /**
         * <p>Email address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>Email address</p>
         */
        @java.lang.Override
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public _FinalStage email(Optional<String> email) {
            this.email = email;
            return this;
        }

        /**
         * <p>Unique member identifier with 'mbr_' prefix</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>Unique member identifier with 'mbr_' prefix</p>
         */
        @java.lang.Override
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public _FinalStage id(Optional<String> id) {
            this.id = id;
            return this;
        }

        @java.lang.Override
        public MemberListItem build() {
            return new MemberListItem(id, firstName, lastName, email, phone, address, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
