/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class NameSuffix {
    public static final NameSuffix III = new NameSuffix(Value.III, "III");

    public static final NameSuffix I = new NameSuffix(Value.I, "I");

    public static final NameSuffix SR = new NameSuffix(Value.SR, "Sr");

    public static final NameSuffix JR = new NameSuffix(Value.JR, "Jr");

    public static final NameSuffix II = new NameSuffix(Value.II, "II");

    public static final NameSuffix IV = new NameSuffix(Value.IV, "IV");

    public static final NameSuffix V = new NameSuffix(Value.V, "V");

    private final Value value;

    private final String string;

    NameSuffix(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof NameSuffix && this.string.equals(((NameSuffix) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case III:
                return visitor.visitIii();
            case I:
                return visitor.visitI();
            case SR:
                return visitor.visitSr();
            case JR:
                return visitor.visitJr();
            case II:
                return visitor.visitIi();
            case IV:
                return visitor.visitIv();
            case V:
                return visitor.visitV();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static NameSuffix valueOf(String value) {
        switch (value) {
            case "III":
                return III;
            case "I":
                return I;
            case "Sr":
                return SR;
            case "Jr":
                return JR;
            case "II":
                return II;
            case "IV":
                return IV;
            case "V":
                return V;
            default:
                return new NameSuffix(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SR,

        JR,

        I,

        II,

        III,

        IV,

        V,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSr();

        T visitJr();

        T visitI();

        T visitIi();

        T visitIii();

        T visitIv();

        T visitV();

        T visitUnknown(String unknownType);
    }
}
