/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Organization.Builder.class)
public final class Organization {
    private final String id;

    private final String name;

    private final Optional<OrganizationType> type;

    private final Optional<String> idpOrgId;

    private final Optional<IdpProvider> idpProvider;

    private final boolean superIn;

    private final Map<String, Object> additionalProperties;

    private Organization(
            String id,
            String name,
            Optional<OrganizationType> type,
            Optional<String> idpOrgId,
            Optional<IdpProvider> idpProvider,
            boolean superIn,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.idpOrgId = idpOrgId;
        this.idpProvider = idpProvider;
        this.superIn = superIn;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Prefixed organization identifier (<code>org_&lt;base64-encoded-uuid&gt;</code>).
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Human-readable organization name.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Partner type (e.g. BROKERAGE, TPA).
     * <ul>
     * <li><code>BROKERAGE</code> - Brokerage</li>
     * <li><code>TPA</code> - TPA</li>
     * <li><code>GENERAL_AGENT</code> - General Agent</li>
     * <li><code>CHANNEL_PARTNER</code> - Channel Partner</li>
     * <li><code>CONSULTING_FIRM</code> - Consulting Firm</li>
     * <li><code>API_PLATFORM</code> - API Platform</li>
     * </ul>
     */
    @JsonIgnore
    public Optional<OrganizationType> getType() {
        if (type == null) {
            return Optional.empty();
        }
        return type;
    }

    /**
     * @return IdP-issued tenant id (WorkOS org id).
     */
    @JsonIgnore
    public Optional<String> getIdpOrgId() {
        if (idpOrgId == null) {
            return Optional.empty();
        }
        return idpOrgId;
    }

    /**
     * @return IdP that minted idp_org_id (e.g. 'workos').
     * <ul>
     * <li><code>workos</code> - WorkOS</li>
     * <li><code>vitable</code> - Vitable</li>
     * </ul>
     */
    @JsonIgnore
    public Optional<IdpProvider> getIdpProvider() {
        if (idpProvider == null) {
            return Optional.empty();
        }
        return idpProvider;
    }

    /**
     * @return Whether this organization reads across every organization.
     */
    @JsonProperty("super_in")
    public boolean getSuperIn() {
        return superIn;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("type")
    private Optional<OrganizationType> _getType() {
        return type;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("idp_org_id")
    private Optional<String> _getIdpOrgId() {
        return idpOrgId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("idp_provider")
    private Optional<IdpProvider> _getIdpProvider() {
        return idpProvider;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Organization && equalTo((Organization) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Organization other) {
        return id.equals(other.id)
                && name.equals(other.name)
                && type.equals(other.type)
                && idpOrgId.equals(other.idpOrgId)
                && idpProvider.equals(other.idpProvider)
                && superIn == other.superIn;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.name, this.type, this.idpOrgId, this.idpProvider, this.superIn);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Prefixed organization identifier (<code>org_&lt;base64-encoded-uuid&gt;</code>).</p>
         */
        NameStage id(@NotNull String id);

        Builder from(Organization other);
    }

    public interface NameStage {
        /**
         * <p>Human-readable organization name.</p>
         */
        SuperInStage name(@NotNull String name);
    }

    public interface SuperInStage {
        /**
         * <p>Whether this organization reads across every organization.</p>
         */
        _FinalStage superIn(boolean superIn);
    }

    public interface _FinalStage {
        Organization build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Partner type (e.g. BROKERAGE, TPA).</p>
         * <ul>
         * <li><code>BROKERAGE</code> - Brokerage</li>
         * <li><code>TPA</code> - TPA</li>
         * <li><code>GENERAL_AGENT</code> - General Agent</li>
         * <li><code>CHANNEL_PARTNER</code> - Channel Partner</li>
         * <li><code>CONSULTING_FIRM</code> - Consulting Firm</li>
         * <li><code>API_PLATFORM</code> - API Platform</li>
         * </ul>
         */
        _FinalStage type(Optional<OrganizationType> type);

        _FinalStage type(OrganizationType type);

        _FinalStage type(Nullable<OrganizationType> type);

        /**
         * <p>IdP-issued tenant id (WorkOS org id).</p>
         */
        _FinalStage idpOrgId(Optional<String> idpOrgId);

        _FinalStage idpOrgId(String idpOrgId);

        _FinalStage idpOrgId(Nullable<String> idpOrgId);

        /**
         * <p>IdP that minted idp_org_id (e.g. 'workos').</p>
         * <ul>
         * <li><code>workos</code> - WorkOS</li>
         * <li><code>vitable</code> - Vitable</li>
         * </ul>
         */
        _FinalStage idpProvider(Optional<IdpProvider> idpProvider);

        _FinalStage idpProvider(IdpProvider idpProvider);

        _FinalStage idpProvider(Nullable<IdpProvider> idpProvider);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, NameStage, SuperInStage, _FinalStage {
        private String id;

        private String name;

        private boolean superIn;

        private Optional<IdpProvider> idpProvider = Optional.empty();

        private Optional<String> idpOrgId = Optional.empty();

        private Optional<OrganizationType> type = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Organization other) {
            id(other.getId());
            name(other.getName());
            type(other.getType());
            idpOrgId(other.getIdpOrgId());
            idpProvider(other.getIdpProvider());
            superIn(other.getSuperIn());
            return this;
        }

        /**
         * <p>Prefixed organization identifier (<code>org_&lt;base64-encoded-uuid&gt;</code>).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Human-readable organization name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public SuperInStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Whether this organization reads across every organization.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("super_in")
        public _FinalStage superIn(boolean superIn) {
            this.superIn = superIn;
            return this;
        }

        /**
         * <p>IdP that minted idp_org_id (e.g. 'workos').</p>
         * <ul>
         * <li><code>workos</code> - WorkOS</li>
         * <li><code>vitable</code> - Vitable</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage idpProvider(Nullable<IdpProvider> idpProvider) {
            if (idpProvider.isNull()) {
                this.idpProvider = null;
            } else if (idpProvider.isEmpty()) {
                this.idpProvider = Optional.empty();
            } else {
                this.idpProvider = Optional.of(idpProvider.get());
            }
            return this;
        }

        /**
         * <p>IdP that minted idp_org_id (e.g. 'workos').</p>
         * <ul>
         * <li><code>workos</code> - WorkOS</li>
         * <li><code>vitable</code> - Vitable</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage idpProvider(IdpProvider idpProvider) {
            this.idpProvider = Optional.ofNullable(idpProvider);
            return this;
        }

        /**
         * <p>IdP that minted idp_org_id (e.g. 'workos').</p>
         * <ul>
         * <li><code>workos</code> - WorkOS</li>
         * <li><code>vitable</code> - Vitable</li>
         * </ul>
         */
        @java.lang.Override
        @JsonSetter(value = "idp_provider", nulls = Nulls.SKIP)
        public _FinalStage idpProvider(Optional<IdpProvider> idpProvider) {
            this.idpProvider = idpProvider;
            return this;
        }

        /**
         * <p>IdP-issued tenant id (WorkOS org id).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage idpOrgId(Nullable<String> idpOrgId) {
            if (idpOrgId.isNull()) {
                this.idpOrgId = null;
            } else if (idpOrgId.isEmpty()) {
                this.idpOrgId = Optional.empty();
            } else {
                this.idpOrgId = Optional.of(idpOrgId.get());
            }
            return this;
        }

        /**
         * <p>IdP-issued tenant id (WorkOS org id).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage idpOrgId(String idpOrgId) {
            this.idpOrgId = Optional.ofNullable(idpOrgId);
            return this;
        }

        /**
         * <p>IdP-issued tenant id (WorkOS org id).</p>
         */
        @java.lang.Override
        @JsonSetter(value = "idp_org_id", nulls = Nulls.SKIP)
        public _FinalStage idpOrgId(Optional<String> idpOrgId) {
            this.idpOrgId = idpOrgId;
            return this;
        }

        /**
         * <p>Partner type (e.g. BROKERAGE, TPA).</p>
         * <ul>
         * <li><code>BROKERAGE</code> - Brokerage</li>
         * <li><code>TPA</code> - TPA</li>
         * <li><code>GENERAL_AGENT</code> - General Agent</li>
         * <li><code>CHANNEL_PARTNER</code> - Channel Partner</li>
         * <li><code>CONSULTING_FIRM</code> - Consulting Firm</li>
         * <li><code>API_PLATFORM</code> - API Platform</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage type(Nullable<OrganizationType> type) {
            if (type.isNull()) {
                this.type = null;
            } else if (type.isEmpty()) {
                this.type = Optional.empty();
            } else {
                this.type = Optional.of(type.get());
            }
            return this;
        }

        /**
         * <p>Partner type (e.g. BROKERAGE, TPA).</p>
         * <ul>
         * <li><code>BROKERAGE</code> - Brokerage</li>
         * <li><code>TPA</code> - TPA</li>
         * <li><code>GENERAL_AGENT</code> - General Agent</li>
         * <li><code>CHANNEL_PARTNER</code> - Channel Partner</li>
         * <li><code>CONSULTING_FIRM</code> - Consulting Firm</li>
         * <li><code>API_PLATFORM</code> - API Platform</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage type(OrganizationType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * <p>Partner type (e.g. BROKERAGE, TPA).</p>
         * <ul>
         * <li><code>BROKERAGE</code> - Brokerage</li>
         * <li><code>TPA</code> - TPA</li>
         * <li><code>GENERAL_AGENT</code> - General Agent</li>
         * <li><code>CHANNEL_PARTNER</code> - Channel Partner</li>
         * <li><code>CONSULTING_FIRM</code> - Consulting Firm</li>
         * <li><code>API_PLATFORM</code> - API Platform</li>
         * </ul>
         */
        @java.lang.Override
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public _FinalStage type(Optional<OrganizationType> type) {
            this.type = type;
            return this;
        }

        @java.lang.Override
        public Organization build() {
            return new Organization(id, name, type, idpOrgId, idpProvider, superIn, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
