/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrganizationEmployer.Builder.class)
public final class OrganizationEmployer {
    private final String employerId;

    private final Optional<String> organizationId;

    private final Optional<String> referenceId;

    private final String name;

    private final Optional<String> legalName;

    private final Optional<String> ein;

    private final Optional<String> email;

    private final Optional<String> phoneNumber;

    private final boolean active;

    private final Address address;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final EnrollmentRateSummary enrollmentRateSummary;

    private final List<String> benefitFamilies;

    private final Optional<EmployerHrisStatus> hrisStatus;

    private final EmployerBenefitLifecycleStage benefitLifecycleStage;

    private final Map<String, Object> additionalProperties;

    private OrganizationEmployer(
            String employerId,
            Optional<String> organizationId,
            Optional<String> referenceId,
            String name,
            Optional<String> legalName,
            Optional<String> ein,
            Optional<String> email,
            Optional<String> phoneNumber,
            boolean active,
            Address address,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            EnrollmentRateSummary enrollmentRateSummary,
            List<String> benefitFamilies,
            Optional<EmployerHrisStatus> hrisStatus,
            EmployerBenefitLifecycleStage benefitLifecycleStage,
            Map<String, Object> additionalProperties) {
        this.employerId = employerId;
        this.organizationId = organizationId;
        this.referenceId = referenceId;
        this.name = name;
        this.legalName = legalName;
        this.ein = ein;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.active = active;
        this.address = address;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.enrollmentRateSummary = enrollmentRateSummary;
        this.benefitFamilies = benefitFamilies;
        this.hrisStatus = hrisStatus;
        this.benefitLifecycleStage = benefitLifecycleStage;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Prefixed employer identifier (<code>empr_&lt;base64-encoded-uuid&gt;</code>).
     */
    @JsonProperty("employer_id")
    public String getEmployerId() {
        return employerId;
    }

    /**
     * @return ID of the parent organization (<code>org_*</code>), or null when unknown.
     */
    @JsonIgnore
    public Optional<String> getOrganizationId() {
        if (organizationId == null) {
            return Optional.empty();
        }
        return organizationId;
    }

    /**
     * @return The organization's own reference id for this employer, or null when none was assigned.
     */
    @JsonIgnore
    public Optional<String> getReferenceId() {
        if (referenceId == null) {
            return Optional.empty();
        }
        return referenceId;
    }

    /**
     * @return Employer name.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Legal business name for compliance and tax purposes.
     */
    @JsonIgnore
    public Optional<String> getLegalName() {
        if (legalName == null) {
            return Optional.empty();
        }
        return legalName;
    }

    /**
     * @return Employer Identification Number (masked in responses).
     */
    @JsonIgnore
    public Optional<String> getEin() {
        if (ein == null) {
            return Optional.empty();
        }
        return ein;
    }

    /**
     * @return Email address for billing and communications.
     */
    @JsonIgnore
    public Optional<String> getEmail() {
        if (email == null) {
            return Optional.empty();
        }
        return email;
    }

    /**
     * @return Employer phone number.
     */
    @JsonIgnore
    public Optional<String> getPhoneNumber() {
        if (phoneNumber == null) {
            return Optional.empty();
        }
        return phoneNumber;
    }

    /**
     * @return Whether the employer is currently active in the system.
     */
    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    /**
     * @return Employer's primary address.
     */
    @JsonProperty("address")
    public Address getAddress() {
        return address;
    }

    /**
     * @return Timestamp when the employer was created.
     */
    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Timestamp when the employer was last updated.
     */
    @JsonProperty("updated_at")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * @return Enrolled/eligible employees roll-up.
     */
    @JsonProperty("enrollment_rate_summary")
    public EnrollmentRateSummary getEnrollmentRateSummary() {
        return enrollmentRateSummary;
    }

    /**
     * @return Distinct benefit-family tags across the employer's active benefits (e.g. <code>MEC</code>, <code>ICHRA</code>, <code>VPC</code>).
     */
    @JsonProperty("benefit_families")
    public List<String> getBenefitFamilies() {
        return benefitFamilies;
    }

    /**
     * @return HRIS connection, or null when the employer has none.
     */
    @JsonIgnore
    public Optional<EmployerHrisStatus> getHrisStatus() {
        if (hrisStatus == null) {
            return Optional.empty();
        }
        return hrisStatus;
    }

    /**
     * @return Where the employer currently sits in the benefits setup lifecycle.
     */
    @JsonProperty("benefit_lifecycle_stage")
    public EmployerBenefitLifecycleStage getBenefitLifecycleStage() {
        return benefitLifecycleStage;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("organization_id")
    private Optional<String> _getOrganizationId() {
        return organizationId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("reference_id")
    private Optional<String> _getReferenceId() {
        return referenceId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("legal_name")
    private Optional<String> _getLegalName() {
        return legalName;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("ein")
    private Optional<String> _getEin() {
        return ein;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("email")
    private Optional<String> _getEmail() {
        return email;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("phone_number")
    private Optional<String> _getPhoneNumber() {
        return phoneNumber;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("hris_status")
    private Optional<EmployerHrisStatus> _getHrisStatus() {
        return hrisStatus;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrganizationEmployer && equalTo((OrganizationEmployer) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrganizationEmployer other) {
        return employerId.equals(other.employerId)
                && organizationId.equals(other.organizationId)
                && referenceId.equals(other.referenceId)
                && name.equals(other.name)
                && legalName.equals(other.legalName)
                && ein.equals(other.ein)
                && email.equals(other.email)
                && phoneNumber.equals(other.phoneNumber)
                && active == other.active
                && address.equals(other.address)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt)
                && enrollmentRateSummary.equals(other.enrollmentRateSummary)
                && benefitFamilies.equals(other.benefitFamilies)
                && hrisStatus.equals(other.hrisStatus)
                && benefitLifecycleStage.equals(other.benefitLifecycleStage);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.employerId,
                this.organizationId,
                this.referenceId,
                this.name,
                this.legalName,
                this.ein,
                this.email,
                this.phoneNumber,
                this.active,
                this.address,
                this.createdAt,
                this.updatedAt,
                this.enrollmentRateSummary,
                this.benefitFamilies,
                this.hrisStatus,
                this.benefitLifecycleStage);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EmployerIdStage builder() {
        return new Builder();
    }

    public interface EmployerIdStage {
        /**
         * <p>Prefixed employer identifier (<code>empr_&lt;base64-encoded-uuid&gt;</code>).</p>
         */
        NameStage employerId(@NotNull String employerId);

        Builder from(OrganizationEmployer other);
    }

    public interface NameStage {
        /**
         * <p>Employer name.</p>
         */
        ActiveStage name(@NotNull String name);
    }

    public interface ActiveStage {
        /**
         * <p>Whether the employer is currently active in the system.</p>
         */
        AddressStage active(boolean active);
    }

    public interface AddressStage {
        /**
         * <p>Employer's primary address.</p>
         */
        CreatedAtStage address(@NotNull Address address);
    }

    public interface CreatedAtStage {
        /**
         * <p>Timestamp when the employer was created.</p>
         */
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        /**
         * <p>Timestamp when the employer was last updated.</p>
         */
        EnrollmentRateSummaryStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface EnrollmentRateSummaryStage {
        /**
         * <p>Enrolled/eligible employees roll-up.</p>
         */
        BenefitLifecycleStageStage enrollmentRateSummary(@NotNull EnrollmentRateSummary enrollmentRateSummary);
    }

    public interface BenefitLifecycleStageStage {
        /**
         * <p>Where the employer currently sits in the benefits setup lifecycle.</p>
         */
        _FinalStage benefitLifecycleStage(@NotNull EmployerBenefitLifecycleStage benefitLifecycleStage);
    }

    public interface _FinalStage {
        OrganizationEmployer build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>ID of the parent organization (<code>org_*</code>), or null when unknown.</p>
         */
        _FinalStage organizationId(Optional<String> organizationId);

        _FinalStage organizationId(String organizationId);

        _FinalStage organizationId(Nullable<String> organizationId);

        /**
         * <p>The organization's own reference id for this employer, or null when none was assigned.</p>
         */
        _FinalStage referenceId(Optional<String> referenceId);

        _FinalStage referenceId(String referenceId);

        _FinalStage referenceId(Nullable<String> referenceId);

        /**
         * <p>Legal business name for compliance and tax purposes.</p>
         */
        _FinalStage legalName(Optional<String> legalName);

        _FinalStage legalName(String legalName);

        _FinalStage legalName(Nullable<String> legalName);

        /**
         * <p>Employer Identification Number (masked in responses).</p>
         */
        _FinalStage ein(Optional<String> ein);

        _FinalStage ein(String ein);

        _FinalStage ein(Nullable<String> ein);

        /**
         * <p>Email address for billing and communications.</p>
         */
        _FinalStage email(Optional<String> email);

        _FinalStage email(String email);

        _FinalStage email(Nullable<String> email);

        /**
         * <p>Employer phone number.</p>
         */
        _FinalStage phoneNumber(Optional<String> phoneNumber);

        _FinalStage phoneNumber(String phoneNumber);

        _FinalStage phoneNumber(Nullable<String> phoneNumber);

        /**
         * <p>Distinct benefit-family tags across the employer's active benefits (e.g. <code>MEC</code>, <code>ICHRA</code>, <code>VPC</code>).</p>
         */
        _FinalStage benefitFamilies(List<String> benefitFamilies);

        _FinalStage addBenefitFamilies(String benefitFamilies);

        _FinalStage addAllBenefitFamilies(List<String> benefitFamilies);

        /**
         * <p>HRIS connection, or null when the employer has none.</p>
         */
        _FinalStage hrisStatus(Optional<EmployerHrisStatus> hrisStatus);

        _FinalStage hrisStatus(EmployerHrisStatus hrisStatus);

        _FinalStage hrisStatus(Nullable<EmployerHrisStatus> hrisStatus);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements EmployerIdStage,
                    NameStage,
                    ActiveStage,
                    AddressStage,
                    CreatedAtStage,
                    UpdatedAtStage,
                    EnrollmentRateSummaryStage,
                    BenefitLifecycleStageStage,
                    _FinalStage {
        private String employerId;

        private String name;

        private boolean active;

        private Address address;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private EnrollmentRateSummary enrollmentRateSummary;

        private EmployerBenefitLifecycleStage benefitLifecycleStage;

        private Optional<EmployerHrisStatus> hrisStatus = Optional.empty();

        private List<String> benefitFamilies = new ArrayList<>();

        private Optional<String> phoneNumber = Optional.empty();

        private Optional<String> email = Optional.empty();

        private Optional<String> ein = Optional.empty();

        private Optional<String> legalName = Optional.empty();

        private Optional<String> referenceId = Optional.empty();

        private Optional<String> organizationId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OrganizationEmployer other) {
            employerId(other.getEmployerId());
            organizationId(other.getOrganizationId());
            referenceId(other.getReferenceId());
            name(other.getName());
            legalName(other.getLegalName());
            ein(other.getEin());
            email(other.getEmail());
            phoneNumber(other.getPhoneNumber());
            active(other.getActive());
            address(other.getAddress());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            enrollmentRateSummary(other.getEnrollmentRateSummary());
            benefitFamilies(other.getBenefitFamilies());
            hrisStatus(other.getHrisStatus());
            benefitLifecycleStage(other.getBenefitLifecycleStage());
            return this;
        }

        /**
         * <p>Prefixed employer identifier (<code>empr_&lt;base64-encoded-uuid&gt;</code>).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("employer_id")
        public NameStage employerId(@NotNull String employerId) {
            this.employerId = Objects.requireNonNull(employerId, "employerId must not be null");
            return this;
        }

        /**
         * <p>Employer name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public ActiveStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Whether the employer is currently active in the system.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("active")
        public AddressStage active(boolean active) {
            this.active = active;
            return this;
        }

        /**
         * <p>Employer's primary address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("address")
        public CreatedAtStage address(@NotNull Address address) {
            this.address = Objects.requireNonNull(address, "address must not be null");
            return this;
        }

        /**
         * <p>Timestamp when the employer was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Timestamp when the employer was last updated.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updated_at")
        public EnrollmentRateSummaryStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>Enrolled/eligible employees roll-up.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("enrollment_rate_summary")
        public BenefitLifecycleStageStage enrollmentRateSummary(@NotNull EnrollmentRateSummary enrollmentRateSummary) {
            this.enrollmentRateSummary =
                    Objects.requireNonNull(enrollmentRateSummary, "enrollmentRateSummary must not be null");
            return this;
        }

        /**
         * <p>Where the employer currently sits in the benefits setup lifecycle.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("benefit_lifecycle_stage")
        public _FinalStage benefitLifecycleStage(@NotNull EmployerBenefitLifecycleStage benefitLifecycleStage) {
            this.benefitLifecycleStage =
                    Objects.requireNonNull(benefitLifecycleStage, "benefitLifecycleStage must not be null");
            return this;
        }

        /**
         * <p>HRIS connection, or null when the employer has none.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage hrisStatus(Nullable<EmployerHrisStatus> hrisStatus) {
            if (hrisStatus.isNull()) {
                this.hrisStatus = null;
            } else if (hrisStatus.isEmpty()) {
                this.hrisStatus = Optional.empty();
            } else {
                this.hrisStatus = Optional.of(hrisStatus.get());
            }
            return this;
        }

        /**
         * <p>HRIS connection, or null when the employer has none.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage hrisStatus(EmployerHrisStatus hrisStatus) {
            this.hrisStatus = Optional.ofNullable(hrisStatus);
            return this;
        }

        /**
         * <p>HRIS connection, or null when the employer has none.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "hris_status", nulls = Nulls.SKIP)
        public _FinalStage hrisStatus(Optional<EmployerHrisStatus> hrisStatus) {
            this.hrisStatus = hrisStatus;
            return this;
        }

        /**
         * <p>Distinct benefit-family tags across the employer's active benefits (e.g. <code>MEC</code>, <code>ICHRA</code>, <code>VPC</code>).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllBenefitFamilies(List<String> benefitFamilies) {
            if (benefitFamilies != null) {
                this.benefitFamilies.addAll(benefitFamilies);
            }
            return this;
        }

        /**
         * <p>Distinct benefit-family tags across the employer's active benefits (e.g. <code>MEC</code>, <code>ICHRA</code>, <code>VPC</code>).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addBenefitFamilies(String benefitFamilies) {
            this.benefitFamilies.add(benefitFamilies);
            return this;
        }

        /**
         * <p>Distinct benefit-family tags across the employer's active benefits (e.g. <code>MEC</code>, <code>ICHRA</code>, <code>VPC</code>).</p>
         */
        @java.lang.Override
        @JsonSetter(value = "benefit_families", nulls = Nulls.SKIP)
        public _FinalStage benefitFamilies(List<String> benefitFamilies) {
            this.benefitFamilies.clear();
            if (benefitFamilies != null) {
                this.benefitFamilies.addAll(benefitFamilies);
            }
            return this;
        }

        /**
         * <p>Employer phone number.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phoneNumber(Nullable<String> phoneNumber) {
            if (phoneNumber.isNull()) {
                this.phoneNumber = null;
            } else if (phoneNumber.isEmpty()) {
                this.phoneNumber = Optional.empty();
            } else {
                this.phoneNumber = Optional.of(phoneNumber.get());
            }
            return this;
        }

        /**
         * <p>Employer phone number.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phoneNumber(String phoneNumber) {
            this.phoneNumber = Optional.ofNullable(phoneNumber);
            return this;
        }

        /**
         * <p>Employer phone number.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "phone_number", nulls = Nulls.SKIP)
        public _FinalStage phoneNumber(Optional<String> phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * <p>Email address for billing and communications.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(Nullable<String> email) {
            if (email.isNull()) {
                this.email = null;
            } else if (email.isEmpty()) {
                this.email = Optional.empty();
            } else {
                this.email = Optional.of(email.get());
            }
            return this;
        }

        /**
         * <p>Email address for billing and communications.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>Email address for billing and communications.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public _FinalStage email(Optional<String> email) {
            this.email = email;
            return this;
        }

        /**
         * <p>Employer Identification Number (masked in responses).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage ein(Nullable<String> ein) {
            if (ein.isNull()) {
                this.ein = null;
            } else if (ein.isEmpty()) {
                this.ein = Optional.empty();
            } else {
                this.ein = Optional.of(ein.get());
            }
            return this;
        }

        /**
         * <p>Employer Identification Number (masked in responses).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage ein(String ein) {
            this.ein = Optional.ofNullable(ein);
            return this;
        }

        /**
         * <p>Employer Identification Number (masked in responses).</p>
         */
        @java.lang.Override
        @JsonSetter(value = "ein", nulls = Nulls.SKIP)
        public _FinalStage ein(Optional<String> ein) {
            this.ein = ein;
            return this;
        }

        /**
         * <p>Legal business name for compliance and tax purposes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage legalName(Nullable<String> legalName) {
            if (legalName.isNull()) {
                this.legalName = null;
            } else if (legalName.isEmpty()) {
                this.legalName = Optional.empty();
            } else {
                this.legalName = Optional.of(legalName.get());
            }
            return this;
        }

        /**
         * <p>Legal business name for compliance and tax purposes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage legalName(String legalName) {
            this.legalName = Optional.ofNullable(legalName);
            return this;
        }

        /**
         * <p>Legal business name for compliance and tax purposes.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "legal_name", nulls = Nulls.SKIP)
        public _FinalStage legalName(Optional<String> legalName) {
            this.legalName = legalName;
            return this;
        }

        /**
         * <p>The organization's own reference id for this employer, or null when none was assigned.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage referenceId(Nullable<String> referenceId) {
            if (referenceId.isNull()) {
                this.referenceId = null;
            } else if (referenceId.isEmpty()) {
                this.referenceId = Optional.empty();
            } else {
                this.referenceId = Optional.of(referenceId.get());
            }
            return this;
        }

        /**
         * <p>The organization's own reference id for this employer, or null when none was assigned.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage referenceId(String referenceId) {
            this.referenceId = Optional.ofNullable(referenceId);
            return this;
        }

        /**
         * <p>The organization's own reference id for this employer, or null when none was assigned.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "reference_id", nulls = Nulls.SKIP)
        public _FinalStage referenceId(Optional<String> referenceId) {
            this.referenceId = referenceId;
            return this;
        }

        /**
         * <p>ID of the parent organization (<code>org_*</code>), or null when unknown.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage organizationId(Nullable<String> organizationId) {
            if (organizationId.isNull()) {
                this.organizationId = null;
            } else if (organizationId.isEmpty()) {
                this.organizationId = Optional.empty();
            } else {
                this.organizationId = Optional.of(organizationId.get());
            }
            return this;
        }

        /**
         * <p>ID of the parent organization (<code>org_*</code>), or null when unknown.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage organizationId(String organizationId) {
            this.organizationId = Optional.ofNullable(organizationId);
            return this;
        }

        /**
         * <p>ID of the parent organization (<code>org_*</code>), or null when unknown.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "organization_id", nulls = Nulls.SKIP)
        public _FinalStage organizationId(Optional<String> organizationId) {
            this.organizationId = organizationId;
            return this;
        }

        @java.lang.Override
        public OrganizationEmployer build() {
            return new OrganizationEmployer(
                    employerId,
                    organizationId,
                    referenceId,
                    name,
                    legalName,
                    ein,
                    email,
                    phoneNumber,
                    active,
                    address,
                    createdAt,
                    updatedAt,
                    enrollmentRateSummary,
                    benefitFamilies,
                    hrisStatus,
                    benefitLifecycleStage,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
