/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PayrollAccessSetupStatus.Builder.class)
public final class PayrollAccessSetupStatus {
    private final boolean completed;

    private final Optional<OffsetDateTime> submittedAt;

    private final Map<String, Object> additionalProperties;

    private PayrollAccessSetupStatus(
            boolean completed, Optional<OffsetDateTime> submittedAt, Map<String, Object> additionalProperties) {
        this.completed = completed;
        this.submittedAt = submittedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether payroll access setup has been completed for this employer.
     */
    @JsonProperty("completed")
    public boolean getCompleted() {
        return completed;
    }

    /**
     * @return When the setup form was submitted (RFC 3339), or <code>null</code> if it has not been submitted.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getSubmittedAt() {
        if (submittedAt == null) {
            return Optional.empty();
        }
        return submittedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("submitted_at")
    private Optional<OffsetDateTime> _getSubmittedAt() {
        return submittedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PayrollAccessSetupStatus && equalTo((PayrollAccessSetupStatus) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PayrollAccessSetupStatus other) {
        return completed == other.completed && submittedAt.equals(other.submittedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.completed, this.submittedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CompletedStage builder() {
        return new Builder();
    }

    public interface CompletedStage {
        /**
         * <p>Whether payroll access setup has been completed for this employer.</p>
         */
        _FinalStage completed(boolean completed);

        Builder from(PayrollAccessSetupStatus other);
    }

    public interface _FinalStage {
        PayrollAccessSetupStatus build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>When the setup form was submitted (RFC 3339), or <code>null</code> if it has not been submitted.</p>
         */
        _FinalStage submittedAt(Optional<OffsetDateTime> submittedAt);

        _FinalStage submittedAt(OffsetDateTime submittedAt);

        _FinalStage submittedAt(Nullable<OffsetDateTime> submittedAt);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CompletedStage, _FinalStage {
        private boolean completed;

        private Optional<OffsetDateTime> submittedAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PayrollAccessSetupStatus other) {
            completed(other.getCompleted());
            submittedAt(other.getSubmittedAt());
            return this;
        }

        /**
         * <p>Whether payroll access setup has been completed for this employer.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("completed")
        public _FinalStage completed(boolean completed) {
            this.completed = completed;
            return this;
        }

        /**
         * <p>When the setup form was submitted (RFC 3339), or <code>null</code> if it has not been submitted.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage submittedAt(Nullable<OffsetDateTime> submittedAt) {
            if (submittedAt.isNull()) {
                this.submittedAt = null;
            } else if (submittedAt.isEmpty()) {
                this.submittedAt = Optional.empty();
            } else {
                this.submittedAt = Optional.of(submittedAt.get());
            }
            return this;
        }

        /**
         * <p>When the setup form was submitted (RFC 3339), or <code>null</code> if it has not been submitted.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage submittedAt(OffsetDateTime submittedAt) {
            this.submittedAt = Optional.ofNullable(submittedAt);
            return this;
        }

        /**
         * <p>When the setup form was submitted (RFC 3339), or <code>null</code> if it has not been submitted.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "submitted_at", nulls = Nulls.SKIP)
        public _FinalStage submittedAt(Optional<OffsetDateTime> submittedAt) {
            this.submittedAt = submittedAt;
            return this;
        }

        @java.lang.Override
        public PayrollAccessSetupStatus build() {
            return new PayrollAccessSetupStatus(completed, submittedAt, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
