/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PlanYearEnrollmentElectionStatus {
    public static final PlanYearEnrollmentElectionStatus WAIVED =
            new PlanYearEnrollmentElectionStatus(Value.WAIVED, "Waived");

    public static final PlanYearEnrollmentElectionStatus PENDING =
            new PlanYearEnrollmentElectionStatus(Value.PENDING, "Pending");

    public static final PlanYearEnrollmentElectionStatus EXPIRED =
            new PlanYearEnrollmentElectionStatus(Value.EXPIRED, "Expired");

    public static final PlanYearEnrollmentElectionStatus ENROLLED =
            new PlanYearEnrollmentElectionStatus(Value.ENROLLED, "Enrolled");

    private final Value value;

    private final String string;

    PlanYearEnrollmentElectionStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PlanYearEnrollmentElectionStatus
                        && this.string.equals(((PlanYearEnrollmentElectionStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WAIVED:
                return visitor.visitWaived();
            case PENDING:
                return visitor.visitPending();
            case EXPIRED:
                return visitor.visitExpired();
            case ENROLLED:
                return visitor.visitEnrolled();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PlanYearEnrollmentElectionStatus valueOf(String value) {
        switch (value) {
            case "Waived":
                return WAIVED;
            case "Pending":
                return PENDING;
            case "Expired":
                return EXPIRED;
            case "Enrolled":
                return ENROLLED;
            default:
                return new PlanYearEnrollmentElectionStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ENROLLED,

        WAIVED,

        PENDING,

        EXPIRED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitEnrolled();

        T visitWaived();

        T visitPending();

        T visitExpired();

        T visitUnknown(String unknownType);
    }
}
