/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class QualifyingLifeEventType {
    public static final QualifyingLifeEventType MOVED_TO_US =
            new QualifyingLifeEventType(Value.MOVED_TO_US, "moved_to_us");

    public static final QualifyingLifeEventType FOSTER_CARE_PLACEMENT =
            new QualifyingLifeEventType(Value.FOSTER_CARE_PLACEMENT, "foster_care_placement");

    public static final QualifyingLifeEventType MOVED_TO_OR_FROM_SCHOOL_HOUSING =
            new QualifyingLifeEventType(Value.MOVED_TO_OR_FROM_SCHOOL_HOUSING, "moved_to_or_from_school_housing");

    public static final QualifyingLifeEventType LOST_DECERTIFIED_INDIVIDUAL_PLAN =
            new QualifyingLifeEventType(Value.LOST_DECERTIFIED_INDIVIDUAL_PLAN, "lost_decertified_individual_plan");

    public static final QualifyingLifeEventType GAINED_TRIBAL_STATUS =
            new QualifyingLifeEventType(Value.GAINED_TRIBAL_STATUS, "gained_tribal_status");

    public static final QualifyingLifeEventType LOST_JOB_BASED_COVERAGE =
            new QualifyingLifeEventType(Value.LOST_JOB_BASED_COVERAGE, "lost_job_based_coverage");

    public static final QualifyingLifeEventType LOST_MEDICAID_CHIP_MEDICARE =
            new QualifyingLifeEventType(Value.LOST_MEDICAID_CHIP_MEDICARE, "lost_medicaid_chip_medicare");

    public static final QualifyingLifeEventType DEATH_OF_SPOUSE_OR_DEPENDENT =
            new QualifyingLifeEventType(Value.DEATH_OF_SPOUSE_OR_DEPENDENT, "death_of_spouse_or_dependent");

    public static final QualifyingLifeEventType OTHER = new QualifyingLifeEventType(Value.OTHER, "other");

    public static final QualifyingLifeEventType MARRIED = new QualifyingLifeEventType(Value.MARRIED, "married");

    public static final QualifyingLifeEventType LEFT_INCARCERATION =
            new QualifyingLifeEventType(Value.LEFT_INCARCERATION, "left_incarceration");

    public static final QualifyingLifeEventType STARTED_OR_ENDED_AMERICORPS_SERVICE = new QualifyingLifeEventType(
            Value.STARTED_OR_ENDED_AMERICORPS_SERVICE, "started_or_ended_americorps_service");

    public static final QualifyingLifeEventType AGED_OFF_PARENT_PLAN =
            new QualifyingLifeEventType(Value.AGED_OFF_PARENT_PLAN, "aged_off_parent_plan");

    public static final QualifyingLifeEventType MOVED_TO_NEW_COVERAGE_AREA =
            new QualifyingLifeEventType(Value.MOVED_TO_NEW_COVERAGE_AREA, "moved_to_new_coverage_area");

    public static final QualifyingLifeEventType BECAME_US_CITIZEN =
            new QualifyingLifeEventType(Value.BECAME_US_CITIZEN, "became_us_citizen");

    public static final QualifyingLifeEventType NEW_CHILD = new QualifyingLifeEventType(Value.NEW_CHILD, "new_child");

    public static final QualifyingLifeEventType DIVORCED = new QualifyingLifeEventType(Value.DIVORCED, "divorced");

    public static final QualifyingLifeEventType ADOPTED_CHILD =
            new QualifyingLifeEventType(Value.ADOPTED_CHILD, "adopted_child");

    public static final QualifyingLifeEventType HAD_BABY = new QualifyingLifeEventType(Value.HAD_BABY, "had_baby");

    public static final QualifyingLifeEventType MOVED_TO_OR_FROM_SEASONAL_WORK_HOUSING = new QualifyingLifeEventType(
            Value.MOVED_TO_OR_FROM_SEASONAL_WORK_HOUSING, "moved_to_or_from_seasonal_work_housing");

    public static final QualifyingLifeEventType COURT_ORDERED =
            new QualifyingLifeEventType(Value.COURT_ORDERED, "court_ordered");

    private final Value value;

    private final String string;

    QualifyingLifeEventType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof QualifyingLifeEventType
                        && this.string.equals(((QualifyingLifeEventType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case MOVED_TO_US:
                return visitor.visitMovedToUs();
            case FOSTER_CARE_PLACEMENT:
                return visitor.visitFosterCarePlacement();
            case MOVED_TO_OR_FROM_SCHOOL_HOUSING:
                return visitor.visitMovedToOrFromSchoolHousing();
            case LOST_DECERTIFIED_INDIVIDUAL_PLAN:
                return visitor.visitLostDecertifiedIndividualPlan();
            case GAINED_TRIBAL_STATUS:
                return visitor.visitGainedTribalStatus();
            case LOST_JOB_BASED_COVERAGE:
                return visitor.visitLostJobBasedCoverage();
            case LOST_MEDICAID_CHIP_MEDICARE:
                return visitor.visitLostMedicaidChipMedicare();
            case DEATH_OF_SPOUSE_OR_DEPENDENT:
                return visitor.visitDeathOfSpouseOrDependent();
            case OTHER:
                return visitor.visitOther();
            case MARRIED:
                return visitor.visitMarried();
            case LEFT_INCARCERATION:
                return visitor.visitLeftIncarceration();
            case STARTED_OR_ENDED_AMERICORPS_SERVICE:
                return visitor.visitStartedOrEndedAmericorpsService();
            case AGED_OFF_PARENT_PLAN:
                return visitor.visitAgedOffParentPlan();
            case MOVED_TO_NEW_COVERAGE_AREA:
                return visitor.visitMovedToNewCoverageArea();
            case BECAME_US_CITIZEN:
                return visitor.visitBecameUsCitizen();
            case NEW_CHILD:
                return visitor.visitNewChild();
            case DIVORCED:
                return visitor.visitDivorced();
            case ADOPTED_CHILD:
                return visitor.visitAdoptedChild();
            case HAD_BABY:
                return visitor.visitHadBaby();
            case MOVED_TO_OR_FROM_SEASONAL_WORK_HOUSING:
                return visitor.visitMovedToOrFromSeasonalWorkHousing();
            case COURT_ORDERED:
                return visitor.visitCourtOrdered();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static QualifyingLifeEventType valueOf(String value) {
        switch (value) {
            case "moved_to_us":
                return MOVED_TO_US;
            case "foster_care_placement":
                return FOSTER_CARE_PLACEMENT;
            case "moved_to_or_from_school_housing":
                return MOVED_TO_OR_FROM_SCHOOL_HOUSING;
            case "lost_decertified_individual_plan":
                return LOST_DECERTIFIED_INDIVIDUAL_PLAN;
            case "gained_tribal_status":
                return GAINED_TRIBAL_STATUS;
            case "lost_job_based_coverage":
                return LOST_JOB_BASED_COVERAGE;
            case "lost_medicaid_chip_medicare":
                return LOST_MEDICAID_CHIP_MEDICARE;
            case "death_of_spouse_or_dependent":
                return DEATH_OF_SPOUSE_OR_DEPENDENT;
            case "other":
                return OTHER;
            case "married":
                return MARRIED;
            case "left_incarceration":
                return LEFT_INCARCERATION;
            case "started_or_ended_americorps_service":
                return STARTED_OR_ENDED_AMERICORPS_SERVICE;
            case "aged_off_parent_plan":
                return AGED_OFF_PARENT_PLAN;
            case "moved_to_new_coverage_area":
                return MOVED_TO_NEW_COVERAGE_AREA;
            case "became_us_citizen":
                return BECAME_US_CITIZEN;
            case "new_child":
                return NEW_CHILD;
            case "divorced":
                return DIVORCED;
            case "adopted_child":
                return ADOPTED_CHILD;
            case "had_baby":
                return HAD_BABY;
            case "moved_to_or_from_seasonal_work_housing":
                return MOVED_TO_OR_FROM_SEASONAL_WORK_HOUSING;
            case "court_ordered":
                return COURT_ORDERED;
            default:
                return new QualifyingLifeEventType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        LOST_JOB_BASED_COVERAGE,

        AGED_OFF_PARENT_PLAN,

        LOST_MEDICAID_CHIP_MEDICARE,

        LOST_DECERTIFIED_INDIVIDUAL_PLAN,

        MARRIED,

        DIVORCED,

        HAD_BABY,

        ADOPTED_CHILD,

        FOSTER_CARE_PLACEMENT,

        DEATH_OF_SPOUSE_OR_DEPENDENT,

        COURT_ORDERED,

        MOVED_TO_NEW_COVERAGE_AREA,

        MOVED_TO_US,

        MOVED_TO_OR_FROM_SCHOOL_HOUSING,

        MOVED_TO_OR_FROM_SEASONAL_WORK_HOUSING,

        BECAME_US_CITIZEN,

        LEFT_INCARCERATION,

        GAINED_TRIBAL_STATUS,

        STARTED_OR_ENDED_AMERICORPS_SERVICE,

        NEW_CHILD,

        OTHER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitLostJobBasedCoverage();

        T visitAgedOffParentPlan();

        T visitLostMedicaidChipMedicare();

        T visitLostDecertifiedIndividualPlan();

        T visitMarried();

        T visitDivorced();

        T visitHadBaby();

        T visitAdoptedChild();

        T visitFosterCarePlacement();

        T visitDeathOfSpouseOrDependent();

        T visitCourtOrdered();

        T visitMovedToNewCoverageArea();

        T visitMovedToUs();

        T visitMovedToOrFromSchoolHousing();

        T visitMovedToOrFromSeasonalWorkHousing();

        T visitBecameUsCitizen();

        T visitLeftIncarceration();

        T visitGainedTribalStatus();

        T visitStartedOrEndedAmericorpsService();

        T visitNewChild();

        T visitOther();

        T visitUnknown(String unknownType);
    }
}
