/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ReissueEnrollment.Builder.class)
public final class ReissueEnrollment {
    private final String enrollmentId;

    private final Map<String, Object> additionalProperties;

    private ReissueEnrollment(String enrollmentId, Map<String, Object> additionalProperties) {
        this.enrollmentId = enrollmentId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Opaque identifier for the new unanswered enrollment
     */
    @JsonProperty("enrollment_id")
    public String getEnrollmentId() {
        return enrollmentId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ReissueEnrollment && equalTo((ReissueEnrollment) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ReissueEnrollment other) {
        return enrollmentId.equals(other.enrollmentId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.enrollmentId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EnrollmentIdStage builder() {
        return new Builder();
    }

    public interface EnrollmentIdStage {
        /**
         * <p>Opaque identifier for the new unanswered enrollment</p>
         */
        _FinalStage enrollmentId(@NotNull String enrollmentId);

        Builder from(ReissueEnrollment other);
    }

    public interface _FinalStage {
        ReissueEnrollment build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EnrollmentIdStage, _FinalStage {
        private String enrollmentId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ReissueEnrollment other) {
            enrollmentId(other.getEnrollmentId());
            return this;
        }

        /**
         * <p>Opaque identifier for the new unanswered enrollment</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("enrollment_id")
        public _FinalStage enrollmentId(@NotNull String enrollmentId) {
            this.enrollmentId = Objects.requireNonNull(enrollmentId, "enrollmentId must not be null");
            return this;
        }

        @java.lang.Override
        public ReissueEnrollment build() {
            return new ReissueEnrollment(enrollmentId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
