/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class Relationship {
    public static final Relationship CHILD = new Relationship(Value.CHILD, "Child");

    public static final Relationship SPOUSE = new Relationship(Value.SPOUSE, "Spouse");

    private final Value value;

    private final String string;

    Relationship(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof Relationship && this.string.equals(((Relationship) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CHILD:
                return visitor.visitChild();
            case SPOUSE:
                return visitor.visitSpouse();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static Relationship valueOf(String value) {
        switch (value) {
            case "Child":
                return CHILD;
            case "Spouse":
                return SPOUSE;
            default:
                return new Relationship(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SPOUSE,

        CHILD,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSpouse();

        T visitChild();

        T visitUnknown(String unknownType);
    }
}
