/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class Status {
    public static final Status APPROVED = new Status(Value.APPROVED, "approved");

    public static final Status PENDING = new Status(Value.PENDING, "pending");

    public static final Status DENIED = new Status(Value.DENIED, "denied");

    private final Value value;

    private final String string;

    Status(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof Status && this.string.equals(((Status) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case APPROVED:
                return visitor.visitApproved();
            case PENDING:
                return visitor.visitPending();
            case DENIED:
                return visitor.visitDenied();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static Status valueOf(String value) {
        switch (value) {
            case "approved":
                return APPROVED;
            case "pending":
                return PENDING;
            case "denied":
                return DENIED;
            default:
                return new Status(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        APPROVED,

        DENIED,

        PENDING,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitApproved();

        T visitDenied();

        T visitPending();

        T visitUnknown(String unknownType);
    }
}
