/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TerminationRule {
    public static final TerminationRule END_OF_N_MONTHS = new TerminationRule(Value.END_OF_N_MONTHS, "END_OF_N_MONTHS");

    public static final TerminationRule END_OF_PLAN_YEAR =
            new TerminationRule(Value.END_OF_PLAN_YEAR, "END_OF_PLAN_YEAR");

    private final Value value;

    private final String string;

    TerminationRule(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof TerminationRule && this.string.equals(((TerminationRule) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case END_OF_N_MONTHS:
                return visitor.visitEndOfNMonths();
            case END_OF_PLAN_YEAR:
                return visitor.visitEndOfPlanYear();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TerminationRule valueOf(String value) {
        switch (value) {
            case "END_OF_N_MONTHS":
                return END_OF_N_MONTHS;
            case "END_OF_PLAN_YEAR":
                return END_OF_PLAN_YEAR;
            default:
                return new TerminationRule(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        END_OF_N_MONTHS,

        END_OF_PLAN_YEAR,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitEndOfNMonths();

        T visitEndOfPlanYear();

        T visitUnknown(String unknownType);
    }
}
