/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.resources.groups.members.sync;

import com.vitablehealth.connect.core.ClientOptions;
import com.vitablehealth.connect.core.RequestOptions;
import com.vitablehealth.connect.resources.groups.members.sync.requests.GetSyncRequest;
import com.vitablehealth.connect.resources.groups.members.sync.requests.GroupMemberSyncRequest;
import com.vitablehealth.connect.types.GroupMemberSyncDetailResponse;
import com.vitablehealth.connect.types.GroupMemberSyncRequestDetailResponse;

public class SyncClient {
    protected final ClientOptions clientOptions;

    private final RawSyncClient rawClient;

    public SyncClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSyncClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSyncClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Submits a member sync payload for the specified group. Members in the payload will be queued for processing asynchronously. Returns HTTP 202 with the batch ID and acceptance timestamp.
     */
    public GroupMemberSyncDetailResponse submit(String groupId, GroupMemberSyncRequest request) {
        return this.rawClient.submit(groupId, request).body();
    }

    /**
     * Submits a member sync payload for the specified group. Members in the payload will be queued for processing asynchronously. Returns HTTP 202 with the batch ID and acceptance timestamp.
     */
    public GroupMemberSyncDetailResponse submit(
            String groupId, GroupMemberSyncRequest request, RequestOptions requestOptions) {
        return this.rawClient.submit(groupId, request, requestOptions).body();
    }

    /**
     * Retrieves a previously-submitted group member sync request by its <code>grpmsr_</code> ID. Returns the acceptance timestamp, completion timestamp (if processing has finished), and the per-member <code>results</code> once available. While processing is in flight, <code>completed_at</code> and <code>results</code> are <code>null</code>.
     */
    public GroupMemberSyncRequestDetailResponse get(String groupId, String requestId) {
        return this.rawClient.get(groupId, requestId).body();
    }

    /**
     * Retrieves a previously-submitted group member sync request by its <code>grpmsr_</code> ID. Returns the acceptance timestamp, completion timestamp (if processing has finished), and the per-member <code>results</code> once available. While processing is in flight, <code>completed_at</code> and <code>results</code> are <code>null</code>.
     */
    public GroupMemberSyncRequestDetailResponse get(String groupId, String requestId, RequestOptions requestOptions) {
        return this.rawClient.get(groupId, requestId, requestOptions).body();
    }

    /**
     * Retrieves a previously-submitted group member sync request by its <code>grpmsr_</code> ID. Returns the acceptance timestamp, completion timestamp (if processing has finished), and the per-member <code>results</code> once available. While processing is in flight, <code>completed_at</code> and <code>results</code> are <code>null</code>.
     */
    public GroupMemberSyncRequestDetailResponse get(String groupId, String requestId, GetSyncRequest request) {
        return this.rawClient.get(groupId, requestId, request).body();
    }

    /**
     * Retrieves a previously-submitted group member sync request by its <code>grpmsr_</code> ID. Returns the acceptance timestamp, completion timestamp (if processing has finished), and the per-member <code>results</code> once available. While processing is in flight, <code>completed_at</code> and <code>results</code> are <code>null</code>.
     */
    public GroupMemberSyncRequestDetailResponse get(
            String groupId, String requestId, GetSyncRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(groupId, requestId, request, requestOptions).body();
    }
}
