/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.resources.employers.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import com.vitablehealth.connect.types.CensusSyncEmployeeRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CensusSyncRequest.Builder.class)
public final class CensusSyncRequest {
    private final List<CensusSyncEmployeeRequest> employees;

    private final Map<String, Object> additionalProperties;

    private CensusSyncRequest(List<CensusSyncEmployeeRequest> employees, Map<String, Object> additionalProperties) {
        this.employees = employees;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("employees")
    public List<CensusSyncEmployeeRequest> getEmployees() {
        return employees;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CensusSyncRequest && equalTo((CensusSyncRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CensusSyncRequest other) {
        return employees.equals(other.employees);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.employees);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<CensusSyncEmployeeRequest> employees = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CensusSyncRequest other) {
            employees(other.getEmployees());
            return this;
        }

        @JsonSetter(value = "employees", nulls = Nulls.SKIP)
        public Builder employees(List<CensusSyncEmployeeRequest> employees) {
            this.employees.clear();
            if (employees != null) {
                this.employees.addAll(employees);
            }
            return this;
        }

        public Builder addEmployees(CensusSyncEmployeeRequest employees) {
            this.employees.add(employees);
            return this;
        }

        public Builder addAllEmployees(List<CensusSyncEmployeeRequest> employees) {
            if (employees != null) {
                this.employees.addAll(employees);
            }
            return this;
        }

        public CensusSyncRequest build() {
            return new CensusSyncRequest(employees, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
