/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.resources.employers.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.Nullable;
import com.vitablehealth.connect.core.NullableNonemptyFilter;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListInvoicesEmployersRequest.Builder.class)
public final class ListInvoicesEmployersRequest {
    private final Optional<String> vitableOrganization;

    private final Optional<Integer> limit;

    private final Optional<String> offset;

    private final Map<String, Object> additionalProperties;

    private ListInvoicesEmployersRequest(
            Optional<String> vitableOrganization,
            Optional<Integer> limit,
            Optional<String> offset,
            Map<String, Object> additionalProperties) {
        this.vitableOrganization = vitableOrganization;
        this.limit = limit;
        this.offset = offset;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Organization to act as for this request (e.g. <code>org_SGVsbG8gV29ybGQ</code>). Optional when your credentials reach a single organization. Required when they reach several — omitting it then returns 400 <code>organization_required</code>. A malformed value returns 400 <code>invalid_organization_header</code>, and naming an organization you do not have access to returns 403 <code>organization_access_denied</code>.
     */
    @JsonIgnore
    public Optional<String> getVitableOrganization() {
        return vitableOrganization;
    }

    /**
     * @return Maximum number of invoices per page
     */
    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    /**
     * @return Opaque cursor from a previous page's next_offset
     */
    @JsonIgnore
    public Optional<String> getOffset() {
        if (offset == null) {
            return Optional.empty();
        }
        return offset;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("offset")
    private Optional<String> _getOffset() {
        return offset;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListInvoicesEmployersRequest && equalTo((ListInvoicesEmployersRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListInvoicesEmployersRequest other) {
        return vitableOrganization.equals(other.vitableOrganization)
                && limit.equals(other.limit)
                && offset.equals(other.offset);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.vitableOrganization, this.limit, this.offset);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> vitableOrganization = Optional.empty();

        private Optional<Integer> limit = Optional.empty();

        private Optional<String> offset = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListInvoicesEmployersRequest other) {
            vitableOrganization(other.getVitableOrganization());
            limit(other.getLimit());
            offset(other.getOffset());
            return this;
        }

        /**
         * <p>Organization to act as for this request (e.g. <code>org_SGVsbG8gV29ybGQ</code>). Optional when your credentials reach a single organization. Required when they reach several — omitting it then returns 400 <code>organization_required</code>. A malformed value returns 400 <code>invalid_organization_header</code>, and naming an organization you do not have access to returns 403 <code>organization_access_denied</code>.</p>
         */
        public Builder vitableOrganization(Optional<String> vitableOrganization) {
            this.vitableOrganization = vitableOrganization;
            return this;
        }

        public Builder vitableOrganization(String vitableOrganization) {
            this.vitableOrganization = Optional.ofNullable(vitableOrganization);
            return this;
        }

        /**
         * <p>Maximum number of invoices per page</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Opaque cursor from a previous page's next_offset</p>
         */
        @JsonSetter(value = "offset", nulls = Nulls.SKIP)
        public Builder offset(Optional<String> offset) {
            this.offset = offset;
            return this;
        }

        public Builder offset(String offset) {
            this.offset = Optional.ofNullable(offset);
            return this;
        }

        public Builder offset(Nullable<String> offset) {
            if (offset.isNull()) {
                this.offset = null;
            } else if (offset.isEmpty()) {
                this.offset = Optional.empty();
            } else {
                this.offset = Optional.of(offset.get());
            }
            return this;
        }

        public ListInvoicesEmployersRequest build() {
            return new ListInvoicesEmployersRequest(vitableOrganization, limit, offset, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
