/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.resources.webhookevents.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import com.vitablehealth.connect.types.EventName;
import com.vitablehealth.connect.types.ResourceType;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListWebhookEventsRequest.Builder.class)
public final class ListWebhookEventsRequest {
    private final Optional<OffsetDateTime> createdAfter;

    private final Optional<OffsetDateTime> createdBefore;

    private final Optional<EventName> eventName;

    private final Optional<Integer> limit;

    private final Optional<Integer> page;

    private final Optional<String> resourceId;

    private final Optional<ResourceType> resourceType;

    private final Map<String, Object> additionalProperties;

    private ListWebhookEventsRequest(
            Optional<OffsetDateTime> createdAfter,
            Optional<OffsetDateTime> createdBefore,
            Optional<EventName> eventName,
            Optional<Integer> limit,
            Optional<Integer> page,
            Optional<String> resourceId,
            Optional<ResourceType> resourceType,
            Map<String, Object> additionalProperties) {
        this.createdAfter = createdAfter;
        this.createdBefore = createdBefore;
        this.eventName = eventName;
        this.limit = limit;
        this.page = page;
        this.resourceId = resourceId;
        this.resourceType = resourceType;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("created_after")
    public Optional<OffsetDateTime> getCreatedAfter() {
        return createdAfter;
    }

    @JsonProperty("created_before")
    public Optional<OffsetDateTime> getCreatedBefore() {
        return createdBefore;
    }

    /**
     * @return <ul>
     * <li><code>enrollment.accepted</code> - Enrollment Accepted</li>
     * <li><code>enrollment.terminated</code> - Enrollment Terminated</li>
     * <li><code>enrollment.termination_rescheduled</code> - Enrollment Termination Rescheduled</li>
     * <li><code>enrollment.elected</code> - Enrollment Elected</li>
     * <li><code>enrollment.granted</code> - Enrollment Granted</li>
     * <li><code>enrollment.waived</code> - Enrollment Waived</li>
     * <li><code>enrollment.started</code> - Enrollment Started</li>
     * <li><code>employee.eligibility_granted</code> - Employee Eligibility Granted</li>
     * <li><code>employee.eligibility_terminated</code> - Employee Eligibility Terminated</li>
     * <li><code>employee.deactivated</code> - Employee Deactivated</li>
     * <li><code>employee.deduction_created</code> - Employee Deduction Created</li>
     * </ul>
     */
    @JsonProperty("event_name")
    public Optional<EventName> getEventName() {
        return eventName;
    }

    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    @JsonProperty("page")
    public Optional<Integer> getPage() {
        return page;
    }

    @JsonProperty("resource_id")
    public Optional<String> getResourceId() {
        return resourceId;
    }

    /**
     * @return <ul>
     * <li><code>enrollment</code> - Enrollment</li>
     * <li><code>employee</code> - Employee</li>
     * <li><code>employer</code> - Employer</li>
     * <li><code>dependent</code> - Dependent</li>
     * <li><code>plan_year</code> - Plan Year</li>
     * <li><code>payroll_deduction</code> - Payroll Deduction</li>
     * </ul>
     */
    @JsonProperty("resource_type")
    public Optional<ResourceType> getResourceType() {
        return resourceType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListWebhookEventsRequest && equalTo((ListWebhookEventsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListWebhookEventsRequest other) {
        return createdAfter.equals(other.createdAfter)
                && createdBefore.equals(other.createdBefore)
                && eventName.equals(other.eventName)
                && limit.equals(other.limit)
                && page.equals(other.page)
                && resourceId.equals(other.resourceId)
                && resourceType.equals(other.resourceType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.createdAfter,
                this.createdBefore,
                this.eventName,
                this.limit,
                this.page,
                this.resourceId,
                this.resourceType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<OffsetDateTime> createdAfter = Optional.empty();

        private Optional<OffsetDateTime> createdBefore = Optional.empty();

        private Optional<EventName> eventName = Optional.empty();

        private Optional<Integer> limit = Optional.empty();

        private Optional<Integer> page = Optional.empty();

        private Optional<String> resourceId = Optional.empty();

        private Optional<ResourceType> resourceType = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListWebhookEventsRequest other) {
            createdAfter(other.getCreatedAfter());
            createdBefore(other.getCreatedBefore());
            eventName(other.getEventName());
            limit(other.getLimit());
            page(other.getPage());
            resourceId(other.getResourceId());
            resourceType(other.getResourceType());
            return this;
        }

        @JsonSetter(value = "created_after", nulls = Nulls.SKIP)
        public Builder createdAfter(Optional<OffsetDateTime> createdAfter) {
            this.createdAfter = createdAfter;
            return this;
        }

        public Builder createdAfter(OffsetDateTime createdAfter) {
            this.createdAfter = Optional.ofNullable(createdAfter);
            return this;
        }

        @JsonSetter(value = "created_before", nulls = Nulls.SKIP)
        public Builder createdBefore(Optional<OffsetDateTime> createdBefore) {
            this.createdBefore = createdBefore;
            return this;
        }

        public Builder createdBefore(OffsetDateTime createdBefore) {
            this.createdBefore = Optional.ofNullable(createdBefore);
            return this;
        }

        /**
         * <ul>
         * <li><code>enrollment.accepted</code> - Enrollment Accepted</li>
         * <li><code>enrollment.terminated</code> - Enrollment Terminated</li>
         * <li><code>enrollment.termination_rescheduled</code> - Enrollment Termination Rescheduled</li>
         * <li><code>enrollment.elected</code> - Enrollment Elected</li>
         * <li><code>enrollment.granted</code> - Enrollment Granted</li>
         * <li><code>enrollment.waived</code> - Enrollment Waived</li>
         * <li><code>enrollment.started</code> - Enrollment Started</li>
         * <li><code>employee.eligibility_granted</code> - Employee Eligibility Granted</li>
         * <li><code>employee.eligibility_terminated</code> - Employee Eligibility Terminated</li>
         * <li><code>employee.deactivated</code> - Employee Deactivated</li>
         * <li><code>employee.deduction_created</code> - Employee Deduction Created</li>
         * </ul>
         */
        @JsonSetter(value = "event_name", nulls = Nulls.SKIP)
        public Builder eventName(Optional<EventName> eventName) {
            this.eventName = eventName;
            return this;
        }

        public Builder eventName(EventName eventName) {
            this.eventName = Optional.ofNullable(eventName);
            return this;
        }

        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        @JsonSetter(value = "page", nulls = Nulls.SKIP)
        public Builder page(Optional<Integer> page) {
            this.page = page;
            return this;
        }

        public Builder page(Integer page) {
            this.page = Optional.ofNullable(page);
            return this;
        }

        @JsonSetter(value = "resource_id", nulls = Nulls.SKIP)
        public Builder resourceId(Optional<String> resourceId) {
            this.resourceId = resourceId;
            return this;
        }

        public Builder resourceId(String resourceId) {
            this.resourceId = Optional.ofNullable(resourceId);
            return this;
        }

        /**
         * <ul>
         * <li><code>enrollment</code> - Enrollment</li>
         * <li><code>employee</code> - Employee</li>
         * <li><code>employer</code> - Employer</li>
         * <li><code>dependent</code> - Dependent</li>
         * <li><code>plan_year</code> - Plan Year</li>
         * <li><code>payroll_deduction</code> - Payroll Deduction</li>
         * </ul>
         */
        @JsonSetter(value = "resource_type", nulls = Nulls.SKIP)
        public Builder resourceType(Optional<ResourceType> resourceType) {
            this.resourceType = resourceType;
            return this;
        }

        public Builder resourceType(ResourceType resourceType) {
            this.resourceType = Optional.ofNullable(resourceType);
            return this;
        }

        public ListWebhookEventsRequest build() {
            return new ListWebhookEventsRequest(
                    createdAfter,
                    createdBefore,
                    eventName,
                    limit,
                    page,
                    resourceId,
                    resourceType,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
