/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.resources.groups.members.sync.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import com.vitablehealth.connect.types.GroupMemberSyncMemberRequest;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GroupMemberSyncRequest.Builder.class)
public final class GroupMemberSyncRequest {
    private final List<GroupMemberSyncMemberRequest> members;

    private final Map<String, Object> additionalProperties;

    private GroupMemberSyncRequest(
            List<GroupMemberSyncMemberRequest> members, Map<String, Object> additionalProperties) {
        this.members = members;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("members")
    public List<GroupMemberSyncMemberRequest> getMembers() {
        return members;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GroupMemberSyncRequest && equalTo((GroupMemberSyncRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GroupMemberSyncRequest other) {
        return members.equals(other.members);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.members);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<GroupMemberSyncMemberRequest> members = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GroupMemberSyncRequest other) {
            members(other.getMembers());
            return this;
        }

        @JsonSetter(value = "members", nulls = Nulls.SKIP)
        public Builder members(List<GroupMemberSyncMemberRequest> members) {
            this.members.clear();
            if (members != null) {
                this.members.addAll(members);
            }
            return this;
        }

        public Builder addMembers(GroupMemberSyncMemberRequest members) {
            this.members.add(members);
            return this;
        }

        public Builder addAllMembers(List<GroupMemberSyncMemberRequest> members) {
            if (members != null) {
                this.members.addAll(members);
            }
            return this;
        }

        public GroupMemberSyncRequest build() {
            return new GroupMemberSyncRequest(members, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
