/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.vitablehealth.connect.resources.employees.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vitablehealth.connect.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListEnrollmentsEmployeesRequest.Builder.class)
public final class ListEnrollmentsEmployeesRequest {
    private final Optional<Integer> limit;

    private final Optional<Integer> page;

    private final Map<String, Object> additionalProperties;

    private ListEnrollmentsEmployeesRequest(
            Optional<Integer> limit, Optional<Integer> page, Map<String, Object> additionalProperties) {
        this.limit = limit;
        this.page = page;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Items per page (default: 20, max: 100)
     */
    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    /**
     * @return Page number (default: 1)
     */
    @JsonProperty("page")
    public Optional<Integer> getPage() {
        return page;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListEnrollmentsEmployeesRequest && equalTo((ListEnrollmentsEmployeesRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListEnrollmentsEmployeesRequest other) {
        return limit.equals(other.limit) && page.equals(other.page);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.limit, this.page);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> limit = Optional.empty();

        private Optional<Integer> page = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListEnrollmentsEmployeesRequest other) {
            limit(other.getLimit());
            page(other.getPage());
            return this;
        }

        /**
         * <p>Items per page (default: 20, max: 100)</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Page number (default: 1)</p>
         */
        @JsonSetter(value = "page", nulls = Nulls.SKIP)
        public Builder page(Optional<Integer> page) {
            this.page = page;
            return this;
        }

        public Builder page(Integer page) {
            this.page = Optional.ofNullable(page);
            return this;
        }

        public ListEnrollmentsEmployeesRequest build() {
            return new ListEnrollmentsEmployeesRequest(limit, page, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
